### ISSUE TITLE
Command to take screenshots

### ISSUE THREAD

**Issue by bobatsar** [mobile-dev-inc/maestro#100]
Is there any command planned to take screenshots?
This would be very handy to document changes between different versions of an app.

**Comment by dmitry-zaitsev** [comment]
That would be relatively easy to add, so we will address this soon 👍

**Comment by ca-ke** [comment]
@dmitry-zaitsev we can use dadb to take screenshots via adb. I do think that we can go with something like this

`adb shell screencasts -p /sdcard/$name`
`adb pull /sdcard/$name $opt`
`adb shell em /sdcard/$name`

**Comment by dmitry-zaitsev** [comment]
@ca-ke indeed, that is more or less how it would go. If you like to give it a try, I can guide you through the implementation steps

**Comment by ragunathjawahar** [comment]
@dmitry-zaitsev and @ca-ke do you folks have a DSL in mind?

**Comment by dmitry-zaitsev** [comment]
Something like:

```
- takeScreenshot: {file name}
```

**Comment by dmitry-zaitsev** [comment]
Good news - this is now available in 1.7.0: https://maestro.mobile.dev/reference/take-screenshot

Credit for Android implementation goes to @ragunathjawahar , thank you!
