### ISSUE TITLE
Bug : testTagsAsResourceId = true does not work in jetpack compose based project 

### ISSUE THREAD

**Issue by rohit-dharap** [mobile-dev-inc/maestro#1013]
As per [documentation](https://maestro.mobile.dev/platform-support/android-jetpack-compose), I added `testTagsAsResourceId = true` in composable and tried to tap on element using test tag as id. But it is not working.

**Comment by felipevolpone** [comment]
@rohit-dharap can you provide more info about the problem you're facing? It's not working how? An example of flow you're using? Which app? It's React Native, iOS or Android?

**Comment by PedroKcz** [comment]
I'm having the same issue while running Maestro on Android 13 (API 33), previous versions of Android are working fine
