### ISSUE TITLE
login email missing button

### ISSUE THREAD

**Issue by ethanneff** [mobile-dev-inc/maestro#1028]
<img width="1148" alt="Screen Shot 2023-04-28 at 12 08 47 PM" src="https://user-images.githubusercontent.com/2933593/235232876-fc55f808-5322-4e64-9629-9447f20c8701.png">

**Comment by axelniklasson** [comment]
@ethanneff looks like there might be an issue with your email client, as there should be a sign in button below the `Maestro Cloud` title like below:

<img width="889" alt="image" src="https://user-images.githubusercontent.com/6113675/235588196-910bdd3d-6e20-413d-8fb8-28783a7bb59e.png">
