### ISSUE TITLE
Multiple Taps happening on Jetpack Compose app

### ISSUE THREAD

**Issue by sanskar10100** [mobile-dev-inc/maestro#104]
I'm trying out version 1.4.0 of Maestro on a Jetpack Compose app, and wrote this yaml:

```
appId: dev.sanskar.photoplay
---
- launchApp
- tapOn: "Thor: Love and Thunder"
- tapOn: "Add To Watchlist"
- tapOn: "MCU"
- tapOn: "Save"
- back
- tapOn: "Thor: Love and Thunder"
- tapOn: "Add To Watchlist"
```

But, as observed in the [video](https://drive.google.com/file/d/1eg1FCle3Tu3Cz7aFS-xcFLFCHNtxbkJE/view?usp=sharing), there are multiple taps on the MCU entry. I was expecting only one tap to happen. Could it be because the list recomposes on tap?

**Comment by dmitry-zaitsev** [comment]
Thanks for reporting! This is sort of a feature and a bug at the same time. What is happening here is that Maestro tries to compare view hierarchy before and after tap, sees no difference (checkbox status does not produce a new view hierarchy) and decides to try tapping again.

To disable this behaviour, you can replace command with this:

```
- tapOn:
      text: "MCU"
      retryTapIfNoChange: false
```
