### ISSUE TITLE
Command to set a Geo location

### ISSUE THREAD

**Issue by dmitry-zaitsev** [mobile-dev-inc/maestro#105]
This appears to be doable:

- [Android](https://stackoverflow.com/a/2587369/926907)
- [iOS](https://fbidb.io/docs/commands#set-a-simulators-location)

**Comment by ragunathjawahar** [comment]
Can you help with how the DSL should look like for this?

**A**
```
location: -82.411629 28.054553
```

**B**
```
location:
    lat: -82.411629
    long: 28.054553
```

**Something else** 
```
?
```

Once we have a consensus on this, I can pick it up.

**Comment by dmitry-zaitsev** [comment]
I would suggest we start with option B. We could add option A in addition to option B later on, but I think this is not super important.

**Comment by ragunathjawahar** [comment]
I'll pick this up later today, if anyone is already working on this please update?

**Comment by amanjeetsingh150** [comment]
Added this command in latest release.
