### ISSUE TITLE
Access flow name in mock server

### ISSUE THREAD

**Issue by SebastianKlaiber** [mobile-dev-inc/maestro#1050]
**Is your feature request related to a problem? Please describe.**
I need access to the flow name in the mock server javascript file. With this information, I have the possibility to decide which response should be returned.

**Describe the solution you'd like**
get('/bound_devices', (req, res, session) => {
	session.flowName;
});

or extend the Handler

type Handler = (req: Request, res: Response, session?: Session, flowName: String)

**Additional context**
I'm building a credit card management app and If there is a new card, the card needs some activation. After the card is activation, the user can use all features of the app. 

I could run the activation as part of a subflow before my current flow to activate the card and save it in the session object. But I don't like to be dependent on this flow all the time. And that's not the only API Call where I have a one time operation.

If there is a better way to archive this, please let me know.

**Comment by SebastianKlaiber** [comment]
An alternative might be to have an index.js per flow that is then only used for this flow.

**Comment by felipevolpone** [comment]
As the mock server feature was deprecated, I'm closing this as not relevant anymore
