### ISSUE TITLE
Command to copy text

### ISSUE THREAD

**Issue by ateslovan** [mobile-dev-inc/maestro#106]
Would love to have the option to copy the text from a view so it can be checked against some other view. This would also bring in discussion a new assert - assertTextEquals - or something similar.

**Comment by dmitry-zaitsev** [comment]
That is doable and indeed makes sense - we will add this

**Comment by ArthurSav** [comment]
#403 Adds copy text from element and paste into text field. 
@ateslovan Does this resolve your issue?

**Comment by ateslovan** [comment]
@ArthurSav Great news & addition! But I was thinking of something more 'complicated' when writing this request.

I'm thinking of a case where you have 2 screens:
- One where you can add favourites
- One where you can see favourites

The case I would test would sound something like: Add a favorite then make sure the favorite appears on favourites screen.

Using the getText method you could compare that the text of the favourite item from the first screen appears on the second screen - but I would also like an assertEquals method so that the test fails in case this isn't true.

so, in the end I think we would need:
- getText method
- a way to save the getText in a variable
- an assert to compare two text values

Does it make sense?

**Comment by dmitry-zaitsev** [comment]
@ateslovan the next release of Maestro (1.16.0) will include some basic Javascript support that will make such usecase possible. The logic would then be something like this:

```
- copyTextFrom: "Field A"
- evalScript: ${output.fieldA = maestro.copiedText}
- copyTextFrom: "Field B"
- assertTrue: ${output.fieldA == maestro.copiedText}
```

**Comment by ateslovan** [comment]
Awesome! I think that will do the job

**Comment by dmitry-zaitsev** [comment]
This is live now in Maestro 1.16.0

https://maestro.mobile.dev/advanced/javascript/access-element-text
