### ISSUE TITLE
[v1.27.0] idb_companion does not start in time

### ISSUE THREAD

**Issue by RomainKB** [mobile-dev-inc/maestro#1063]
**Describe the bug**
I have a problem when I try to run a test or event the maestro studio on an iphone emulator. It seems that idb_companion did not start in time. I have tried with 2 differents emulators (iphone 16.4 and ipad 15.2), restart my mac, fresh clean installation of idb, ... Everything on my side is working. I can see devices with "idb list targets" and then with  "idb list-apps --udid {UUID of my emulator}" I get the package name of the app I want to test. But still stuck on the maestro command step. My maestro version is 1.27.0 and I tried to contact the slack support but your collegue told me to finally open this ticket as nothing works. 

Moreover I found that on your repo : https://github.com/mobile-dev-inc/maestro/pull/370/files 
Which seems to try to fix the same problem that I still have 

**To Reproduce**
Steps to reproduce the behavior, e.g.:
1. Start the simulator
2. Run `maestro test` or "maestro studio"

**Expected behavior**
I expecte the test to start or the studio to start.

**Screenshots**
![image](https://github.com/mobile-dev-inc/maestro/assets/32517335/25c8d324-e481-4d8b-ab43-661e9389541b)

**Environment information (please complete the following information):**

- Maestro version [v1.27.0]
- Platform: [iOS 16.4.1, iOS 15.2]
- Device model and OS version: [iphone pro max and  iPad mini (6th generation)]
- Simulator with xCode
- Host [Mac M1]

**Comment by samuelgja** [comment]
what is going on with this? I have same issue.

**Comment by MaxenceChantome** [comment]
Hey, I am also facing the same issue. Could you let me know if you managed to find a way to fix it?

**Comment by SamarthKejriwal** [comment]
Same issue faced by me also

**Comment by felipevolpone** [comment]
We don't relly on idb_companion anymore, so I'm closing this as not relevant anymore
