### ISSUE TITLE
[Feature Request] - Add an option to export test results in HTML format

### ISSUE THREAD

**Issue by venkat2789** [mobile-dev-inc/maestro#1067]
**Is your feature request related to a problem? Please describe.**
Currently, Maestro only supports exporting test results in JUnit format. While this works fine, if we are running Maestro tests in CI platforms like Azure/Jenkins, and would like to send the results via email, it is becoming a challenge to convert JUnit results to HTML. If Maestro supports this natively, it would come in very handy.

**Describe the solution you'd like**
An option to export results in HTML like ```maestro test --format html myFolderWithTests/```

**Describe alternatives you've considered**
Tried a few plugins available in Jenkins and Azure, but it was neither easy to convert JUnit to HTML nor attach JUnit results to an email.

**Additional context**
None.

**Comment by bartekpacia** [comment]
done in #1750
