### ISSUE TITLE
Maestro cloud config files breaks in monorepo

### ISSUE THREAD

**Issue by raulriera** [mobile-dev-inc/maestro#1074]
**Describe the bug**
There doesn't appear to be a way to use wildcards in a monorepo, using this configuration will fail with `Upload request failed (400): Workspace doesn't have any flow`

```yaml
baselineBranch: develop
flows:
  - "*/*"
excludeTags:
  - skip
  - util
```

I was able to replicate the same error above if I exclude all the flows with tags. So maybe that error is a bug in that logic instead of the upload one

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Configure maestro on a monorepo app
2. Run `maestro cloud ...` in the monorepo 
3. The console fails saying there are no flows

**Expected behavior**
It should upload the flows and a console url be displayed in the console

**Screenshots**

**Comment by raulriera** [comment]
It seems there are conflicting docs, the blog post about configuring maestro mentioned `*/*` is the wild card, but the [current docs](https://maestro.mobile.dev/cli/test-suites-and-reports) mention `**` instead

**Comment by igorsmotto** [comment]
Hey @raulriera, thanks for reporting this. It's a bit hard to explain, but I'll try it here.

Both `*/*` and `**` can work, it depends on what you exactly want and your folder structure. For example, take this folder structure:
```
.maestro
├── auth
│   ├── Login.yaml
│   ├── Onboarding.yaml
│   └── authsubflows
│       └── SignUp.yaml
├── checkout
│   ├── CheckoutWithCreditCard.yaml
│   ├── CheckoutWithGooglePay.yaml
│   └── CheckoutWithInvalidInfo.yaml
└──Settings.yaml
```

By using `**`, maestro will recursively select all flows from all folders. 
By using `*/*`, you will **not** select all flows (`SignUp.yaml` and `Settings.yaml` will not be sent), this is what the glob represents:: any file name (last star) within any folder (first star) - there is no recursive search here.

By using `*/**`, maestro will select all flows except `Settings.yaml`

**Comment by raulriera** [comment]
Thanks for the explanation, that makes sense now, that was my issue I was trying to select the root (Settings.yaml in this example) and a single folder and the wild cards were failing
