### ISSUE TITLE
[Biometrics Authentication] Testing features with biometrics

### ISSUE THREAD

**Issue by NandoMB** [mobile-dev-inc/maestro#1075]
I'm using [Expo Local Authentication](https://docs.expo.dev/versions/latest/sdk/local-authentication/) and I already tried to use maestro to authenticate, but without success...

So, today you have no support to do this. Do you have any plans to support Biometrics Authentication?

Thank you all!

PS: And hey, I forgot to say: "Awesome library"!

**Comment by axelniklasson** [comment]
Thanks for the suggestion @NandoMB!

Related to #282

**Comment by NandoMB** [comment]
Awesome @axelniklasson, I'll wait for it! 😄 

Thanks for your attention!
