### ISSUE TITLE
[Feature Request] Upload/Read File Feature

### ISSUE THREAD

**Issue by numanhan** [mobile-dev-inc/maestro#1077]
**Is your feature request related to a problem? Please describe.**
In my test flow there is one step which user takes photo and upload it for verify process. So with functionality I want to read jpg/jpeg/png file from local/cloud environment and upload it to app. So in this way I can manipulate data without taking a picture and verify the process.

**Describe the solution you'd like**
I'd love to use function like read file functions like other frameworks/languages.

**Describe alternatives you've considered**
  try {
            FileReader reader = new FileReader("myPicture.png");
            int character;
            while ((character = reader.read()) != -1) {
                System.out.print((char) character);
            }
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

**Additional context**
https://www.guru99.com/all-about-excel-in-selenium-poi-jxl.html

**Comment by amanjeetsingh150** [comment]
Hey @numanhan this feature is available in the latest release of 1.33.0

https://maestro.mobile.dev/api-reference/commands/addmedia
