### ISSUE TITLE
Command to stop the app

### ISSUE THREAD

**Issue by dmitry-zaitsev** [mobile-dev-inc/maestro#108]
Something like:

```
- stopApp
- stopApp:
     appId: {package name or bundle id}
```

**Comment by dmitry-zaitsev** [comment]
Added in 1.7.1

**Comment by pauloaapereira** [comment]
> Added in 1.7.1

Sorry to re-open this @dmitry-zaitsev;
FYI, I don't seem to find this command on the documentation, not sure if it was on purpose or not!
