### ISSUE TITLE
v1.27.0 - an stacktrace is shown if idb_companion is not installed

### ISSUE THREAD

**Issue by dmitry-zaitsev** [mobile-dev-inc/maestro#1080]
**Describe the bug**

When running Maestro on iOS without having idb_companion installed it spews out a stack trace instead of guiding user to necessary steps (i.e. installing idb_companion)

<img width="692" alt="image" src="https://github.com/mobile-dev-inc/maestro/assets/2990722/a4002de7-3c2c-4dfc-9467-33f18eb2fb59">

**Comment by amanjeetsingh150** [comment]
Hey @dmitry-zaitsev we wouldn't need IDB with latest release in v1.31.0. maestro is now decoupled with idb 🎉
