### ISSUE TITLE
[Feature Request] Upgrade Javascript Rhino Engine to something more recent 

### ISSUE THREAD

**Issue by bernardotwistag** [mobile-dev-inc/maestro#1081]
**Is your feature request related to a problem? Please describe.**
Yes, the problem arises when there is a need to execute more complex external JavaScript, such as tasks that involve reading an email inbox to retrieve a verification code, resetting URLs, or other related tasks. These tasks are necessary to ensure E2E testing flows operate as expected for our end-users. Currently, the 'runScript' function that uses the Rhino JavaScript engine is inadequate, as its limited capabilities do not fully support these tasks.

**Describe the solution you'd like**
To resolve this issue, we propose the incorporation of a more recent and robust JavaScript engine supporting ES6. This engine should be capable of handling complex tasks and offer a wider range of capabilities, surpassing the limitations encountered with the Rhino JavaScript engine. In essence, the new engine should be able to better support the execution of intricate JavaScript required for our E2E testing.

**Describe alternatives you've considered**
No alternatives found yet.

**Additional context**
The implementation of a more sophisticated JavaScript engine is crucial to enhance the efficiency and effectiveness of our E2E testing processes. Not only will it simplify the execution of complex tasks, but it will also ensure a better user experience by more reliably verifying that all systems are functioning as intended.

**Comment by orbiteleven** [comment]
Did you check out https://maestro.mobile.dev/advanced/javascript/make-http-s-requests ? I had the same question, but this seems to do the trick for me.

**Comment by bsarmento** [comment]
I haven't, but I will take a look if it meets my needs -- thanks!

**Comment by bartekpacia** [comment]
Does [GraalJS](https://maestro.mobile.dev/advanced/javascript/graaljs-support) fulfill your needs?
