### ISSUE TITLE
[1.2.7] launcApp fail on AWS mac m1 runner

### ISSUE THREAD

**Issue by davydspotnana** [mobile-dev-inc/maestro#1085]
**Describe the bug**

I tried to setup e2e pipeline on AWS m1 mac `mac2.metal` , but I stuck on such simple sign as lauckApp, (app was installed, see video) and check a bugreport zip (I also added simulator logs) for more Info

**To Reproduce**

```
maestro download-samples

cd ./samples
unzip sample.zip
xcrun simctl install Booted Wikipedia.app
maestro test ios-flow.yaml

Running on test3 - iOS 16.4 - 28F50966-5B20-49DB-8191-E23F25BD0F1A
Waiting for idb service to start..
Waiting for Simulator to boot..
Waiting for successful taps
Simulator ready


Running on test3 - iOS 16.4 - 28F50966-5B20-49DB-8191-E23F25BD0F1A      
                                                                        
 ║                                                                      
 ║  > Flow                                                              
 ║                                                                      
 ║    ❌  Launch app "org.wikimedia.wikipedia"                          
 ║                                            
```

**Expected behavior**

test run: success

**Screenshots**

https://github.com/mobile-dev-inc/maestro/assets/95620376/5c016130-186c-4b83-8fce-9bd4003274b6

**Environment information (please complete the following information):**

- Maestro version 1.2.7
- Platform: iOS 16.4
- Framework: Sample App, React Native
- Device model and OS version: iPhone 14
- Simulator - yes
- Host Mac M1

**Workspace (if applicable)**

...

**Bugreport output (if applicable)**

[maestro-logs.zip](https://github.com/mobile-dev-inc/maestro/files/11507725/maestro-logs.zip)

**Additional context**

...

**Comment by davydspotnana** [comment]
I used [xcodes](https://github.com/XcodesOrg/xcodes) to install Xcode and that was the reason 

```tsx
xcodes install --latest --experimental-unxip
```

when I installed xcode using App Store issue is gone

**Comment by mskhan18** [comment]
@ghost
 can you share some details or documentation regarding aws pipeline setup?
