### ISSUE TITLE
[Feature Request] Support double-tap action

### ISSUE THREAD

**Issue by xuanmd** [mobile-dev-inc/maestro#1090]
**Is your feature request related to a problem? Please describe.**
Currently, we don't support double-tab action. It would be helpful in some cases (ex: double-tap to like,..)
**Describe the solution you'd like**
Solution 1: support a new command `doubleTapOn`
Solution 2: add more customization on the `tapOn` command. Ex: `count: 2`, `threshold: 200` (ms),..
**Describe alternatives you've considered**
I prefer the solution 2

**Additional context**
It is same as the `touchPerform` in WebDriver

http://v4.webdriver.io/api/mobile/touchPerform.html

**Comment by ArthurSav** [comment]
Great suggestion from this [discussion](https://github.com/mobile-dev-inc/maestro/discussions/674) to also support mulltiple quick taps.

**Comment by ArthurSav** [comment]
Thank you for the suggestion, this has been implemented here https://github.com/mobile-dev-inc/maestro/pull/1149
