### ISSUE TITLE
Is CI integration via Github Actions possible?

### ISSUE THREAD

**Issue by johnnywang** [mobile-dev-inc/maestro#110]
A couple questions since the documentation for running on CI is a bit sparse: https://maestro.mobile.dev/getting-started/running-flows-on-ci

- I assume there's a bunch of setup that's necessary in order to make sure you can get the iOS sim and Android emu working on whatever your CI platform is first, right? Is it similar to the basic setup that Detox recommends going through?
- Would it be possible to run Maestro tests if our CI flow is set up to run via Github Actions?

**Comment by dmitry-zaitsev** [comment]
Sorry that it took a while to answer this question. We have introduced a SaaS product that allows to do that easily:

- Documentation: https://docs.mobile.dev/
- Signup: https://console.mobile.dev/signup
