### ISSUE TITLE
[Feature Request] Any chance Maestro can get Web Apps / Web API automation support?

### ISSUE THREAD

**Issue by muhamad-rizki** [mobile-dev-inc/maestro#1101]
**Is your feature request related to a problem? Please describe.**
I need AIO automation testing tools like Katalon for Mobile Apps, Web Apps, and Web API

**Describe the solution you'd like**
It would be great if Maestro can support automation for Web Apps / Web API e2e testing for AIO automation testing solution like Katalon

**Describe alternatives you've considered**
For now Katalon is the best match that has Mobile Apps, Web Apps, and Web API automation testing tools

**Additional context**
I'd be gladly happy for helping to make it happen in case if it has on Maestro roadmap

**Comment by axelniklasson** [comment]
Hi there @muhamad-rizki! We have experimental Web Support ([docs here](https://maestro.mobile.dev/advanced/experimental/maestro-webdriver)) that you can try out. Let us know what you think!
