### ISSUE TITLE
[Feature Request]Hello, may I ask if automated testing on the web side will be supported in the future

### ISSUE THREAD

**Issue by cfy3133** [mobile-dev-inc/maestro#1103]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by axelniklasson** [comment]
Hi there @cfy3133! We have experimental Web Support ([docs here](https://maestro.mobile.dev/advanced/experimental/maestro-webdriver)) that you can try out. Let us know what you think!
