### ISSUE TITLE
launch app returns “Unable to launch app com.android.settings: UNAVAILABLE: io exception”

### ISSUE THREAD

**Issue by Linda415** [mobile-dev-inc/maestro#1104]
[2023-05-25_191935.zip](https://github.com/mobile-dev-inc/maestro/files/11564183/2023-05-25_191935.zip)

**Comment by felipevolpone** [comment]
@Linda415 we need more information on this.
Was the app installed on the simulator before running the maestro command? Is the app native? If so, which platform? Which simulator have you used? If it's Android, what API level?

**Comment by Dambakk** [comment]
I regularly encounter this as well. Running locally on emulator, target API 33, app already installed and working as normal. I'm just tapping "up" in the terminal to rerun a flow, and then it suddenly throws the mentioned exception. The issue persist even after restarting the emulator and uninstalling and reinstalling the app. I even booted up another emulator and the error is still there. Suddenly, it decides to work again 🤷

**Comment by PictoMki** [comment]
I encountered the above error when running the binary created with Flutter.

I tried both with API level 30 and 32, but both throw the same error as above.

Simulator uses two points in the image

Just in case, the log that was spit out is output.
app_id is replaced with sample.app

[maestro.log.zip](https://github.com/mobile-dev-inc/maestro/files/11924827/maestro.log.zip)

<img width="464" alt="image" src="https://github.com/mobile-dev-inc/maestro/assets/56622027/e95b88c4-b624-4856-922e-9fab1aee7fd7">

**Comment by BrandonKandC** [comment]
I got this error when running the same test flow that was working last week

`[Failed] login-flow (4s) (Unable to launch app app.test: UNAVAILABLE: io exception)`

I'm working with an Android device (a real one), it was working last week, but not now.

**Comment by PictoMki** [comment]
I found a workaround here.

When I ran maestro test ~flow.yaml with the app I wanted to test open on an Android emulator, I was able to successfully test it without the above error.

**Comment by amanjeetsingh150** [comment]
Hey folks, can you try to check if devices were reachable with adb. Its an IOException it seems like the device might not be reachable.

**Comment by rahimrahman** [comment]
> Tip: Maestro Studio can now run simultaneously alongside other Maestro CLI commands!

And that exactly what happened to me.  I had `maestro studio` connected on my iOS simulator on a different terminal window and used a different terminal to run `maestro test` commands.  Then I switched to do some testing on Android device, so I quit my iOS simulator, ran `maestro test something.flow` with Android device connected and it would give me this error.  

Shutting down the `maestro studio` session on the other terminal solved my problem.

**Comment by chiefchief** [comment]
> > Tip: Maestro Studio can now run simultaneously alongside other Maestro CLI commands!
> 
> And that exactly what happened to me. I had `maestro studio` connected on my iOS simulator on a different terminal window and used a different terminal to run `maestro test` commands. Then I switched to do some testing on Android device, so I quit my iOS simulator, ran `maestro test something.flow` with Android device connected and it would give me this error.
> 
> Shutting down the `maestro studio` session on the other terminal solved my problem.

thank you

**Comment by bartekpacia** [comment]
Hey, does this issue occur anymore? From v1.30.1, it should be possible to run `maestro studio` and `maestro test` simultaneously.

There are no recent reports and the 👍 count is low as well, so maybe it doesn't occur anymore.
