### ISSUE TITLE
[Maestro Cloud v1.3.1] Android Snackbar test failing

### ISSUE THREAD

**Issue by joshliebe** [mobile-dev-inc/maestro#1107]
**Describe the bug**
One of our tests on Android has started to fail where Maestro Cloud doesn’t seem to click on a Snackbar action in time (It looks like it started failing on May 2).

The test passes when the duration of the Snackbar is set to `Snackbar.LENGTH_INDEFINITE`, it fails when it’s set to `Snackbar.LENGTH_LONG`.

**To Reproduce**
This is the test that was failing (I have since commented out the failing steps): https://github.com/duckduckgo/Android/blob/develop/.maestro/release_tests/3_-_favorites.yaml

The highlighted steps in this test are failing when the duration of the Snackbar is set to `Snackbar.LENGTH_LONG`:
<img width="480" alt="Screenshot 2023-05-25 at 16 15 38" src="https://github.com/mobile-dev-inc/maestro/assets/3471025/ec2e98df-4b09-45ff-b0a5-cc3cc0412b5c">
<img width="580" alt="Screenshot 2023-05-19 at 13 42 37" src="https://github.com/mobile-dev-inc/maestro/assets/3471025/1e3c5357-a03c-44ac-99d1-9106cf183d31">

When the duration is set to `Snackbar.LENGTH_INDEFINITE` it passes:
<img width="569" alt="Screenshot 2023-05-19 at 20 47 45" src="https://github.com/mobile-dev-inc/maestro/assets/3471025/387ece4c-ced6-4db7-8baa-b6cb3e4d43de">

This test is being run with this GH action: https://github.com/duckduckgo/Android/blob/develop/.github/workflows/end-to-end.yml

**Expected behavior**
The test should pass with any Snackbar duration.

**Screenshots**
When set the duration is set to `Snackbar.LENGTH_LONG`, the undo action is not performed (The deleted favorite does not reappear):

https://github.com/mobile-dev-inc/maestro/assets/3471025/3078ab13-77b1-4539-b530-e5b528bac099

When set the duration is set to `Snackbar.LENGTH_INDEFINITE`, the undo action is performed (The deleted favorite reappears):

https://github.com/mobile-dev-inc/maestro/assets/3471025/7c6aeb96-0bfc-4eed-841e-68cec9914b2e

**Environment information (please complete the following information):**

- Maestro Cloud version: v1.3.1
- Platform: Android 11
- Framework: Native Android
- Device model and OS version: Cloud
- Simulator, emulator or physical device: Cloud
- Host [e.g. Mac M1, Windows, Linux, etc]: Cloud

**Workspace (if applicable)**
Binary: https://github.com/duckduckgo/Android/releases/tag/5.159.0
Workspace: [workspace.zip](https://github.com/mobile-dev-inc/maestro/files/11566690/workspace.zip)

**Bugreport output (if applicable)**
n/a

**Additional context**
n/a

**Comment by axelniklasson** [comment]
Hi there @joshliebe - thanks for the detailed report, much appreciated! 

I believe this is due to the three assertions being done after tapping on the `Delete` button, before trying to tap `Undo`. maestro has a lot of logic to ensure that the screen changes have been finished and the view hierarchy is settled that is being invoked between commands, so I would recommend you to update your Flow to not do these assertions before the tapping on `Undo` as there is simply not enough time for maestro to do all this in the short timespan the snackbar is available.

Could you try to remove the following lines between the undo and delete taps from your Flow and try again?

```yaml
# When a favorite is removed, it still stays as Bookmark
- assertVisible:
    text: "No favorites added yet"
- assertNotVisible:
    text: "No bookmarks added yet"
# Undo remove favorite from bookmarks screen
- assertVisible: "Undo"
```

**Comment by joshliebe** [comment]
Hey @axelniklasson, your suggestion worked! I split the test up into 3 separate ones and everything is passing now.
Thanks so much 🙂
