### ISSUE TITLE
[v1.2.8] io.grpc.internal.AbstractClientStream$TransportState inboundDataReceived

### ISSUE THREAD

**Issue by Angelk90** [mobile-dev-inc/maestro#1114]
**Describe the bug**
I tried running on an old device, Samsung Galaxy Tab A (2016) I don't see anything in the preview.

I set the usb as `file transfer`.

**Screenshots**
<img width="702" alt="Screenshot 2023-05-29 alle 17 39 38" src="https://github.com/mobile-dev-inc/maestro/assets/20476002/3a683b3a-b3a2-454a-a976-66c012b788a3">

<img width="441" alt="Screenshot 2023-05-29 alle 17 46 06" src="https://github.com/mobile-dev-inc/maestro/assets/20476002/74f178e0-9efb-4996-9af4-e8f4ad2f0d76">

**Environment information (please complete the following information):**

Maestro version: 1.28.0
OS: Mac OS X
OS version: 13.2.1
Architecture: x86_64

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue - unfortunately, it's not easily reproducible. We have a huge backlog, so it's important we can triage issues in an efficient manner.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
