### ISSUE TITLE
[Feature Request] Maestro Cloud: Download report

### ISSUE THREAD

**Issue by Dambakk** [mobile-dev-inc/maestro#1128]
If I accidentally close my terminal after launching a maestro cloud run, or if the terminal looses connection to maestro (and I get the following error message: Upload did not complete in time due to an issue on mobile.dev side. Follow the results of your upload below), then it would be convenient to be able to download the report from the web interface when the run is complete.

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue! Unfortunately, it's not reproducible to us.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

This issue does not contain such an example, therefore I'm going to reluctantly close it.

If you don't have time right now, that's totally OK. Feel free to open a new issue in the future with all the required information provided.

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
