### ISSUE TITLE
[Feature Request] : Are you working on integrating the test runs on cloud device providers like Sauce Labs , Browser Stack.

### ISSUE THREAD

**Issue by BharathSaraswathi** [mobile-dev-inc/maestro#1129]
As an automation engineers, we would always run automation scripts on real devices. 
So it would be easy if you can provide us a way to integrate our scripts with cloud testing providers like Sauce Labs, and Browser Stack, at least for Android as iOS is still in the development stage to run on real devices.

**Comment by micheltonon** [comment]
Hello, following @BharathSaraswathi's question, is there the possibility of expanding the service for testing on multiple real devices

**Comment by bartekpacia** [comment]
Support for running on multiple device in parallel was contributed in #1732 and will be released in the next stable version.

Currently we don't have plans to add explicit support 3rd party testing platforms. As long as you can run an emulator and have shell access, you can run Maestro yourself.

Could you clarify the request exactly here?

PS Before you ask for support of a fully-managed service like Firebase Test Lab - it's not possible with Maestro's architecture (heavy usage of `adb` and `xcrun simctl`, which is not possible on Firebase Test Lab and similar).
