### ISSUE TITLE
[Maestro version v1.27] maestro test stops when a custom toast appears 

### ISSUE THREAD

**Issue by cenci7** [mobile-dev-inc/maestro#1132]
**Describe the bug**
The `maestro test` process ends when a custom toast appears in the app.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Start the simulator
2. Run `maestro test ...`
3. The Flow fails when a custom toast is shown

**Expected behavior**
Keep running the `maestro test`.

**Screenshots**

**Environment information (please complete the following information):**

- Maestro version v1.27
- Platform: Android
- Framework: Native Android
- Device model and OS version: -
- Simulator, emulator or physical device: tested on emulator, I didn't try it on a physical device
- Host: Mac M1

**Bugreport output (if applicable)**
![image](https://github.com/mobile-dev-inc/maestro/assets/17922386/b2b0a96b-1863-4ac0-801f-b30d8d37d305)

**Additional context**
[Slack message](https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1684223082675439).

**Comment by cenci7** [comment]
[CustomToast.zip](https://github.com/mobile-dev-inc/maestro/files/11687341/CustomToast.zip)

There's a test `maestro_toast_test.yaml` in the root folder.

Thanks!

**Comment by TaimoorWaseemKhan93** [comment]
@cenci7 have you tried to run on Maestro 1.28.0 ?

**Comment by TaimoorWaseemKhan93** [comment]
![Screenshot from 2023-06-08 19-18-18](https://github.co@cenci7 /mobile-dev-inc/maestro/assets/114213754/ba9e89bb-754a-4713-b076-47655afd7cff)
@cenci7 i have executed the issue on both the versions of maestro 1.27 and 1.28. Its working fine.

**Comment by amanjeetsingh150** [comment]
Hey @cenci7 can you try on 1.28.0 and let me know if it works? If it still fails can you help with following:

1. Do `adb logcat -c`
2. Run maestro test which fails
3. Do `adb logcat -d > output_logs.txt`
4. Attach this `output_logs.txt` here.

**Comment by cenci7** [comment]
I tested it again with version 1.27 and 1.28 and everything seems to be working fine.
Also tried it with MacOS Ventura and Monterrey and everything ok.

I don't know what caused it, but seems it's not happening anymore 👌 
I close the issue.

Thanks anyway por the research!!
