### ISSUE TITLE
`test` throws `adb` exception

### ISSUE THREAD

**Issue by theapache64** [mobile-dev-inc/maestro#1133]
**Problem**
![image](https://github.com/mobile-dev-inc/maestro/assets/9678279/2ed06478-cacc-4792-8dd5-feda2252d0f5)

**Logs**
[2023-06-06_224534.zip](https://github.com/mobile-dev-inc/maestro/files/11667422/2023-06-06_224534.zip)
[2023-06-06_224546.zip](https://github.com/mobile-dev-inc/maestro/files/11667423/2023-06-06_224546.zip)

**Comment by amanjeetsingh150** [comment]
Hey, @theapache64 are you trying on a physical device? 

Can you give following information:

1. Environment information:
- Maestro version 
- Device model and OS version: [e.g. Pixel 2 API level 30]
- Simulator, emulator or physical device
- Host [e.g. Mac M1, Windows, Linux, etc]
2. Since this is IOException seems like your emulator/device was not reachable can you check with `adb devices` command.

**Comment by theapache64** [comment]
@amanjeetsingh150 

**Version**
![image](https://github.com/mobile-dev-inc/maestro/assets/9678279/9ee4361b-5aca-440c-9b47-35d6addd5546)

**Device**

Physical Device, Redmi A1 (Android 12 Go edition)

**Host**

![image](https://github.com/mobile-dev-inc/maestro/assets/9678279/7c4ec50b-79c2-4e87-983f-af613da7e731)

**Comment by theapache64** [comment]
I've also tried with a `Pixel 4a - Android 11`. Same result

**Comment by amanjeetsingh150** [comment]
Hey @theapache64, Can you help me send output of this command:

`adb shell pm list packages --user 0 dev.mobile.maestro.test`

**Comment by theapache64** [comment]
@amanjeetsingh150 

It returns nothing

![image](https://github.com/mobile-dev-inc/maestro/assets/9678279/2207b32c-e1ed-4ade-b647-1c44e9dbce53)

**Video**


https://github.com/mobile-dev-inc/maestro/assets/9678279/6e0b5d33-7f0a-47bd-b8b5-aa7bddcf9ff1

**Comment by theapache64** [comment]
@amanjeetsingh150 Any updates on this? :)

**Comment by amanjeetsingh150** [comment]
Hey, @theapache64 we will pick this up soon and keep you updated here. Meanwhile can you try some other android version or testing in emulator to see if it works

**Comment by felipevolpone** [comment]
Real devices aren't fully supported by Maestro yet.
