### ISSUE TITLE
Add a "maestro doctor" command line which does basic checks if the app is ready to run

### ISSUE THREAD

**Issue by SuperRoach** [mobile-dev-inc/maestro#1136]
**Is your feature request related to a problem? Please describe.**
I'm looking at helping onboard new users.

**Describe the solution you'd like**
A new command line option for maestro, called doctor. `maestro doctor` would run, and check for the things needed to run the app. 

By doing this, you have more room on the command line to tell them what the user should do. I'm going  to list the macOS ways of doing things, but you could also link to websites to get the user in the right direction. 

Overall though, a set of checkmarks would fit right in with how a normal maestro test would look anyway - however the test is in some ways, on your own computer.

**Describe alternatives you've considered**
It would show the current version of Maestro, as well as the command line for upgrading it if needed. You could in theory check if there is a newer version available and let the user know that, but that's making things a bit too complex too quickly.

It would check:
- Is ADB accessible? (if not, suggest installing it, and adding it to your path) - I'm focused on Android testing fwiw.
- Is there something returned when `adb devices` happens? to know that a device/emulator is ready to start
- Is Java installed? (suggest `brew install java`, or link to openjdk)
- (macOS) Is xcode command line tools installed? ( the folder will print if `xcode-select -p 1>/dev/null;echo $?` works)

In slack, I also mentioned a check for `which scrcpy`, which is a fantastic companion app with this but honestly is not worth including in the doctor output.

**Additional context**
https://docs.flutter.dev/get-started/install/windows#run-flutter-doctor
![image](https://github.com/mobile-dev-inc/maestro/assets/63333/29fcface-ef09-4fd5-b3a3-50dec691b299)
Here is a sample of what `flutter doctor` looks like. 
Their implementation is a good part of what makes setting it up more hassle free compared to say React native.

Possible web links if wanting to go down that route:
Android SDK: https://developer.android.com/studio/index.html
If you want it to be apple specific, the command to do this is `brew install android-platform-tools` - if they have brew.

To install java:
Official OpenJDK link (short but may be confusing): https://openjdk.org/install/
MultiOS: https://www.freecodecamp.org/news/install-openjdk-free-java-multi-os-guide/ (better but unofficial)

**Comment by bartekpacia** [comment]
This is a great issue, thanks a ton!

I unknowingly duplicated it with #1785 though.
