### ISSUE TITLE
[Feature Request] Introduce Execution Order for Local runs as well as Cloud

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#1139]
https://cloud.mobile.dev/reference/execution-order

Execution order has been introduced for Cloud and looks like a great idea when you want to force flows in a certain order.

For Local execution, we currently only have `deterministicOrder: true` which does help allow us to define an order, but leaves it constrained in to having to either number or alphabetise flows, e.g:

> 1_login.yaml
> 2_home.yaml

**Comment by axelniklasson** [comment]
Closing this out as this has been shipped: https://maestro.mobile.dev/cli/test-suites-and-reports#sequential-execution
