### ISSUE TITLE
Slack channel

### ISSUE THREAD

**Issue by Angelk90** [mobile-dev-inc/maestro#1157]
Hi @axelniklasson , @ArthurSav : 

I tried to join the slack channel, when logging in with email I am asked for an email with domain: `@fetchrewards.com`

But I don't have an email with the following domain, it tells me:

Don't have an @fetchrewards.com email address?
Contact your mobile.dev workspace administrator to request an invite.

**Comment by axelniklasson** [comment]
@Angelk90 could you send me an email to `axel@mobile.dev` and I'll help you out there? Thanks!
