### ISSUE TITLE
Maestro cloud - Flow ends up in a "canceled" status randomly

### ISSUE THREAD

**Issue by mjaworski-bsg** [mobile-dev-inc/maestro#1158]
Our flow is sometimes passing correctly and sometimes it get a "canceled" status. 

![image](https://github.com/mobile-dev-inc/maestro/assets/124886525/3c658247-0629-41d1-a903-24b4e7f7957e)

Flow does not exceed the limit runtime, it gets canceled at 1:28, but sometimes the same flow is passing fine (it takes ~2:30 for that flow to pass correctly)

We were unable to reproduce the issue locally, it happens only in the cloud.

Build link:
https://console.mobile.dev/uploads/bf2df847-e9ae-436a-9d78-55891475dd5e?teamId=2d47eb57-10f2-4b6f-b8d4-7d0c59e74bbe&appId=7468445e-8a12-4b4a-b578-380679425a01&analysisId=ec702868-6490-4bad-9721-cd940d3dce16

**Comment by berikv** [comment]
There was an issue with recording the screen. This issue caused the flow to be canceled.
I have implemented a fix that makes sure that a screen recording error does not cause the flow result to be changed. I was not able to resolve the screen recording issue, that will still be looked at.

**Comment by MarcoCalva** [comment]
Is the above issue fixed? We are also facing the same issue of flows getting canceled randomly. 
Could you check and advise on this? 

Console Link: https://console.mobile.dev/uploads?teamId=819d997f-c091-4dbf-bd90-eafe488b25ed&appId=33b6bbc1-2b16-4226-964e-0c47ec2eb3ec
