### ISSUE TITLE
1.28.0 - maestro-driver-ios using huge amount of storage space in DerivedData

### ISSUE THREAD

**Issue by sidster-io** [mobile-dev-inc/maestro#1166]
**Describe the bug**
Currently in /Library/Developer/Xcode/DerivedData/* I see maestro using a lot of storage

**To Reproduce**
Keep running multiple tests on maestro
Then use the following command  `du -sh $HOME/Library/Developer/Xcode/DerivedData/* | sort -rh` to list out what is in DerivedData

**Screenshots**
<img width="837" alt="Screenshot 2023-06-16 at 4 57 44 PM" src="https://github.com/mobile-dev-inc/maestro/assets/6657673/46b5151f-7f64-4972-acaf-6e499002a6c1">

**Environment information (please complete the following information):**

- Maestro version 1.28.0
- Platform: iOS
- Host: macOS 13.4 on Xcode 14.3.1

**Comment by berikv** [comment]
Hi @sidster-io, I've updated maestro to save these maestro-driver-ios-* directories in the OS temp dir (`/var/folders/.../.../...`) which should be automatically cleaned by the OS.
This change will be part of the next maestro release (scheduled this week).
To remove any already existing logs, one can use `rm -rf ~/Library/Developer/Xcode/DerivedData/maestro-driver-ios-*`.

**Comment by berikv** [comment]
Hi @sidster-io I believe this issue has been fixed.
Let me know if you still find that this issue is still happening.
