### ISSUE TITLE
[Feature Request] Physical on/off button

### ISSUE THREAD

**Issue by Angelk90** [mobile-dev-inc/maestro#1167]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the ability to support the physical on/off button.

**Comment by berikv** [comment]
I think you then need the “Lock” pressKey command. Or am I missing something?

**Comment by depapp** [comment]
hi @berikv 
I've tried the `- pressKey: lock` command, only works for lock the screen. didn't works for unlock the screen.
here's the screen recording

https://github.com/mobile-dev-inc/maestro/assets/6134774/3f485ffa-deee-49d7-be50-4bf7a06b40bc

**Comment by depapp** [comment]
> @berikv : I don't freeze, the screen gets a little dark but it doesn't freeze.
> 
> Have you tried the command?

hi @Angelk90 
can you run this PR locally on your side? just curious is it works as expected or not

**Comment by berikv** [comment]
Looking at  https://stackoverflow.com/a/57778537/439096
and https://medium.com/@tjaddams/how-to-enable-the-lock-screen-for-your-android-emulator-a7d5d4d5b404

It seems you can configure the android emulator to show the lock screen.

The following maestro script does this. However, when I test this, the screen stays black and none of the buttons brings the emulator os back. This is likely a bug in the android emulator.

```
appId: "foo.bar"
---
- swipe: { direction: UP }
- tapOn: Settings
- swipe: { direction: UP }
- tapOn: Security
- tapOn: Screen lock
- tapOn: Swipe
- pressKey: home
- pressKey: Lock
- pressKey: Lock
```

**Comment by depapp** [comment]
> @berikv : I tested your code on my physical device it doesn't work. I don't understand why the behavior of the emulator is different from that of a physical device. If you can try it on a physical device.
> 
> @depapp: I tested your pr code locally on my physical device it seems to work, no problem.

that's great @Angelk90 

@berikv since this works on @Angelk90 case, how if I change the keycode for `-pressKey: lock` to `26` instead of `276`.
so I don't need to add new command `-pressKey: power`
