### ISSUE TITLE
hierarchy CLI command only showing "text" and "bounds" attributes?

### ISSUE THREAD

**Issue by neonfink** [mobile-dev-inc/maestro#117]
The `hierarchy` command seems like such a great improvement compared to endless nesting you have to scroll through in Appium's inspector tree view! However, it seems to only return `text` and `bounds` attributes for the found views at the moment but not the `id`, for instance. 
Are more attributes output support is planned in future? Thanks!

**Comment by dmitry-zaitsev** [comment]
Maestro does surface a `resource-id` field whenever it is available. Could you give an example of an application where you expected to have this field but it was not present?

**Comment by neonfink** [comment]
Ah, thanks for clarifying! I was expecting to see a null value if `resource-id` is missing, similar to what I observed for `"clickable" : null`.
It could be that our app is in fact missing `resource-id` and only has accessibility ID provided, I would have to double check that to be sure it's not an issue on our side.   

As a follow-up question if I may: do I understand correctly that it's expected to see accessibility IDs propagated as `text` field in the hierarchy tree?

**Comment by dmitry-zaitsev** [comment]
> I was expecting to see a null value

Fair point, we'll address it.

> As a follow-up question if I may: do I understand correctly that it's expected to see accessibility IDs propagated as text field in the hierarchy tree?

Actually, accessibility ids should still appear as `resource-id`. What platform are we talking about here? Android or iOS?

**Comment by neonfink** [comment]
> Actually, accessibility ids should still appear as resource-id. What platform are we talking about here? Android or iOS?
sorry for not specifying before, I tested it on iOS

**Comment by dmitry-zaitsev** [comment]
I see, thanks for clarifying. Could you please:

- Validate whether you indeed do not see `resource-id` for views that have an accessibility identifier set.
- If that is indeed the case, could you share a code snippet on how you set the accessibility id so that I can try to reproduce it?

**Comment by neonfink** [comment]
Need to set some time aside with some of our developers to validate it, will try to get back this this thread with more valuable info when I have any 👌

**Comment by dmitry-zaitsev** [comment]
Closing until more context is available
