### ISSUE TITLE
[v1.29.0] Responsive Maestro Studio

### ISSUE THREAD

**Issue by Angelk90** [mobile-dev-inc/maestro#1173]
**Describe the bug**

As you can see from the video when you minimize the window, it is no longer responsive, it happens with all tested browsers which are: Chrome, Firefox, Safari.

Chrome:

https://github.com/mobile-dev-inc/maestro/assets/20476002/fe32879e-62c9-4f73-85d4-a207de11121e

<img width="526" alt="Screenshot 2023-06-19 alle 18 10 46" src="https://github.com/mobile-dev-inc/maestro/assets/20476002/28609147-aae5-4982-9cd5-5cca011a0cec">

Firefox:

<img width="488" alt="Screenshot 2023-06-19 alle 18 06 56" src="https://github.com/mobile-dev-inc/maestro/assets/20476002/2d29f1c1-9ba5-4ebd-90f9-886a5c5aafb8">

Safari:

<img width="620" alt="Screenshot 2023-06-19 alle 18 08 00" src="https://github.com/mobile-dev-inc/maestro/assets/20476002/1bcfabb5-58a1-40f8-bc68-844c22aea6a8">

**To Reproduce**

1) Minimize your window browser

**Environment information (please complete the following information):**

- Maestro version 1.29.0
- Platform: Chrome, Firefox, Safari

**Comment by bartekpacia** [comment]
Hey, it'll be hard to provide a good responsive experience, and we don't have any plans for that.

a bit reluctantly I consider this working as intended.
