### ISSUE TITLE
SHA-256 Mismatch while installing through homebrew on M1

### ISSUE THREAD

**Issue by DroidNinja** [mobile-dev-inc/maestro#118]
**Problem:**
When I am installing `maestro` through homebrew, it is giving SHA-256 checksum mismatch issue. Although It is working fine on my intel mac machine.

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/889201/188315731-3d818903-d4d6-44a6-b44c-87b830604d88.png">

**Comment by dmitry-zaitsev** [comment]
Brought it up with the team members who have M1s, checking

**Comment by dmitry-zaitsev** [comment]
We were not able to reproduce the issue on 3 different M1 machines, so I have to assume that this is something related to your setup. Let's reopen it once we have more context
