### ISSUE TITLE
Command to clear keychain info for the app?

### ISSUE THREAD

**Issue by neonfink** [mobile-dev-inc/maestro#119]
In the iOS app that we're testing, user session data persists to the keychain, even after removing and re-installing the app. Due to this a `clearState` property does not seem to be sufficient to get a clean state of the app in a such a scenario, as the previously logged in user will stay logged in. 
In Appium we found a workaround for this being to force reset iOS Simulator itself when establishing session capabilities, as it is not capable of cleaning the keychain for a specific app (frankly, not sure that iOS even allows this technically). 

Is something like clearing keychain info or a clean simulator restart command possibly coming in future versions of Maestro?

**Comment by dmitry-zaitsev** [comment]
We use Facebook's IDB under the hood and it does seem to have an ability to clear the keychain (https://fbidb.io/docs/commands#clear-the-keychain), so this could be added 👍

**Comment by dmitry-zaitsev** [comment]
This is now a part of version 1.7.1
