### ISSUE TITLE
Text not found

### ISSUE THREAD

**Issue by dmitry-zaitsev** [mobile-dev-inc/maestro#120]
Recording:
https://youtu.be/smpECXx0B1Y?t=524

**Comment by migueldaipre** [comment]
I'm having same issue in React Native project

maestro hierarchy show input with text is clickable

<img width="482" alt="image" src="https://user-images.githubusercontent.com/21174859/188776257-0b1c8498-c006-41c2-ac9e-5d8a4d98f8fc.png">

But not working well

<img width="330" alt="image" src="https://user-images.githubusercontent.com/21174859/188776484-965e9e73-c4d9-4a5d-90a3-bf30bc67104c.png">

he looks at the children ?

**Comment by dmitry-zaitsev** [comment]
Closing until more context is available
