### ISSUE TITLE
port fowarding to maestro cloud

### ISSUE THREAD

**Issue by helloagain-dev** [mobile-dev-inc/maestro#1205]
**Is your feature request related to a problem? Please describe.**
i want to run maestro test on maestro cloud but the backend is not available over a public ip address or domain
i want to run wire-mock locally and my test in the cloud should be able to access it

**Describe the solution you'd like**
i want to run 
`maestro cloud ... port:8080`
and the app on the emulator/simulator should be available to access the local port from my machine where i started the maestro command

**Describe alternatives you've considered**
ngrock, any other tunneling service

**Comment by igorsmotto** [comment]
Hi @helloagain-dev! 

Other users of Maestro Cloud that had their backend blocked from the internet, usually behind a VPN, have successfully added Maestro Cloud IPs to their allow list - allowing Maestro Cloud to access it. More details here: https://cloud.mobile.dev/reference/ip-allowlist

Would this help you?

**Comment by helloagain-dev** [comment]
this would help for a restricted network?
what about the use case to have a local backend / mock server running? would you recommend to use tunnel service?

**Comment by bartekpacia** [comment]
We don't plan to support this for now. For now we advise to expose a staging/dev backend on the internet.
