### ISSUE TITLE
Test fails randomly on iOS when using hideKeyboard 

### ISSUE THREAD

**Issue by kassemitani** [mobile-dev-inc/maestro#1220]
Flaky tests when using `hideKeyboard` on iOS 

First it shows connection was leaked and then shows an error `Unable to obtain active app id`

> Jun 26, 2023 11:05:15 AM okhttp3.internal.platform.Platform log
> WARNING: A connection to http://localhost:22087/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
> Jun 26, 2023 11:05:15 AM okhttp3.internal.platform.Platform log
> WARNING: A connection to http://localhost:22087/ was leaked. Did you forget to cjava.lang.IllegalStateException: Unable to obtain active app id       logg    at ios.xctest.XCTestIOSDevice.contentDescriptor(XCTestIOSDevice.kt:57)l.    at ios.LocalIOSDevice.contentDescriptor(LocalIOSDevice.kt:35)
> 

We are using:  
- Xcode (14.2)
 - iOS 16.2
- Hardware: Mac mini M1
- React-Native app (release app, no metro) (no expo libraries)

Tests randomly fails after `hideKeyboard`: [ERROR] maestro.cli.runner.TestRunner - Failed to run flow
java.lang.IllegalStateException: Unable to obtain active app id

[Slack maestro thread](https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1687643412982529)

**Comment by amanjeetsingh150** [comment]
Hey @kassemitani can you try this on latest version of maestro v1.31.0 ? We have addressed some issues to scroll operation which is how hideKeyboard works on iOS

**Comment by kassemitani** [comment]
Thank you, now it is working fine.
