### ISSUE TITLE
IOS real device 

### ISSUE THREAD

**Issue by xasancyber-security** [mobile-dev-inc/maestro#1224]
**Bug description**

 Maestro can't see my real IOS device Iphone 13
 How to test flows in real devices?

Thanks,  
Xasan

Environment information:

Maestro version v1.29.0
Platform: iOS 16.5
Device model and OS version: iPhone
Simulator, emulator or physical device: Simulator
Host: Mac M1

**Comment by igorsmotto** [comment]
Hey @xasancyber-security,

Unfortunately, for iOS, Maestro still doesn't support real devices.

**Comment by xasancyber-security** [comment]
Hi Igor,
Nowadays I am using maestro in my project. I would love to have a chance to test it in real gadgets. Perhaps, it would be nice to have those features in the near future.  
Thanks, for feedback

**Comment by igorsmotto** [comment]
Thanks for your feedback! 
To be clear, we do want to have this feature as well, however, I can't make promises about when we will deliver this.

**Comment by lukepighetti** [comment]
@igorsmotto Hi there, I noticed this issue was closed as "completed." What's the current state of this feature request, and what is the future of it? Any chance to see Maestro working on physical iOS devices?
