### ISSUE TITLE
[Maestro Cloud] input text flaky in iOS

### ISSUE THREAD

**Issue by SaphiraNgocThuy** [mobile-dev-inc/maestro#1225]
**Describe the bug**
Flaky text input when running 
`- inputText: ${USERNAME}`

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Only happens on Maestro cloud
2. See video in screenshot section
4. The Flow fails at:
  - Tap on id: email-username-input
  - Then wait for animation to end.
  - Then Input text ${username} which input wrongly, (m**o**biletestfreeuser => mbiletestfreeuser**o**)

**Expected behavior**
Should input correctly mobiletestfreeuser

**Screenshots**
https://github.com/mobile-dev-inc/maestro/assets/41480474/6cd800ad-6758-4ed6-9def-76501f440825

**Environment information (please complete the following information):**

- Maestro Cloud @v1.2.3
- Platform: iOS
- Framework: React Native
- Device model and OS version: iPhone 14
- Simulator
- Host [e.g. Mac M1, Windows, Linux, etc]

**Comment by igorsmotto** [comment]
Hey @SaphiraNgocThuy, 
Sadly, inputText on iOS is still subpar to what we would like it to be, and we're hoping to fix that in the future.

However, one thing that we found out from our work was that inputText looks to be more stable on iOS 16. Therefore, could you try uploading this flow to run on iOS 16 to see if this flakiness is fixed?

`maestro cloud yourApp.app workspace --ios-version=16`
[Docs here](https://cloud.mobile.dev/reference/device-configuration)

--
Also, usually, you don't need to wait for the animation to end before inputting the text. But my guess is that you added this wait _because_ of the flakiness, am I right? If not, could you share the reason for it?

**Comment by SaphiraNgocThuy** [comment]
> Hey @SaphiraNgocThuy, Sadly, inputText on iOS is still subpar to what we would like it to be, and we're hoping to fix that in the future.
> 
> However, one thing that we found out from our work was that inputText looks to be more stable on iOS 16. Therefore, could you try uploading this flow to run on iOS 16 to see if this flakiness is fixed?
> 
> `maestro cloud yourApp.app workspace --ios-version=16` [Docs here](https://cloud.mobile.dev/reference/device-configuration)
> 
> -- Also, usually, you don't need to wait for the animation to end before inputting the text. But my guess is that you added this wait _because_ of the flakiness, am I right? If not, could you share the reason for it?

hi @igorsmotto yeah, seems changing the ios version and upgrading Maestro cloud to v1.4.1 fixed this, thank u
Yeah, I added the wait for animation to end before inputting text to fix this issue, now can remove thank uu 👯

**Comment by bartekpacia** [comment]
This issue is probably related (or the same) as #2005
