### ISSUE TITLE
Sroll and Swipe commands not working on RN app version 0.71.7

### ISSUE THREAD

**Issue by kavithamahesh** [mobile-dev-inc/maestro#1234]
Slack channel concersation link : https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1689073684767359

This is currently a blocker for us to run the tests on the pipeline.

**Comment by amanjeetsingh150** [comment]
Hey, @kavithamahesh can you provide more details:

1. A sample app/flow reproducing the issue
2. What exactly is happening when you say not working?
3. Can you share it separately for android / iOS

Also following environment information:

- Maestro version [e.g. v1.2.3]
- Platform: [e.g. iOS 16.4.1, Android 11.0, Chrome]
- Device model and OS version: [e.g. iPhone6]
- Simulator, emulator or physical device
- Host [e.g. Mac M1, Windows, Linux, etc]

**Comment by bartekpacia** [comment]
Closing because of lack of response. Please feel free to open a new issue with all the required info filled out.
