### ISSUE TITLE
[1.30.0 - Android Only]: assertVisible with ID Fails, react-native

### ISSUE THREAD

**Issue by foratbahrani** [mobile-dev-inc/maestro#1242]
**Describe the bug**
the following command works on iOS, but not android:
- assertVisible:
    id: "authentication.continueAsGuest"

**To Reproduce**
Steps to reproduce the behavior, e.g.:

react native code:
> 		<Text id="authentication.continueAsGuest" nativeID="authentication.continueAsGuest" testID="authentication.continueAsGuest" >
>			{content}
>		</Text>

maestro code:
> \- assertVisible:
>         id: "authentication.continueAsGuest"

output:
❌  Assert that id: authentication.continueAsGuest is visible 

**The exact same code works on iOS**

also tried with Views

react native code:
`<View testID='CheckBox 1' />`

maestro code:
> \- assertVisible:
>         id: "CheckBox 1"

output:
❌  Assert that id: CheckBox 1 is visible 

**Again, Only breaks on Android**

**Expected behavior**

**Screenshots**

**Environment information (please complete the following information):**

- Maestro version 1.30
- Platform: Android SDK 21
- Framework: React Native
- Device model and OS version: emulator (Pixel 4)
- Emulator
- Host macOS

**Workspace (if applicable)**
Please share your workspace with Flow files and application binary if you are able to do so as that greatly helps in reproduction efforts.

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

**Additional context**

**Comment by felipevolpone** [comment]
@foratbahrani Can you provide your app binary and your Flow? Without them, I don't think we'll be able to debug or work on this

**Comment by foratbahrani** [comment]
@felipevolpone it's open source

https://github.com/foratbahrani/healthyme

**Comment by felipevolpone** [comment]
@foratbahrani  Can you provide the binary? I don't to build it myself
