### ISSUE TITLE
[Feature Request] Ability to put the app to the background and bring it back from background

### ISSUE THREAD

**Issue by itsashis4u** [mobile-dev-inc/maestro#1261]
**Is your feature request related to a problem? Please describe.**
I'm trying to test a crash which happens when the app is in background. We have no clear reproduction steps for this, so I wanted to put the app to background after every navigation. 

**Describe the solution you'd like**
Ability to put the app to the background and go to the home screen and then open the app from the recent apps section

**Comment by timrijckaert** [comment]
Have you tried

```
- pressKey: home
```

As per [documentation](https://maestro.mobile.dev/api-reference/commands/presskey), I personally did not try it, but seems like this could do the trick

**Comment by itsashis4u** [comment]
Thanks. I will try this. If it works, I will close this

**Comment by markrickert** [comment]
> Have you tried
> 
> ```
> - pressKey: home
> - launchApp:
>     appId: "com.example.app"
>     clearState: false
> ```

This worked perfectly for my test's needs! Thank you!
