### ISSUE TITLE
[1.30.3] Crash on run flow "RESOURCE_EXHAUSTED: gRPC message exceeds maximum size"

### ISSUE THREAD

**Issue by ichlaufe** [mobile-dev-inc/maestro#1264]
**Describe the bug**
After updating to version 1.30.3 my script fails on executing the first flow in: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: gRPC message exceeds maximum size 4194304: 4223020

**To Reproduce**

1. Start the emulator
2. Run `maestro test ...`
3. The Flow fails at executing the first testrun, after taking a screenshot of the spash screen

**Expected behavior**
No crash. All testruns should be executed in the order that is defined in the main yml file. 

**Environment information:**

Maestro Version: 1.30.3
OS Name: Mac OS X
OS Version: 13.4.1
Architecture: x86_64
Android pixel 4 emulator - Android 8.1

**Additional context**
[maestro.log](https://github.com/mobile-dev-inc/maestro/files/12088183/maestro.log)

**Comment by ichlaufe** [comment]
With MAESTRO_VERSION={1.26.1} everything works fine.

**Comment by felipevolpone** [comment]
We will need your app binary and the Flow to investigate

**Comment by ichlaufe** [comment]
We have investigated this problem a little more closely. 
The cause is quite simple. With the version update from 1.26.1 to 1.27.0, there was a change in the way the app is started. 
My script took a Screenshot right after the app was launched, before the first test step, to capture the SplashScreen. 
And I use an emualtor with a high screen resolution to avoid too much scrolling in my tests.
It turns out that the first screenshot crashes because of the size related to netty: https://cloud.google.com/datastore/docs/concepts/limits

Taking screenshots later in the script just works fine. If you want to reproduce the problem, you can set up an emulator with a resolution of 2160x3840 and add the command to take a screenshot right after launching the app.

I have now removed the splash screen screenshot in my tests and everything is back to normal, all tests are running correctly.

**Comment by bartekpacia** [comment]
Please provide app binary and flow for investigation.
