### ISSUE TITLE
[Maestro version, e.g. v1.2.3] Cannot upload app file (ios) to run on Maestro Cloud

### ISSUE THREAD

**Issue by stephenduong12** [mobile-dev-inc/maestro#1269]
**Describe the bug**
I tried to run the test on Maestro Cloud, but got an issue as below. Could anyone can helps me with this?
I tried to run on sample workspace (download from Maestro website), just change to my own app and got an error 500

![image](https://github.com/mobile-dev-inc/maestro/assets/135583776/4edae8b0-05e4-430c-a9c8-d81c0a5c0ff5)

I also tried to run on my own workspace, and got an issue as below:

<img width="1065" alt="image" src="https://github.com/mobile-dev-inc/maestro/assets/135583776/2da3020f-a339-4f41-99cb-dc7fa6a51ef6">

**Comment by felipevolpone** [comment]
For the first command, you have to change the binary architecture as the error message suggests. Check our doc on how to do that.

For the second command, change the last part of the command to `test` instead of `test/noBestExecution.yaml`
