### ISSUE TITLE
Add support for flutter element keys

### ISSUE THREAD

**Issue by vbhvkthr1** [mobile-dev-inc/maestro#128]
It seems maestro does not support tap on flutter elements using key. This will be helpful to automate app build in flutter - similar to id/text, support for key for flutter element will help.

**Comment by dmitry-zaitsev** [comment]
@vbhvkthr1 Maestro relies on accessibility information (i.e. text, content description). As long as Flutter keys are exposed as accessibility information, we would be able to see it

**Comment by miquelbeltran** [comment]
I think Flutter is unable to expose those on Android. I am following this issue on the Flutter framework regarding that: https://github.com/flutter/flutter/issues/17988

On the other hand, I am trying with the ["Semantics" widgets](https://api.flutter.dev/flutter/widgets/Semantics-class.html), yet Maestro is unable to find my views (widgets), nor with "label" "value" or "toolTip", which should be exposed as accessibility info.

I haven't tried on iOS yet, I will report back when I do.

Any hints or working examples would be appreciated.

**Comment by JigneshWorld** [comment]
If we haven't explored the accessibility info hierarchy of screen/view then I would suggest trying the `maestro hierarchy`.

As this accessibility info is the foundation for these kinds of tools and it's much more helpful to write a flow/tests based on those.

If in any case, we feel the need to get support(from the maestro team / any other), sharing this accessibility info would be much helpful to debug the stuff.

**Comment by JigneshWorld** [comment]
I have tried it on Flutter ["Semantics" widgets](https://api.flutter.dev/flutter/widgets/Semantics-class.html) and it seems working for my one test use-case with my device.

**Comment by miquelbeltran** [comment]
As @JigneshWorld reported, wrapping Flutter Widgets with `Semantics` and setting the `label` does the trick, later the widgets can be selected. I am not sure why it did not work on my tests, but now I can confirm it works.

**Comment by Leland-Takamine** [comment]
@vbhvkthr1 @miquelbeltran @JigneshWorld We just released a Flutter-specific guide as well here: https://maestro.mobile.dev/platform-support/flutter
