### ISSUE TITLE
[Maestro version, 1.30.4] Android Recyclerview Item ID work around issue

### ISSUE THREAD

**Issue by UgurGuner** [mobile-dev-inc/maestro#1287]
**Describe the bug**
In IOS I can give ids to views in an item list. However, is there a way to do the same, giving ids or something similar to items in a recyclerview and use it. For Instance for the 4th item in the recyclerview:
-tapOn:
     id: “item4”
Or I can only go on with the string names? 

For example my flow: 

appId: ${APP_ID}
name: Test Flow
---
- launchApp
- tapOn:
    id: "btnLanguage"
- tapOn:
    id: "txtSearch"
- inputText: "Türkçe"
- runFlow: ../common/hideKeyboard.yaml
- tapOn:
    id:"trLanguage"
- tapOn:
    id: "btnSave"

**Comment by bartekpacia** [comment]
Closing as not reproducible.
