### ISSUE TITLE
[Feature Request] Maestro cloud recording and logs for first attempt (when test fails) 

### ISSUE THREAD

**Issue by furqandaud** [mobile-dev-inc/maestro#1290]
**Is your feature request related to a problem? Please describe.**

When a flow fails 2/2 attempts, is there any way to see what failed in first attempt?

What’s happening is that in our app once we move past some certain screens, we can’t go back ( it’s an onboarding/signup process ), Assuming that something failed in screen 5 in attempt(1), when cloud does second attempt, the flow which is written is expecting screen 1 so it fails to find content.

So recording and logs are coming of attempt 2, which is really not giving out any useful info. When I run whole flow locally it works fine so it has something to do with cloud and I am unable to see attempt 1 logs or recording.

To understand my case more I am also attaching the cloud runs links related to this issue.

https://console.mobile.dev/uploads/3a0b4185-a7d7-4ac3-96d3-1642ca3387ba?teamId=44956578-e848-4f4b-8555-fb1a75256f45&appId=1766cab8-d6bf-4113-a1a0-2156eb7fcce0&analysisId=678a18d1-00df-4dc5-bd55-69e2db22ad20&checkIdx=0

https://console.mobile.dev/uploads/1ea18265-4a87-4e32-b59e-ce913cde4541?teamId=44956578-e848-4f4b-8555-fb1a75256f45&appId=aeb076e8-1e85-4c05-a9e0-646c81f164cd&analysisId=0e6553ee-3fe4-4700-9843-23d6bf7adfde&checkIdx=0

**Describe the solution you'd like**

If we get to see at least the steps ( Like those green ticks, red ticks ) for the first flow if not recording, even that would be very helpful!

**Describe alternatives you've considered**

**Additional context**
![Screenshot 2023-07-26 at 6 30 45 PM](https://github.com/mobile-dev-inc/maestro/assets/111492691/df5be3fb-56a3-43b4-ab31-efe42efe0468)

**Comment by SynytsiaAlex** [comment]
It would be useful to be able to disable the "Intelligent Retry" option in the configuration file if a second attempt is unacceptable for a particular text. This feature could offer a swift solution and help in identifying issues within the test
