### ISSUE TITLE
[1.30.4] `config.yaml`s in subfolders are ignored

### ISSUE THREAD

**Issue by LukaszCuler** [mobile-dev-inc/maestro#1302]
**Describe the bug**
Not sure if it's a bug or expected behavior (if so, this issue might be a feature request? ;)), but was a little bit surprising to me.
Let's have a given folder structure:

```
flowsRoot/
    config.yaml
    flowA.yaml
    flowB.yaml
    groupOne/
        flowC.yaml
        flowD.yaml
    groupTwo/
        flowE.yaml
        flowF.yaml
```
`config.yaml` contains only:
```
flows:
  - "**"
```
for the recursive run.

If we run `maestro test flowsRoot/` we observe flows executed as below:
```
[Passed] flowA (1s)
[Passed] flowD (0s)
[Passed] flowC (0s)
[Passed] flowF (0s)
[Passed] flowE (0s)
[Passed] flowB (0s)
```

Now we want to modify the order - let set `flowsRoot/config.yaml` content to:
```
flows:
  - "**"
executionOrder:
  flowsOrder:
    - flowB
    - flowA
```

create `flowsRoot/groupOne/config.yaml` with:
```
flows:
  - "**"
executionOrder:
  flowsOrder:
    - flowC
    - flowD
```

and `flowsRoot/groupTwo/config.yaml` with:
```
flows:
  - "**"
executionOrder:
  flowsOrder:
    - flowE
    - flowF
```

Then we run `maestro test flowsRoot/` again, which results in a given order:
```
[Passed] flowB (0s)
[Passed] flowA (0s)
[Passed] flowD (0s)
[Passed] flowC (0s)
[Passed] flowF (0s)
[Passed] flowE (0s)
```

It looks the order defined in `flowsRoot/config.yaml` was respected, however, those included in subfolders' `config.yaml` weren't. The question is if that works like that by design (that root `config.yaml` defines behavior for all tests in scope) or is it a bug?

**Environment information (please complete the following information):**

- Maestro version: [1.30.4]
- Platform: [Android 13]
- Framework: [Native Android]
- Device model and OS version: Android Emulator based on Android 13
- Host: Mac M1

**Comment by felipevolpone** [comment]
You have to provide all the configurations in the config.yaml at the root level. Multiple config.yaml isn't supported right now
