### ISSUE TITLE
Stuck at "Run `maestro help command` to get help specific to a subcommand." on MacOS M2

### ISSUE THREAD

**Issue by corne-de-bruin** [mobile-dev-inc/maestro#1305]
**Describe the bug**
After installing Maestro by following the guide: https://maestro.mobile.dev/getting-started/installing-maestro I keep getting the message "Run `maestro help command` to get help specific to a subcommand." on every command.

**To Reproduce**
Follow the installation guide and run the maestro --version command

**Expected behavior**
It should be able to run/start maestro instead of returning the above message

**Screenshots**
<img width="682" alt="Screenshot 2023-08-01 at 14 46 07" src="https://github.com/mobile-dev-inc/maestro/assets/3504599/99c226f8-7261-489b-a37b-5204372870f5">

**Environment information (please complete the following information):**

- Maestro version: ? (should be the latest available version)
- Platform: -
- Framework: React Native
- Device model and OS version: -
- Simulator, emulator or physical device
- Host Mac M2 Pro

**Comment by 02gaurav** [comment]
Hi @corne-de-bruin , try `maestro -v`

**Comment by corne-de-bruin** [comment]
That's giving the same result
<img width="682" alt="Screenshot 2023-08-01 at 15 07 56" src="https://github.com/mobile-dev-inc/maestro/assets/3504599/6817ca5d-472b-4437-8620-c872f18dc3a8">

**Comment by corne-de-bruin** [comment]
Apparently there was an NPM package installed (maestro) that caused this behaviour
