### ISSUE TITLE
[Android] Tap action on switch wrongfully invokes multiple taps

### ISSUE THREAD

**Issue by cpaleop** [mobile-dev-inc/maestro#131]
Here is a video demo of the bug: https://www.youtube.com/watch?v=CxzJXZMOhIY

Even though only one tap action was specified, four tap-actions are being invoked on the view.

The app is just a `androidx.appcompat.widget.SwitchCompat` in a `FrameLayout`, no additional logic on the view. Same happens with `com.google.android.material.switchmaterial.SwitchMaterial`

**Comment by dmitry-zaitsev** [comment]
This happens because Maestro is expecting a view hierarchy to change after you tap on something, which is not the case with toggles. While we are thinking of a better API, you can specify `retryTapIfNoChange` to fix this behaviour for your app:

```
- tapOn:
      id: {your view id}
      retryTapIfNoChange: false
```

**Comment by cpaleop** [comment]
Good to know, thanks for the quick response!
