### ISSUE TITLE
Notifications from maestro cloud not arriving in Slack

### ISSUE THREAD

**Issue by pimentones** [mobile-dev-inc/maestro#1324]
**Describe the bug**
Notifications are not being delivered to slack channels when using the config.yml file.
I check the following:
- the config.yml file is valid
- the email in the file is correct

Until last Friday we were receiving the notification but suddenly they don't arrive anymore.

**Comment by ArthurSav** [comment]
I was not able to replicate this, as well as, @pimentones mentioned that the issue was resolved.
Very likely a Slack issue. Closing, unless more reports come in.
