### ISSUE TITLE
Maestro Cloud Github app fails to report back

### ISSUE THREAD

**Issue by raulriera** [mobile-dev-inc/maestro#1331]
**Describe the bug**
Maestro Cloud app is not reporting back to Github Actions, at the moment these two have completed in Maestro Console a while ago, but their status was never updated

- https://console.mobile.dev/uploads/8298bae5-44fc-41d5-8a63-c4e10553284b?teamId=6bfb2940-2d02-4c2b-bbc6-86d94cf44654
- https://console.mobile.dev/uploads/340bf4d5-ff96-4f8a-bb54-207649d628f2?teamId=6bfb2940-2d02-4c2b-bbc6-86d94cf44654

**To Reproduce**
Can't be reproduced consistently, fails intermittently 

**Expected behavior**
The action should report back with either a failure or a success

**Screenshots**

<img width="342" alt="Screenshot 2023-08-09 at 1 55 11 PM" src="https://github.com/mobile-dev-inc/maestro/assets/24159/16d24751-b9e9-4313-aa12-0e3840cdf146">

**Environment information (please complete the following information):**

Using this pinned version of cloud

```
      - name: Upload build to Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@7319c856f44eb157f524414fcfd074d632fc3b9d # v1.3.0
```

**Comment by axelniklasson** [comment]
Closing this out as this was due to having multiple checks with the same name setup in the repo and triggering both on each commit. The recommendation is to differentiate check names between platforms to avoid running into this problem.
