### ISSUE TITLE
[1.30.4] Location permissions alert not appearing in iOS

### ISSUE THREAD

**Issue by DevMobile2** [mobile-dev-inc/maestro#1332]
**Describe the bug**
Hi Team!. I am trying to test a functionality which uses users current location in iOS. On tapping a button it should ask for permissions dialog to allow or deny,on tapping allow it should fetch current location. But that dialog is not appearing.

I am also setting device current location using setLocation after launchApp. 

- setLocation:
    latitude: -10.8544921875
    longitude: 49.82380
    
Also i have tried allowing the location permission while launching like this.

- launchApp:
    permissions:
        location: always
        
 But this is not taking the lat longs which i gave in setLocation.

**Comment by bartekpacia** [comment]
closing as not reproducible
