### ISSUE TITLE
[Maestro version, e.g. v1.2.3] Cannot run subflows on Maestro Cloud

### ISSUE THREAD

**Issue by stephenduong12** [mobile-dev-inc/maestro#1333]
**Describe the bug**
Hi guys, I want to run all my workspace on Maestro cloud, but it seems not working at all, they cannot recognize my sub flow files

samples
 |----- ios-flow-staging.yaml
 |----- ios-flow.yaml
 |----- ProphetExchange-sandbox.zip

This is my command: maestro cloud -e APP_ENV=staging ProphetExchange-sandbox.zip ios-flow-staging.yaml
There is an error displayed Upload request failed (400): Flow file does not exist: jar:file:///tmpFiles/workspaces/workflow1363239561574391180.zip!/./ios-flow.yaml
Does Maestro support to run complicated workspace files with multiple sub flows?

![image](https://github.com/mobile-dev-inc/maestro/assets/135583776/9700a188-7a16-410d-a643-82a473b3536c)
![image](https://github.com/mobile-dev-inc/maestro/assets/135583776/f57ae163-fca4-451e-83d7-a8cce3aea3eb)
![image](https://github.com/mobile-dev-inc/maestro/assets/135583776/814255ed-75be-4d6a-bbf9-18894809dfb3)

**Comment by felipevolpone** [comment]
Update to the newer version of maestro and run this command instead
```maestro cloud -e APP_ENV=staging ProphetExchange-sandbox.zip .
