### ISSUE TITLE
[Feature Request] add changelogs to github release descriptions

### ISSUE THREAD

**Issue by walkerdb** [mobile-dev-inc/maestro#1336]
**Is your feature request related to a problem? Please describe.**
I rely on notifications from github to keep me up to date on new maestro releases. For most other libraries I track this way, their release notes are part of the release description, so I can see what changed either from the email or from the release itself. With Maestro I need to first go to the release tab, then hunt down the changelog file.

**Describe the solution you'd like**
If you have automation for release notes, could you use the same automation for updating the release description?

A smaller change may be to just link to the changelog file in the release description itself.

**Comment by bartekpacia** [comment]
Thanks for letting us know it would be useful for you. We're not gonna update old releases, but in the next one I promise we'll do better! 🙏🏻
