### ISSUE TITLE
[Maestro version, v1.27.0 till v1.31.0]

### ISSUE THREAD

**Issue by JessAA** [mobile-dev-inc/maestro#1339]
**Describe the bug**

Hi guys, I'm trying to upload a flow into maestro cloud. When i execute this command:

`maestro cloud --apiKey 7a0be70e-2334-429f-94b3-3966b38147ff android-debug.apk android-kmp-apprf-launch-app.yaml`

For info, the android-debug.apk support very well x86_64.

I have an issue while uploading flow into maestro cloud:

```
Upload failed with status code 500: org.postgresql.util.PSQLException: ERROR: null value in column "name" violates not-null constraint
  Detail: Failing row contains (60bd0b3d-2bce-48a3-ba7e-f49be246789e, 60e30912-7b55-4fc8-a434-5e9761d40be7, null, ANDROID, com.radiofrance.poc_kmm.android, null, f, 2023-08-11 14:32:35.079351, 2023-08-11 14:32:35.079351, 0, null). [statement:"INSERT INTO target(team_id, name, platform, application_id, application_name, baseline_branch) VALUES (:teamId, :name, :platform, :applicationId, :applicationName, :baselineBranch) RETURNING *", arguments:{positional:{0:60e30912-7b55-4fc8-a434-5e9761d40be7,1:null,2:ANDROID,3:com.radiofrance.poc_kmm.android,4:null,5:null}, named:{teamId:60e30912-7b55-4fc8-a434-5e9761d40be7,name:null,baselineBranch:null,applicationId:com.radiofrance.poc_kmm.android,platform:ANDROID,applicationName:null}, finder:[]}]
```
Can anyone help me solve this issue?

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Run `maestro cloud --apiKey 7a0be70e-2334-429f-94b3-3966b38147ff android-debug.apk android-kmp-apprf-launch-app.yaml`
2. The Flow fails to upload into maestro cloud

**Expected behavior**
Be able to upload  `android-kmp-apprf-launch-app.yaml` flow in maestro cloud.

**Screenshots**
<img width="1182" alt="Capture d’écran 2023-08-11 à 17 30 16" src="https://github.com/mobile-dev-inc/maestro/assets/30175141/1194a0a9-d261-442b-95be-64974c7c0fec">
<img width="1174" alt="Capture d’écran 2023-08-11 à 17 30 28" src="https://github.com/mobile-dev-inc/maestro/assets/30175141/ff4188e8-1138-4516-a839-cdc5ce5495cc">
![Capture d’écran 2023-08-11 à 12 03 54](https://github.com/mobile-dev-inc/maestro/assets/30175141/c892aa28-ced1-4fde-baf7-e190e9a68b77)

**Environment information (please complete the following information):**

- Maestro version [v1.27.0 -> v1.31.0]
- Platform: [Android 11.0]
- Framework: [KMP]
- Device model and OS version: [Pixel 4]
- Emulator
- Host [Mac M1]

**Workspace (if applicable)**
This is the flow that i try to run with maestro cloud:
```
appId: com.radiofrance.poc_kmm.android
---
- launchApp

```
Thanks!

**Comment by bartekpacia** [comment]
Hey @JessAA, do you still encounter this issue?
