### ISSUE TITLE
[Maestro cloud] Maestro cloud doesn’t recognize a file located in a folder above the flow

### ISSUE THREAD

**Issue by dtirafaelsouza** [mobile-dev-inc/maestro#1340]
Hi guys!
I’m have some problems to utilize the maestro cloud, more specifically to access archives from different folders.
This is an example, i have a flow that run a script (with a string library for internationalization) that are located in a folder above. When I run locally, the code works well, but when I run the maestro cloud command:

`maestro cloud --apiKey xxx --ios-version 16 -e APP_ID=xxx --app-file=xxx --flows='TermsAndConditionsFlow/terms-test-flows.yml'`

The cloud returns the error `"Upload request failed (400): Flow file does not exist: jar:file:///tmpFiles/workspaces/workflow1993298830842511077.zip!/./../dictionary.js" `

Could you tell me how I can make the cloud also recognize this dictionary file without having to run the entire maestro folder?

<img width="1340" alt="Captura de Tela 2023-08-11 às 11 38 30" src="https://github.com/mobile-dev-inc/maestro/assets/136634689/85c4f0bf-d7e6-499d-bb99-8b18deb2f1a6">

**Comment by bartekpacia** [comment]
This is working as intended. Only your _workspace_ is uploaded to Maestro Cloud, so anything you refer to in your test flow files must be located inside the workspace.
