### ISSUE TITLE
[Android] can't tap on a text that is visible

### ISSUE THREAD

**Issue by omid-ebrahimi** [mobile-dev-inc/maestro#1348]
**Describe the bug**
In the maestro cloud (Android) it can't touch the "Sverige" however it's clearly on the screen. It works on my local iOS Simulator.

**Expected behavior**
It should do the job the same as it does on the iOS simulator.

**Screenshots**
![image](https://github.com/mobile-dev-inc/maestro/assets/1673391/79e32cbe-d5b1-4d87-ba41-1666e80e0be0)

**Environment information (please complete the following information):**

- Maestro version: 1.31.0
- Platform: Android
- Framework: React Native
- Host: Maestro Cloud

**Comment by blacksrc** [comment]
This issue is also happening on android emulator (on linux). For some reason tapping on text is not working. `testID` works fine btw.

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue! Unfortunately, it's not reproducible to us.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

This issue does not contain such an example, therefore I'm going to reluctantly close it.

If you don't have time right now, that's totally OK. Feel free to open a new issue in the future with all the required information provided.

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
