### ISSUE TITLE
Ansible like manipulating data

### ISSUE THREAD

**Issue by danieltaub** [mobile-dev-inc/maestro#1365]
While utilizing Maestro for our UI tests, I've observed the need for enhanced data and string manipulation capabilities similar to those provided by Ansible. Having a more robust set of tools for these operations would substantially augment Maestro's functionality and ease many testing scenarios.

- `map`: This Ansible filter can extract and transform items from a list. In a testing scenario, it could be useful to transform test data on-the-fly.

- `combine`: This filter allows merging of dictionaries into one. This could be handy when combining multiple sets of test data into a single set for certain tests.

- `regex_replace`: Allows users to replace strings or patterns using regular expressions. When dealing with dynamic strings or generating unique identifiers for tests, this becomes invaluable.

- `default`: Provides a default value when a specific variable is undefined or null. This can make tests more robust by ensuring there's always a fallback value.

- `search`: Useful for searching a pattern within a string. It could aid in verification tests where you need to ensure certain patterns or data points are present in your output.

- `json_query`: This filter allows complex data querying of JSON structures based on specific conditions, helping in parsing and verifying complex test outputs.

- `flatten`: Converts lists of lists into a single list. It can be essential when dealing with hierarchical or nested test data

- `Uniq`: Ability to remove duplicate values from lists or sets, ensuring each entry is unique.

- `Count`: Count occurrences of a particular item or characteristic within a set of data.

**Comment by bartekpacia** [comment]
Hello @danieltaub, thank you for this detailed feature request.

To me, this sounds like something that'd be better off implemented in JS, rather than YAML. Wdyt?
