### ISSUE TITLE
More advanced JS engine support (eg, V8)

### ISSUE THREAD

**Issue by smikheiev** [mobile-dev-inc/maestro#1379]
The Rhino JS engine is quite limited and seems to be far from modern JS. For example, it doesn't support regex (in my use case - I need to fetch a login email and parse it to get a login link).

Would it be possible to add support for a better JS engine?
For example, there's this open source project https://github.com/caoccao/Javet/ which seems to be an integration of V8 in Java 💭

**Comment by amanjeetsingh150** [comment]
Hey @smikheiev maestro does support an experimental graal js engine. Can you check if this support fulfills your requirements?

Doc: https://maestro.mobile.dev/advanced/javascript/graaljs-support

**Comment by smikheiev** [comment]
hey @amanjeetsingh150! sorry, I missed that GraalJS supports the latest ECMAScript 🙈 I tried it briefly and it seems to work fine and fulfill our requirements. thanks! 👍🏻
