### ISSUE TITLE
[Feature Request] Framework to enable data driven execution

### ISSUE THREAD

**Issue by JayMehtaFR** [mobile-dev-inc/maestro#1386]
**Is your feature request related to a problem? Please describe.**
We don't have the ability to transfer a variable value from 1 flow file to another. This is in reference to main flow files in .maestro folder. 
I have a requirement where I have to create a batch with unique ID in Scenario#1. Next I have to stop the same batch in Scenario#2. Require a way to pass variable value across scripts. Currently I am able to achieve this using JS. But this seems like a workaround rather than a solution.

**Describe the solution you'd like**
A solution might be where maestro flow files can read JSON files using a keyword.
This will not just solve my problem. But also provide a data driven framework. Currently the variables passed as env in the start of the scripts are static. Also, you cannot list them like in an excel or json. The current usage is in a way limited.
Instead of JSON some other data structure can also provide the same solution, like xml, etc.

**Describe alternatives you've considered**
I can for my purposes create a framework completely out of javascript to do the exact same solution proposed above. However, that defeats the whole purpose of no code. A keyword and context provided my maestro itself should do the trick.

**Additional context**
Like currently we have env variable defined for each flow file. We can have a JSON predefined for each flow. This JSON can be read and write enabled across flows.

**Comment by bartekpacia** [comment]
Hey, thanks a lot for sharing this with us! Currently we don't have bandwidth to implement this feature.

If you narrowed down the scope and had some rough draft of the API you'd like from us, please feel free to create a new issue and we'll take another look :-)

For now, I'll close it since we're cleaning up our issue tracker to have only actionable stuff.
