### ISSUE TITLE
[v1.31.0] Maestro cloud runner times out

### ISSUE THREAD

**Issue by ferdy-roz** [mobile-dev-inc/maestro#1406]
**Describe the bug**
The Maestro cloud CLI tool times out even though the flows do not time out, with the following logs:

```
Upload did not complete in time due to an issue on mobile.dev side. Follow the results of your upload below:
--


https://console.mobile.dev/uploads/de4420b7-f718-420a-9afd-da99078f9df4?teamId=12ffe931-ef42-4f64-8b41-43cff78f82cc&amp;appId=efaf4b2b-73f0-43df-ba49-0b1e8d39beca
```

**Expected behavior**
The cloud runner should not time out unless the tests themselves time out

**Comment by felipevolpone** [comment]
The flow that was marked as canceled was canceled because because the dependency flow 'Edit Result Templates' failed
