### ISSUE TITLE
[Maestro version,1.11.0]

### ISSUE THREAD

**Issue by manish270820** [mobile-dev-inc/maestro#1408]
Bug - Unrecognized field "runScript" (class maestro.orchestra.yaml.YamlFluentCommand), not marked as ignorable (22 known properties: "tapOn", "openLink", "assertNotVisible", "longPressOn", "assertVisible", "inputRandomPersonName", "launchApp", "inputRandomEmail", "extendedWaitUntil", "eraseText", "action", "inputText", "runFlow", "inputRandomText", "repeat", "pressKey", "stopApp", "clearState", "takeScreenshot", "inputRandomNumber", "swipe", "setLocation"]) 

**below yml is working on emulator but not in real device.**
`appId: com.a.b

#- runFlow: ../Login/enterPin.yaml

    runFlow: ../login/loginFlow.yaml

    waitForAnimationToEnd:
    timeout: 3000

    tapOn:
    text: "Crypto"
    index: 1

    scrollUntilVisible:
    element: "Popular Crypto"
    direction: "DOWN"

speed: 100
visibilityPercentage: 100

    tapOn: "AssetCard Bitcoin"

    tapOn: "Buy"

    tapOn: "SIP"

    tapOn: " 0"

    inputText: "113"

    hideKeyboard

    tapOn: "Edit Date"

    assertVisible: "SIP Instalment Date"

#- tapOn: "3"

    back

    tapOn: "Next"

    assertVisible: ".*SIP"

    assertVisible: ".1st Instalment."

    tapOn: "Trade Preview Button"

    waitForAnimationToEnd:
    timeout: 3000

    runFlow:
    when:
    visible:
    text: "Submit"
    commands:
    - tapOn: "8"
    - tapOn: "Submit"

    assertVisible: "Woohoo!"

    assertVisible: "Manage SIP"

    tapOn:
    delay : 300
    text : "Manage SIP"

    assertVisible: "Orders & History"

    assertVisible:
    text: "Open"
    index: 1

    assertVisible:
    text: "History"
    index: 1

    assertVisible: "SIP"

    assertVisible: "Active"

    tapOn:
    text: "SIP BTC"
    index: 0

#- assertVisible: "Amount"
#- assertVisible: "Frequency"
#- assertVisible: "Next Instalment"

    tapOn: "Pause SIP"

    assertVisible: "Are you sure you want to Pause SIP?"

    tapOn: "Yes, Pause"

    assertVisible: "SIP has been paused successfully"

    assertVisible: "Paused"

    tapOn: "Paused"

    assertVisible: "Activate SIP"

    tapOn: "Activate SIP"

    tapOn: "Yes, Activate"

    assertVisible: "SIP has been resumed successfully"

    assertVisible:
    text: "Active"
    index: 0
    `

getting below issue , please help me on this

**Comment by felipevolpone** [comment]
You're using an old version of maestro. Update to the most recent one https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli

**Comment by manish270820** [comment]
Thanks felipevolpone. its working fine.
