### ISSUE TITLE
Wait for result before Tap on point.

### ISSUE THREAD

**Issue by misterjedu** [mobile-dev-inc/maestro#141]
After launching my App, I need to tap on a specific XY location on the home screen. But the view is already tapped on the splash screen, before the home screen loads. The same happens when there is a loading screen, and you need to tap on the location after the screen is loaded.

**Comment by dmitry-zaitsev** [comment]
Could you perhaps share a video recording and a yaml file that you use so that we can better understand the problem?

**Comment by dmitry-zaitsev** [comment]
Closing until more context is available
