### ISSUE TITLE
[Question] Click on view by Id. A real example of tapOn : "id"  

### ISSUE THREAD

**Issue by misterjedu** [mobile-dev-inc/maestro#142]
I am trying to tap on a particular icon, using its viewId. I use tapOn: "like_icon". 

I have tried to click on some views by their Id but none has worked for me.

**Comment by dmitry-zaitsev** [comment]
You are on the right track, but it is just a slightly different command:

```
- tapOn:
     id: {full id of your view}
```

Now, the id can include things like package name if you are on Android, so typically what I do is prefix it with `.*` to make it a regular expression:

```
- tapOn:
     id: .*myButton
```

Documentation for the `tapOn` can be found here: https://maestro.mobile.dev/reference/tap-on-view
