### ISSUE TITLE
Maestro version 1.31.0 - Not able to launch App on Real device

### ISSUE THREAD

**Issue by manish270820** [mobile-dev-inc/maestro#1423]
Problem Statement - Not able to launch App on Real device , if we launch manually , then next script is running fine but from our launch script is not launching app aautomatically on real device,,,Its working on emulator pefectly.

FIle name - homeRunner.yaml
appId: com.c.k
---

- startRecording: recording/homeRunner
#- runFlow: ../Login/login.yaml
#- runFlow: ../test/homepage/existingHomePageCrypto.yaml
- runFlow: ../test/homepage/existingHomePageWatchlistandPopularCrypto.yaml
#- runFlow: ../test/homepage/existingHomePageCategoriesToCryptoBytes.yaml

- stopRecording
----------->
file - login.yaml
appId: com.c.k
---
- clearState 
#- startRecording: "Login"
- launchApp
- waitForAnimationToEnd:
    timeout: 5000
- runScript: ../../js/login/loginPage.js
- tapOn: 
    text: ${output.LoginPage.letGetStartedBtn}
    delay: 200
#- tapOn:
#    id: "com.android.systemui:id/drip_network_speed_splitter"
#- tapOn:
#    id: "com.google.android.gms:id/cancel"
- tapOn: ${output.LoginPage.digitNumberTxb}
- repeat:
    times: 8
    commands:
      - tapOn: ${output.LoginPage.keyPadButton1Key}
- tapOn: ${output.LoginPage.keyPadButton2Key}
- tapOn: ${output.LoginPage.keyPadButton7Key}
- tapOn: ${output.LoginPage.verifyNumberBtn}
- tapOn: ${output.LoginPage.otpNumberTxb}
- repeat:
    times: 6
    commands:
     - tapOn: ${output.LoginPage.keyPadButton0Key}
- tapOn: ${output.LoginPage.verifyOTPBtn}
- tapOn: ${output.LoginPage.skipBtn}
- tapOn: ${output.LoginPage.keyPadButton1Key}
- tapOn: ${output.LoginPage.keyPadButton2Key}
- tapOn: ${output.LoginPage.keyPadButton3Key}
- tapOn: ${output.LoginPage.keyPadButton4Key}

- waitForAnimationToEnd:
    timeout: 5000

**Comment by amanjeetsingh150** [comment]
Hey @manish270820 can you give specifications for your physical device?

**Comment by NurayTumer** [comment]
I'm also having this issue 
![WhatsApp Image 2024-05-30 at 12 56 06 PM](https://github.com/mobile-dev-inc/maestro/assets/163411269/68baf2c4-b07f-43e8-9f2c-ef4d7e066290)
my device specifications are attached,

**Comment by NurayTumer** [comment]
@amanjeetsingh150 can you please check it up, topic is important for me.

**Comment by manish270820** [comment]
@NurayTumer -  `Can you please disable the Auto-optimization  in your device and try.. basically when ur app is in background , ur device doesn't allow to launch due to battery optimisation setting`Let me know ,if its doesn't work.
