### ISSUE TITLE
[Feature Request] Be able to define actual folder name of debug output rather than using datetime so we can access screenshots on CI runs

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#1427]
**Is your feature request related to a problem? Please describe.**
Unable to access screenshots/logs on CI due to the folder name being created using datetime at runtime

**Describe the solution you'd like**
Be able to define the actual folder the debug output screenshots/logs gets saved in, currently you can define the root folders but it always adds a folder at the end with the datetime of the run. This means it’s very difficult to be able to access these within CI if ever there’s a failure, as we have no idea what the folder will be called prior to the run.

**Comment by Fishbowler** [comment]
Would you expect this to be another flag to specify a subfolder? 
Or a flag that says "just put it where I said, no subfolders"?

**Comment by simon-gilmurray** [comment]
> Would you expect this to be another flag to specify a subfolder? Or a flag that says "just put it where I said, no subfolders"?

Either works 🙂

**Comment by Fishbowler** [comment]
If there's a `--flatten-debug-output` flag, is it worth removing the `.maestro/tests/` bit from the path too?

**Comment by Fishbowler** [comment]
Had a play, and came up with this: https://github.com/Fishbowler/maestro/commit/972f6154009567fd395e3912fd985131eb85d1ab

Does this look like it would do what you want?

**Comment by simon-gilmurray** [comment]
Nice one, looks great!
