### ISSUE TITLE
Not seeing ID for most of the elements

### ISSUE THREAD

**Issue by Arulsundarmts** [mobile-dev-inc/maestro#1428]
Not seeing ID for most of the elements

this is forcing me to use only the 'Text' property to 'tapOn' and navigate.

When using apps with multiple languages, the Text property varies for each language. 

How to get element ID for every element?

**Comment by amanjeetsingh150** [comment]
Hey @Arulsundarmts we would need more information to debug the issue. Platform, android/ios version, framework, steps to reproduce.

**Comment by ivancantarino** [comment]
I have this same issue.

Maestro is not able to find the views for the given `id`, but when using the `text` field it works, though I don't want to rely on the `text` field, due to translations.

Code example:

```ruby
appId: com.myAppId
tags:
  - myTag
---

- launchApp:
    appId: "com.myAppId"

- waitForAnimationToEnd:
    timeout: 5000

- swipe:  
    start: 50, 400
    end: 50, 100

- waitForAnimationToEnd:
    timeout: 10000

- tapOn:
    id: "MAESTRO_ID"
```

**Comment by bartekpacia** [comment]
Hey, thanks y'all for creating this issue - unfortunately, it's not easily reproducible. We have a huge backlog, so it's important we can triage issues in an efficient manner.

Please provide [a minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
