### ISSUE TITLE
inputText on Android is sometimes inconsistently typing the wrong strings

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#1435]
**Describe the bug**
One of my Android tests has failed twice in two days typing the wrong thing ( 5.757 instead of 57.57) as part of my morning smoketests. Subsequently running this individually, it worked ok.

```
[INFO ] m.cli.runner.TestSuiteInteractor - Input text 57.57 RUNNING
[INFO ] maestro.Maestro - Inputting text: 57.57
[INFO ] m.cli.runner.TestSuiteInteractor - Input text 57.57 COMPLETED
```

![screenshot-❌-1694506012940-(home_transactionFeed)](https://github.com/mobile-dev-inc/maestro/assets/74550141/bb8df0fc-14f3-47e7-ad72-5aaa769e78b6)

**To Reproduce**
Use inputText and observe that a lot of the times it works, but sometimes it types the string incorrectly

**Expected behavior**
String should type as expected

**Environment information (please complete the following information):**

- Maestro version v1.32.0
- Platform: Android 13
- Framework: Native Android
- Device model and OS version: Pixel 6 Pro
- Simulator, emulator or physical device: Emulator
- Host: Mac

**Comment by simon-gilmurray** [comment]
@axelniklasson I've only noticed it happening when the string contains a decimal point `.` so perhaps that could be related

**Comment by axelniklasson** [comment]
@simon-gilmurray interesting, thanks for that context. We do dispatch individual key events for each character the same way for periods and characters (source code [here](https://github.com/mobile-dev-inc/maestro/blob/main/maestro-android/src/androidTest/java/dev/mobile/maestro/MaestroDriverService.kt#L380)) and we haven't seen any other complains for input text on Android 🤔 are you able to consistently reproduce this issue or did it only happen the two times?

**Comment by simon-gilmurray** [comment]
I've only seen it the two times on two consecutive days - but haven't seen it since. I'll let you know if it happens again.

**Comment by balsick** [comment]
This happens for me as well, but also on iOS and without any `.` character in it.

**Comment by MariaMatyushenkoMicropsi** [comment]
Hey! Occasionally happens in my tests as well. Do not have a `.` character, just a string. And sometimes `maestro` messes up with the input.
Example of a give string: `UI tests - pos dual cam`; maestro inputs the following value instead: `m-pos dual UI test`
I am using Android emulator and maestro version 1.33.0

**Comment by axelniklasson** [comment]
Let's keep the discussion in #395, closing this as duplicate
