### ISSUE TITLE
[1.32.0] Numbers in flows cannot be split with `_` (was working on 1.31.0)

### ISSUE THREAD

**Issue by bmarty** [mobile-dev-inc/maestro#1448]
Not following your issue template (sorry!), just pointing to how we fixed this issue: https://github.com/vector-im/element-x-android/commit/c6d68e8392304e1e6118e26dee2970ae627c3972

Not a big deal, but just to let you know!

**Comment by axelniklasson** [comment]
@amanjeetsingh150 is working on a fix for this, thanks for raising this issue @bmarty!

**Comment by axelniklasson** [comment]
Closing this out as this will go out in the next relase
