### ISSUE TITLE
[Feature Request] Maestro command to update version

### ISSUE THREAD

**Issue by Angelk90** [mobile-dev-inc/maestro#1451]
**Is your feature request related to a problem? Please describe.**
Instead of using the curl command:

`curl -Ls "https://get.maestro.mobile.dev" | bash
`

It would be more convenient for the master to have his own command.

**Describe the solution you'd like**

`maestro update` or `maestro up`

**Comment by bartekpacia** [comment]
We will not provide this, sorry.

If you're on macOS, use Homebrew (see also #1513). You can also always continue to keep using the script installation method.
