### ISSUE TITLE
[v1.32.0] `--result-wait-timeout` doesn't do anything

### ISSUE THREAD

**Issue by ferdy-roz** [mobile-dev-inc/maestro#1456]
**Describe the bug**
My maestro cloud runner was timing out and gave me the message

```
To extend the timeout, run maestro with this option `maestro cloud --result-wait-timeout=<timeout in minutes>
```

Running `maestro cloud --result-wait-timeout=120` yields 

```
Unknown option: '--result-wait-timeout=120'
```

**Comment by ferdy-roz** [comment]
Looks like the real option might be `--timeout` as per https://github.com/mobile-dev-inc/maestro/commit/dc699a466c83f6492b9ac830a38abc9f6d33df57#diff-0a19fdf026f7d770725b2d8ce1bc06f34eeef7050f46e0ce0f11c33f9ebfd38cR149

**Comment by axelniklasson** [comment]
Closing this out as this will go out in the next release
