### ISSUE TITLE
[v1.32.0] iOS: maestro-driver-iosUITests-Runner quit unexpectedly.

### ISSUE THREAD

**Issue by deepeshsubedi8** [mobile-dev-inc/maestro#1466]
**Describe the bug**
When simultaneously running both the maestro studio & a flow locally, I receive the following error message frequently which disrupts the flow execution.

**To Reproduce**

1. Start the simulator
2. Start maestro studio
3. Run `maestro test ...`

**Expected behavior**
Flow execution should not be affected while the maestro studio is also running.

**Screenshots**
<img width="467" alt="Screenshot 2023-09-19 at 4 57 02 PM" src="https://github.com/mobile-dev-inc/maestro/assets/135839296/265900a6-e83f-49de-8ba5-e0705735907a">

**Environment information:**

- Maestro version: v1.32.0
- Platform: iOS 16.4
- Framework: Native iOS
- Device model and OS version: iPhone 14 Pro Max
- Simulator
- Host: Mac M2 Air

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue! Unfortunately, it's not reproducible to us.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

This issue does not contain such an example, therefore I'm going to reluctantly close it.

If you don't have time right now, that's totally OK. Feel free to open a new issue in the future with all the required information provided.

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
