### ISSUE TITLE
Update docs on Pass variables to tests

### ISSUE THREAD

**Issue by b099l3** [mobile-dev-inc/maestro#147]
In the example command for [Pass variables to tests ](https://maestro.mobile.dev/getting-started/maestro-cli#pass-variables-to-tests), there are one too many `test` commands, i.e., 
```
maestro test -e USERNAME=user@example.com -e PASSWORD=123 test file.yaml
```

I think this would be:
```
maestro test -e USERNAME=user@example.com -e PASSWORD=123 file.yaml
```

I can't seem to find the docs code on this repo. Is it public? If so, I will create a PR for this change if not, can I log it here?

**Comment by dmitry-zaitsev** [comment]
Thank you for spotting that. I just updated the docs (might take a few minutes to propagate).

For now, we are keeping our documentation in Gitbook, so it is not public yet (but it might become in the future).
