### ISSUE TITLE
[1.32.0]inputText command does not work when keyboard is disabled or hidden for flutter app

### ISSUE THREAD

**Issue by NireekshaPoojary** [mobile-dev-inc/maestro#1478]
Describe the bug:

When flutter apk is build by having enableFlutterDriverExtension(); in main.dart file, this will disable keyboard, in this case inputText does not works

To Reproduce:

Steps to reproduce the behavior, e.g.:
1. yaml file
appId: com.ap.ap.dev
---
- runFlow: "selectLanguage.yaml"
- tapOn: "phone-icon.*"
- inputText: 0123456669
- tapOn:
    above: "terms and conditions"
- waitForAnimationToEnd:
    timeout: 10000
- tapOn:
    above: "Submit"
    point: 166, 878
- inputText: "1"
- inputText: "3"
- inputText: "5"
- inputText: "1"
- inputText: "0"
- inputText: "2"
- waitForAnimationToEnd
- stopRecording

Note: Same flow works, when apk is build without FlutterDriverExtension

Expected behaviour:

Existing inputText command could be enhanced or new command could be provided which allows to enter text even when keyboard not available through copy paste option 

Environment information (please complete the following information):

- Maestro version [e.g. v1.2.3] - 1.32.0
- Platform: [e.g. iOS 16.4.1, Android 11.0, Chrome] - Android 12
- Framework: [Native iOS/Android, Flutter, React Native, etc] - Flutter
- Device model and OS version: [e.g. iPhone6] - Android Pixel XL API 31
- Simulator, emulator or physical device - Emulator
- Host [e.g. Mac M1, Windows, Linux, etc] - Mac M1

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue - unfortunately, it's not easily reproducible. We have a huge backlog, so it's important we can triage issues in an efficient manner.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
