### ISSUE TITLE
setTimeout in runScript

### ISSUE THREAD

**Issue by dansimau** [mobile-dev-inc/maestro#1482]
I am using `runScript` to execute a JS script but, I get the following error:

```
TypeError: TypeError: setTimeout is not a function, it is object. (scripts/fetch-invitation-url.js#11)}
```

Inside the script I am trying to sleep before performing a HTTP request (with retries), as I need to wait for an async process on my backend to finish executing.

Is `setTimeout` supported? Is there another wait for me to pause execution for a period of time?

**Comment by NicolaGugole** [comment]
+ 1

**Comment by mikevercoelen** [comment]
Bump

**Comment by bartekpacia** [comment]
What JS engine do you use? GraalJS or Rhino?

**Comment by bartekpacia** [comment]
I checked it. `setTimeout` works only with GraalJS.

```yaml
appId: com.example.example
jsEngine: graaljs
---
- launchApp
- runScript:
    file: script.js
```

```js
setTimeout(() => {
  console.log("Delayed for 1 second.");
}, 1000);
```

Solution: please use GraalJS instead of RhinoJS.
