### ISSUE TITLE
Unsupported architecture UNKNOWN [1.33.0]

### ISSUE THREAD

**Issue by TheLastProject** [mobile-dev-inc/maestro#1492]
**Describe the bug**
Running `maestro studio` fails with the error "Unsupported architecture UNKNOWN"

**To Reproduce**
1. Run `maestro studio`
2. Select "[1] Start or create a Maestro recommended device" on the "No running devices found." message
3. Enter `android` on the "Please specify a device platform [android, ios, web]:" message
4. Press Enter on the "Please specify Android version [33, 31, 30, 29, 28]: Press ENTER for default (30)" message
5. See an error message: "Unsupported architecture UNKNOWN"

**Expected behavior**
`maestro studio` creates an emulator

**Environment information (please complete the following information):**

- Maestro version: 1.33.0
- Platform: Android 11.0
- Framework: Native Android (java)
- Device model and OS version: Unknown
- Simulator, emulator or physical device: Emulator (I think? I assume it wants to make an emulator in this wizard)
- Host: Linux (Fedora 38 on an AMD Ryzon 7 5800H (which is x86_64))

**Bugreport output (if applicable)**
[2023-09-28_182059.zip](https://github.com/mobile-dev-inc/maestro/files/12751817/2023-09-28_182059.zip)

(Seems `maestro studio` already makes such a bugreport, the `maestro bugreport` output contained less info)

**Additional context**
I did a quick read into the code and while I'm definitely not a Maestro expert (this is me trying it for the first time), I think ede703b6e5b357d417458ac26902dd362f33a070 might be related to this issue.

After all, neither `sysctl` commands would work under Linux:
```
$ sysctl hw.optional.arm64
sysctl: cannot stat /proc/sys/hw/optional/arm64: No such file or directory
$ sysctl hw.optional.x86_64
sysctl: cannot stat /proc/sys/hw/optional/x86_64: No such file or directory
```

But the old command, `uname -m` would have returned `x86_64`:
```
$ uname -m
x86_64
```

If the `getMacOSArchitecture` function is also used on Linux, this would be a possible lead.

**Comment by evanheisler** [comment]
I've hit this as well, trying to use `maestro start-device` during CI on a linux box. Exits with `architecture UNKNOWN`.
