### ISSUE TITLE
[v1.33.0] Exception in thread `pool-4-thread-1` with Github actions

### ISSUE THREAD

**Issue by kojofosu** [mobile-dev-inc/maestro#1495]
**Describe the bug**
I always get this error on the 10th or 11th flow to run in the `config.yaml` file. 
![image (1)](https://github.com/mobile-dev-inc/maestro/assets/20203694/5d126507-8326-48f8-a87b-fd1b2a5ab8f0)

I then tried to remove the extra flows to have just 9 flows and the tests pass now. Pic below
![image (2)](https://github.com/mobile-dev-inc/maestro/assets/20203694/38d70575-f28d-46ec-900f-a861e9da3e45)

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Have upto 11 flows to run in the `config.yaml` file.
2. Run maestro test for the with Github actions
3. 1Exception in thread pool-4-thread-1` on the 9th flow

**Expected behavior**
All flows are expected to pass and error is not due to flows failing. 

**Screenshots**
![image (1)](https://github.com/mobile-dev-inc/maestro/assets/20203694/5d126507-8326-48f8-a87b-fd1b2a5ab8f0)
![image (2)](https://github.com/mobile-dev-inc/maestro/assets/20203694/38d70575-f28d-46ec-900f-a861e9da3e45)

**Environment information (please complete the following information):**

- Maestro version [e.g. v1.33.0]
- Platform: [eAndroid SDK 31,]
- Framework: [Emulator on Github actions]
- Android 12
- Emulator
- Host [Github actions running Macos host]

**Workspace (if applicable)**
Please share your workspace with Flow files and application binary if you are able to do so as that greatly helps in reproduction efforts.

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

**Additional context**

**Comment by DavidREntwistle** [comment]
I'm also facing this same issue.

**Comment by DavidREntwistle** [comment]
Noticed this issue again, this mainly looks to be Android 12 causing the issue.

**Comment by felipevolpone** [comment]
Android emulators are not super reliable and things running on the machine they run on could interfere on their behavior. There are many reasons for to this error to happen and it's outside of what maestro as a project tries to accomplish, so I'm marking this as won't fix.
