### ISSUE TITLE
[v1.32.0] Firebase Remote config fetch fails on cloud iOS simulator

### ISSUE THREAD

**Issue by arashgm** [mobile-dev-inc/maestro#1496]
**Describe the bug**
Our app uses Firebase remote configs , the flows run pretty fine locally on android emulator , devices and iOS simualtor , but when we try to run our flows on cloud , all our tests getting failed on iOS simualtor because remote configs cannot be fetched from Firebase.     
i wonder if your servers got blocked or being throttled by Firebase? 

**Expected behavior**
Remote Config should be fetched normally

**Additional context**
Error Message in logs : Failed to get installations token. Error : Error Domain=com.firebase.installations Code=0 "Underlying error: The operation couldn’t be completed. SecItemCopyMatching (-34018)"

**Comment by fantpmas** [comment]
We have the same issue.

**Comment by axelniklasson** [comment]
This specific issue was due to specifying `--no-codesign` as part of `flutter build`. @fantpmas are you also using a flutter app?

**Comment by fantpmas** [comment]
Hi @axelniklasson, just ran the tests again and this seems to have been solved in the mean time. We're using React Native by the way.
