### ISSUE TITLE
[v1.3.3] Cloud runner gets into a bad loop installing the maestro driver app?

### ISSUE THREAD

**Issue by ferdy-roz** [mobile-dev-inc/maestro#1497]
**Describe the bug**
The fifth or sixth flow in a suite in maestro cloud will always get canceled or time out due to the maestro driver app seemingly trying to install and spinning forever.

**Expected behavior**
All my tests run in the cloud (works locally)

Example console link: https://console.mobile.dev/uploads/16e8c214-7a12-456b-be40-1617128eca04?teamId=12ffe931-ef42-4f64-8b41-43cff78f82cc&appId=efaf4b2b-73f0-43df-ba49-0b1e8d39beca&analysisId=24b5fadf-0811-4be5-8cb0-dca125135908

**Comment by lucasfronza** [comment]
> canceled or time out due to the maestro driver app seemingly trying to install and spinning forever

Same here: https://console.mobile.dev/uploads/82ffe032-601d-4a66-9eee-1bb53dbfa87a?teamId=7f598273-b6c6-4b57-847f-43deff0eda2f&appId=2c8323fd-2c1b-497a-bcb5-a675b729de1f&analysisId=4d4f56c4-d313-4166-874f-16f7e6bff38e&checkIdx=1

**Comment by ferdy-roz** [comment]
Seems to have been fixed in the latest release
