### ISSUE TITLE
handle automated selfies

### ISSUE THREAD

**Issue by reymalahay** [mobile-dev-inc/maestro#1505]
**Is your feature request related to a problem? Please describe.**
this is not a problem.

**Describe the solution you'd like**
will it be possible to add a feature to handle automated selfies?

**Describe alternatives you've considered**
saucelabs has something, but it involves uploading the app to the cloud. i want to perform automated tests locally.

please advise.

thanks in advance,
rey malahay

**Comment by bartekpacia** [comment]
Hi, thanks for taking time to create an issue. We'd really appreciate if you explained your request in more detail, as of now it's not really actionable and since we have lots of issues to handle, we tend to close underspecified ones.
