### ISSUE TITLE
Support for NX - `@nx/maestro`?

### ISSUE THREAD

**Issue by tmc** [mobile-dev-inc/maestro#1510]
I'd be great if NX and Maestro worked well together. 

https://nx.dev/nx-api/detox is an existing plugin that could be used for inspiration.

https://github.com/nrwl/nx/issues/19470

**Comment by bartekpacia** [comment]
Hi @tmc, thanks for using Maestro and creating this issue!

I'm not familiar with neither `nx`, and only a bit with Detox. Could you share what would be use-case for such an integration? Is there anything that cannot be achieved without it?
