### ISSUE TITLE
[v1.33.1] React native alerts not visible if the hierarchy is greater than some max depth

### ISSUE THREAD

**Issue by ferdy-roz** [mobile-dev-inc/maestro#1511]
**Describe the bug**
React native alerts are not visible/interactable to maestro if the view hierarchy grows past a certain depth.

**Expected behavior**
Buttons are clickable by maestro flows

**Comment by amanjeetsingh150** [comment]
Hey @ferdy-roz can you provide a sample app where this is reproducible?

**Comment by ferdy-roz** [comment]
@amanjeetsingh150 https://console.mobile.dev/uploads/90788ba9-49bb-4032-adc1-3b6f2d088f93?teamId=12ffe931-ef42-4f64-8b41-43cff78f82cc&appId=efaf4b2b-73f0-43df-ba49-0b1e8d39beca&analysisId=24b5fadf-0811-4be5-8cb0-dca125135908

**Comment by ferdy-roz** [comment]
any update on this? @amanjeetsingh150

**Comment by jp928** [comment]
+ 1

**Comment by felipevolpone** [comment]
There isn't much we can do here. The view hierarchy of some React Native apps are too bad and maestro relies on the view hierarchy to run commands. Our recommendation is this:

```
If you are using React native, consider migrating to the new architecture where 
view flattening is available. For more information on the migration process, 
please visit: https://reactnative.dev/docs/new-architecture-intro"
```
