### ISSUE TITLE
Support code coverage collection for react-native targets

### ISSUE THREAD

**Issue by tmc** [mobile-dev-inc/maestro#1512]
I'm not seeing a mechanism to support collecting code coverage, what would support for this look like?

**Comment by Maxim-Filimonov** [comment]
I wonder how will this work as from my understanding it's using native drivers to drive UI. 
For example, as Appium uses similar approach - https://stackoverflow.com/questions/36924528/appium-ios-code-coverage#:~:text=It%20is%20not%20possible%20to%20do%20a%20code,it%20get%20called%20when%20the%20test%20is%20done./n.

**Comment by bartekpacia** [comment]
Maestro isn't a tool for collecting e2e code coverage.

If you want code coverage, I think you should at tools that are more far away from the end user, and closer to the source code. Links shared by @Maxim-Filimonov above are a good start.
