### ISSUE TITLE
Restore Homebrew support 

### ISSUE THREAD

**Issue by tmc** [mobile-dev-inc/maestro#1513]
Please consider resuming support for homebrew as a distribution mechanism, in some enterprises a "curl pipe bash" installation methodology isn't going to fly.

**Comment by schmod** [comment]
Strongly agree here.  This installation procedure unnecessarily opens your users up to a security risk.

**Comment by bartekpacia** [comment]
Thanks for voicing your concerns. We see the problems with the current approach, and are considering restoring Homebrew way of installation in the near future. Thanks for understanding!

**Comment by bartekpacia** [comment]
Example of a good-looking formula that requires JVM: [detekt](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/d/detekt.rb)

**Comment by bartekpacia** [comment]
[Homebrew is back](https://medium.com/p/581431428562)!
