### ISSUE TITLE
iOS 17 support

### ISSUE THREAD

**Issue by tmc** [mobile-dev-inc/maestro#1514]
https://github.com/mobile-dev-inc/maestro/blob/e768b912ce3509bae85560d9d6871992487f3f6a/maestro-cli/src/main/java/maestro/cli/util/DeviceConfig.kt#L6-L10

This appears to imply 15 and 16 are supported.

**Comment by radhakrishnanakireddy** [comment]
Hi
Could please provide to latest iOS version support

**Comment by bartekpacia** [comment]
This was implemented in https://github.com/mobile-dev-inc/maestro/pull/1569
