### ISSUE TITLE
tapOn issues on iOS

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#152]
I'm trying to get past a simple passcode entry screen after the app launches...

My passcode is 1112 in this example

```
- tapOn: "1"
- tapOn: "1"
- tapOn: "1"
- tapOn: "2"
```

This seems to be tapping on 1 four times for each line, which hits an incorrect passcode entry error and then clears the passcode automatically. It does this three times over, and then on the tapOn 2 it taps on 2 once.

If I query the hierarchy, it shows the resource-id of 1 to be  "key_1", but when I try to tap on this it does nothing and seems to be unable to find it. Are we not able to tap on Accessibility/Resource IDs?

I seem to be able to somewhat temporarily get around it by tapping 1 which enters it four times and gets the incorrect passcode error, then input the text "1112" and press enter which proceeds correctly but obviously this is not a solution...

**Comment by dmitry-zaitsev** [comment]
This is a known issue that we are working on solving, luckily there is an easy way to work around it on your side: https://maestro.mobile.dev/troubleshooting/known-issues#maestro-taps-on-the-same-view-multiple-times
