### ISSUE TITLE
A better way to automate tab clicking

### ISSUE THREAD

**Issue by reymalahay** [mobile-dev-inc/maestro#1524]
**Describe the bug**
This is an extension to #511 

**To Reproduce**
please follow the steps in #511

**Additional context**
Is there a better way to auto clicking on tabs, as opposed to what was discussed in #511? especially in a where there is no tab labels but only icons.

please advise,

thanks in advance,
rey malahay

**Comment by felipevolpone** [comment]
Duplicated of #1544
