### ISSUE TITLE
[Feature Request] Use pasetext in a variable

### ISSUE THREAD

**Issue by satbirkira** [mobile-dev-inc/maestro#1529]
You can see below that I would like to extract the link, and browse to it, but according to the documentation, I can only use the value by pasting it into else, by doing a tapon and then a paste.

<img width="1216" alt="Screenshot 2023-10-16 at 9 04 22 PM" src="https://github.com/mobile-dev-inc/maestro/assets/5432756/de993096-0686-4959-8bb8-daa64d25f273">
<img width="1216" alt="Screenshot 2023-10-16 at 9 04 49 PM" src="https://github.com/mobile-dev-inc/maestro/assets/5432756/d4fd3ffe-a689-4c45-9285-f78da931e699">

**Comment by satbirkira** [comment]
Hi, apparently it is possible via maestro.copiedText. Can this be added to the documentation?

![Uploading Screenshot 2023-10-17 at 10.45.37 AM.png…]()

**Comment by bartekpacia** [comment]
Thanks! Resolved in https://github.com/mobile-dev-inc/maestro-docs/pull/74
