### ISSUE TITLE
[Feature Request] Can we add custom message on failing an assert than showing id of an element?

### ISSUE THREAD

**Issue by amar-mindtickle** [mobile-dev-inc/maestro#1539]
**Is your feature request related to a problem? Please describe.**
Can we add custom message on failing an assert than showing id of an element?
❌  Assert that id: com.foo-bar.qa:id/recordingListItemLayout, Index: 0 is visible     

**Describe the solution you'd like**
Show custom message set in code when any assert fails.
❌  Assert that filter button is visible

**Comment by bartekpacia** [comment]
You can use labels for that.

see https://github.com/mobile-dev-inc/maestro-docs/pull/51
