### ISSUE TITLE
App crash detection

### ISSUE THREAD

**Issue by martinlAP** [mobile-dev-inc/maestro#1540]
Hello,

Sorry in advance if this topic has already been created or discussed.

I was wondering if there is anyway to detect app crashes with maestro? 

Thank you in advance.

**Comment by axelniklasson** [comment]
Not when using the CLI specifically, but we have built in support for this in [Maestro Cloud](https://cloud.mobile.dev/) that will automatically mark your Flows as failed if the app crashes.
