### ISSUE TITLE
tapping on tabs

### ISSUE THREAD

**Issue by reymalahay** [mobile-dev-inc/maestro#1544]
Hi @reymalahay please open a new ticket describing your issues and the steps necessary to reproduce it.

_Originally posted by @ArthurSav in https://github.com/mobile-dev-inc/maestro/issues/497#issuecomment-1761085038_

hi there,

is there a way to tap on tabs during automated tests?

**Is your feature request related to a problem? Please describe.**
i have a `react native` application that uses `Tabs`. at the moment, `maestro` cannot detect the `testIDs` that were assigned to the tabs.

**Describe the solution you'd like**
i would like to use the `testID` attribute on these tabs so that i can click on them. 

**Describe alternatives you've considered**
the current workaround i use is to `swipe left` and `swipe right`. 

**Additional context**
n/a

please advise.

thanks in advance,
rey malahay

**Comment by chris-hud** [comment]
I have this same issue, testing on an ios device

**Comment by felipevolpone** [comment]
Run `maestro hierarchy` and check if the tap elements are there and if they have ids, if not you will have to use the text or coordinates to tap on them

**Comment by tommywong-flux** [comment]
@reymalahay Is the `Tabs` you are using from `expo-router` or `react-navigation`? If so, you may try to run `maestro studio` and click on the tab you want to target on, it will normally give you 2 options to whether tap based on the text or based on the graphic position.

For my case, it looks something like `tapOn: 'ACCOUNT, tab, 3 of 3'` after inspecting from `maestro studio`.
