### ISSUE TITLE
[1.33.1] launchApp closes the open app and marks case as success on Android real devices.

### ISSUE THREAD

**Issue by amar-mindtickle** [mobile-dev-inc/maestro#1562]
**Describe the bug**
launchApp closes the open app and marks case as success on Android real devices.
It works on emulators.

**To Reproduce**

1. Start the simulator
2. Run `maestro test ...` on Android real device
3. The Flow fails at "- launchApp"

**Expected behavior**
App should by launched irrespective of current state; launched or terminated

**Environment information (please complete the following information):**

- Maestro version [1.33.1]
- Platform: [Android]
- Framework: [Android]
- Device model and OS version: [Samsung F62, Mi 10i]
- Physical device
- Host [Mac M1]

**Additional context**
Same code with launchApp works on Android emulator.

**Comment by DavidREntwistle** [comment]
I have noticed this on Android emulators too.

**Comment by felipevolpone** [comment]
We don't officially support physical devices so I'm closing this as won't fix.
