### ISSUE TITLE
[1.33.1] Not able to tap on an IconButton (specifically) on Flutter

### ISSUE THREAD

**Issue by mike-mathieu** [mobile-dev-inc/maestro#1563]
**Describe the bug**
On my app using Flutter version 3.13.9 I am unable to `tapOn` an IconButton despite adding a semanticLabel to the Icon. Note: maestro studio also suggests to use the semanticLabel that I've provided. Furthermore, maestro shows a _green check mark_ next to the step indicating that it has successfully tapped on the button, however, nothing happens (it should take you to the next screen). Here is the code for the IconButton:

```
IconButton(
  splashColor: Colors.transparent,
  onPressed: onAccountPressed,
  icon: const Icon(
    Icons.account_circle,
    semanticLabel: "icon-lyrics",
  ),
)
```

I have also tried wrapping with a Semantics widget but gotten the same result.
And here is the maestro yaml code:

```
- assertVisible: "icon-lyrics"
- tapOn: "icon-lyrics"
```

The strange thing is, if I leave everything else the same but change it to use a FloatingActionButton **it works correctly**. The new code being:

```
FloatingActionButton(
  splashColor: Colors.transparent,
  onPressed: onAccountPressed,
  child: const Icon(
    Icons.account_circle,
    semanticLabel: "icon-lyrics",
  ),
)
```

**Environment information (please complete the following information):**

- Maestro version 1.33.1
- Platform: Android 14.0
- Framework: Flutter
- Physical device (Pixel 7)
- Host Mac

**Comment by ghassenk** [comment]
I had the same issue and fixed it by wrapping the Icon object inside a Semantics widget and it is now working:
IconButton(
      icon: SemanticsWrapper.wrapWithId(
        identifier: identifier,
        child: const Icon(Icons.more_vert),
      ),

**Comment by mike-mathieu** [comment]
@ghassenk thanks! We ended up wrapping the IconButton and it seems to be working now. I will close the issue.

```
      child: Semantics(
        button: true,
        label: 'Account',
        child: IconButton()...
```
