### ISSUE TITLE
How to properly use regex with selectors? [Feature Request]

### ISSUE THREAD

**Issue by satbirkira** [mobile-dev-inc/maestro#1566]
Can the docs have a page dedicated to regex? Cause right now I know it's possible but no clue how

**Comment by axelniklasson** [comment]
@satbirkira maestro does not have a custom Regex implementation as it's using normal Regex syntax under the hood, so I would recommend googling / checking out other resources for how regex works if you're looking to learn 🙂 

For example: you can use it like this to match an element with id that begins with `foo` :

```yaml
- tapOn: 
  id: "foo.*"
```
