### ISSUE TITLE
[Maestro v1.34.0] assertVisible for Lottie in Compose is flaky / not succeeding as expected

### ISSUE THREAD

**Issue by sdfgsdfgd** [mobile-dev-inc/maestro#1568]
**Describe the bug**

**To Reproduce**
```
@Preview
@Composable
fun SplashScreenP() {
    SomeTheme {
        SplashScreen(
            modifier = Modifier
                .width(720.dp)
                .height(1280.dp)
                .background(
                    color = Color.DarkGray,
                ),
            stateFlow = MutableStateFlow(AnimationState.Open),
            onOpeningCompleted = {},
            onClosingCompleted = {},
        )
    }
}

@Composable
fun SplashScreen(
    modifier: Modifier = Modifier,
    stateFlow: StateFlow<AnimationState>,
    onOpeningCompleted: @Composable () -> Unit,
    onClosingCompleted: @Composable () -> Unit,
) {
    val animationState by stateFlow.collectAsState()
    val isOpeningVisible = if (animationState is AnimationState.Open) {
        1f
    } else {
        0f
    }
    val isClosingVisible = if (animationState is AnimationState.Close) {
        1f
    } else {
        0f
    }


    Box(modifier = modifier) {
        SplashAnimation(
            modifier = Modifier
                .alpha(isOpeningVisible)
                .testTag("SplashScreen_OpenAnimation"),
            animationRes = R.raw.splash_opening_animation,
            isPlaying = animationState is AnimationState.Open,
            onCompleted = {
                onOpeningCompleted()
                Log.d("XXX", "opening animation completed")
            },
        )
        SplashAnimation(
            modifier = Modifier
                .alpha(isClosingVisible)
                .testTag("SplashScreen_CloseAnimation"),
            animationRes = R.raw.splash_closing_animation,
            isPlaying = animationState is AnimationState.Close,
            onCompleted = {
                onClosingCompleted()
            },
        )
    }
}

@Composable
private fun SplashAnimation(
    modifier: Modifier = Modifier,
    isPlaying: Boolean,
    @RawRes animationRes: Int,
    onCompleted: @Composable () -> Unit,
) {
    val composition by rememberLottieComposition(LottieCompositionSpec.RawRes(animationRes))

    val lottieState = animateLottieCompositionAsState(
        composition,
        iterations = 1,
        isPlaying = isPlaying,
        restartOnPlay = false,
    )

    LottieAnimation(
        modifier = modifier,
        composition = composition,
        progress = { lottieState.progress },
    )

    if (lottieState.progress >= 1f) {
        onCompleted()
    }
}
```

1. Start the simulator
2. Run `maestro test ...`
content of simple test:
``` 
appId: ${APP_ID}
---
- clearState
- launchApp
- openLink: "app://my.app.com/splash"
- assertVisible:
    id: "splash_closing_animation"
- runFlow: subflow/login.yaml
- runFlow: subflow/logoutLogin.yaml
```

3. The Flow fails at 
```
- assertVisible:
    id: "splash_closing_animation"
```

**Expected behavior**
the lottieanimation view with the ID is clearly there, but it's failing for me ? the exact same setup, with same emulator version and same codebase is not failing for someone else though. 
What could be behind this behaviour ? 

All the other test flows are successful in my case, except for this one, which is failing for me, but not failing for my friend.

- Maestro version.  1.34.0      (I tried downgrading to many other versions, ran on 1.21.3 as well)
- Platform: [Android 11.0 API30]
- Framework: [Native Android]
- Device model and OS version: [Emulator/virtual arm64 device, running on OSX 14.1]
- Host [Macbook Pro M2]

**Bugreport output (if applicable)**
[2023-11-02_123524.zip](https://github.com/mobile-dev-inc/maestro/files/13233285/2023-11-02_123524.zip)
[2023-11-02_123627.zip](https://github.com/mobile-dev-inc/maestro/files/13233286/2023-11-02_123627.zip)
[2023-11-02_123845.zip](https://github.com/mobile-dev-inc/maestro/files/13233287/2023-11-02_123845.zip)
[2023-11-02_123847.zip](https://github.com/mobile-dev-inc/maestro/files/13233288/2023-11-02_123847.zip)
[2023-11-02_123855.zip](https://github.com/mobile-dev-inc/maestro/files/13233289/2023-11-02_123855.zip)
[2023-11-02_124955.zip](https://github.com/mobile-dev-inc/maestro/files/13233290/2023-11-02_124955.zip)

**Comment by axelniklasson** [comment]
Could you share a run on Maestro Cloud or your app binary and workspace with me and I can take a look? When you run `maestro studio`, what does it say for this element that you're trying to assert visible? Does it find the id?
