### ISSUE TITLE
Unique error when trying to run tests or studio

### ISSUE THREAD

**Issue by ShaneNoonan** [mobile-dev-inc/maestro#1574]
I keep getting the error - "java.lang.IndexOutOfBoundsException: Index: 1, Size: 1" , when trying to run any of my tests or maestro studio. When I look in the logs it says "cli.session.MaestroSessionManager - Failed to record heartbeat" any idea how to resolve this issue ? Im on the latest maestro version and running on emulator and windows wsl 

Java version : openjdk version "11.0.18" 2023-01-17
Adb version : Version 34.0.0-9570255

<img width="649" alt="maestro error2" src="https://github.com/mobile-dev-inc/maestro/assets/22483886/a1f5d346-69ca-46ff-935f-1077f101c9d9">
<img width="854" alt="maestro error1" src="https://github.com/mobile-dev-inc/maestro/assets/22483886/f90a173d-4f74-4964-a6dc-0fdb520a10a6">

**Comment by JRWilding** [comment]
Exact same stack trace, slightly newer versions of openjdk 11.0.19 and adb 34.0.3

**Comment by JRWilding** [comment]
I deleted the sessions file in ~/.maestro (in the linux file system) and seems to fix things

**Comment by FabioRocha462** [comment]
deu certo para mim
