### ISSUE TITLE
[Maestro Cloud 1.3.2 / Bitrise]: Unknown option: '--device-locale'

### ISSUE THREAD

**Issue by wonderlul** [mobile-dev-inc/maestro#1584]
**Describe the bug**
Can't specify custom locale.

**To Reproduce**
![Screenshot 2023-11-10 at 13 12 28](https://github.com/mobile-dev-inc/maestro/assets/56554355/f19a3948-dd7a-468b-a815-d600f8e90aef)

Enter "pl_PL" as Device locale in Bitrise "Upload to Maestro Cloud" step.

**Expected behavior**
Services recognise device locale. 

**Screenshots**
![Screenshot 2023-11-10 at 13 13 43](https://github.com/mobile-dev-inc/maestro/assets/56554355/6b66df7c-e1bc-46f6-9f1f-30c8fd6ef330)

**Environment information (please complete the following information):**

- Maestro version [Maestro Cloud 1.3.2]
- Platform: [Bitrise]
- Framework: [React Native]
- Device model and OS version: Default
- Host [Xcode 14.3.x on macOS 13.2 Ventura]

**Additional context**
If additional information is needed please tell. Also I don't know if this issue should land here or Bitrise GitHub. If it shouldn't be here, please close.

**Comment by axelniklasson** [comment]
@wonderlul this has since been released to Maestro Cloud so this should now work for you -- let us know if you have any issues!
