### ISSUE TITLE
Command to scroll horizontally

### ISSUE THREAD

**Issue by ragunathjawahar** [mobile-dev-inc/maestro#159]
The existing scroll command supports vertical scrolling, do we need to parameterise this command/use the `SwipeCommand` to imitate horizontal scrolling?

**Comment by Colorofbest** [comment]
Hello,
You can use the swipe command : https://maestro.mobile.dev/reference/scroll-and-swipe

> \- swipe:                 # This command swipes from point (x:100, y:500) to point (x: 300, y:500). Units are in pixels  
>      start: 100, 500
>      end: 300, 500`

Or, what you ask for, is a simpler command "swipe" without parameter, like scroll ?

(but it could be nice to specify direction, "scroll down", "scroll up", "swipe left", "swipe right")

**Comment by dmitry-zaitsev** [comment]
Agree that having a DSL-like command for swiping makes sense

**Comment by ghasemdev** [comment]
> Agree that having a DSL-like command for swiping makes sense

Some other gestures we need :
onDoubleTap
dragging
zoomIn/Out

**Comment by dmitry-zaitsev** [comment]
It is now possible to swipe left and right: https://maestro.mobile.dev/reference/scroll-and-swipe
