### ISSUE TITLE
[Feature Request] Improve Cloud Console with Statistics and Reporting

### ISSUE THREAD

**Issue by clmoore28** [mobile-dev-inc/maestro#1591]
**Describe the solution you'd like**
Currently the Maestro Cloud Console for uploads is pretty basic. All we as users have is the ability to do some simple filtering. 

We would love the ability to be able to see some statistics at-a-glance, such as pass/fail % rate by month/day/app etc, or even something as small as the time it's taken to run all of the tests. Maybe with some more granular reporting abilities, like seeing which tests are the most prone to failure. This would really help us to identify if our tests are flaky and need more work, as well as demonstrating to our stakeholders the kind of value our tests are giving to the company.

If this is something that would take a long while to implement, then just allowing us to export bulk data as xml/csv from the Console would be great too, as we could import this into our own dashboards and monitoring.

**Comment by bartekpacia** [comment]
Hey, thanks for sharing your ideas and thoughts with us.

We do not have any plans to build this right now, unfortunately.
