### ISSUE TITLE
[v1.34.1] Process crashes when custom toast is shown - java.io.IOException: Command failed (tcp:7001): closed

### ISSUE THREAD

**Issue by jaychang0917** [mobile-dev-inc/maestro#1618]
**Describe the bug**
The process crashes after Android toast is shown.  **Only happens for custom toast(i.e. with custom view)**
```
Exception in thread "pool-4-thread-1" java.io.IOException: Command failed (tcp:7001): closed
	at dadb.adbserver.AdbServer.send$dadb(AdbServer.kt:99)
	at dadb.adbserver.AdbServerDadb.open(AdbServer.kt:138)
	at dadb.forwarding.TcpForwarder.handleForwarding$lambda-1(TcpForwarder.kt:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
when the `-tapOn: Show toast` command is executed (i.e. a Android toast is shown), the whole process crashes.
```
name: Test toast
appId: com.myapp
---
- launchApp:
    clearState: true
- tapOn: Show toast
- tapOn: Next
```

**Expected behavior**
The flow runs without crash

**Screenshots**

**Environment information (please complete the following information):**

- Maestro version [v1.34.1]
- Platform: [Android 13]
- Framework: [Native Android]
- Device model and OS version: [vivo Y76 5G]
- Physical device
- Host [Mac M1]

**Comment by frichez** [comment]
I have the same error. Here is the error from logcat :

> FATAL EXCEPTION: main
> Process: dev.mobile.maestro, PID: 17831
> java.lang.NoSuchMethodError: No direct method <init>()V in class Landroid/view/accessibility/AccessibilityNodeInfo; or its super classes (declaration of 'android.view.accessibility.AccessibilityNodeInfo' appears in /system/framework/framework.jar!classes3.dex)
>     at dev.mobile.maestro.ToastAccessibilityListener.onAccessibilityEvent(ToastAccessibilityListener.kt:26)
> 
AccessibilityNodeInfo empty [constructor](https://developer.android.com/reference/android/view/accessibility/AccessibilityNodeInfo#AccessibilityNodeInfo()) added in api level 30 and my device is running api level 29.

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue! Unfortunately, it's not reproducible to us.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

This issue does not contain such an example, therefore I'm going to reluctantly close it.

If you don't have time right now, that's totally OK. Feel free to open a new issue in the future with all the required information provided.

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
