### ISSUE TITLE
[Feature Request] Show flow results over time

### ISSUE THREAD

**Issue by chriswiesner** [mobile-dev-inc/maestro#1626]
**Is your feature request related to a problem? Please describe.**

It would be quite useful to see test results for the different flows over time.
Imagine you have a flaky test flow and you want to know it's last 10 results. For that you'd need to scan all uploads and look for that specific test flow.

**Describe the solution you'd like**

Show flow results in a matrix

| Flow | Today (upload X) | Yesterday (upload Y) | 14/12 (upload Z) | 13/12 (upload A)
|--------|--------|--------|--------|---|
| Onboarding | ✅ | ❌ | ❌ | ✅
| Sign-up | ✅ | ✅ | ✅ | ✅
| Notifications | ❌ | ❌ | ❌ | ❌

**Comment by bartekpacia** [comment]
Thanks for the idea. For now, we do not have plans to implement this, sorry.

Related: #1591
