### ISSUE TITLE
[Question] Does it works for apple watch devices?

### ISSUE THREAD

**Issue by jhonatan-3a** [mobile-dev-inc/maestro#1628]

**Comment by bartekpacia** [comment]
[Apple's XCUITest supports watchOS](https://developer.apple.com/documentation/xctest/xcuidevice), so in principle, it should be possible. But the demand for this feature seems to be quite low, and there's not much prior art. If someone would like to work on getting this supported in Maestro (and then commit to maintaining it) we're always happy to accept contributions.

For reference, here's Appium issue tracking this: https://github.com/appium/appium/issues/4829

**Comment by bartekpacia** [comment]
Since this issue is a question and not a request, I'll consider it answered and close it.
