### ISSUE TITLE
Android tapOn with id doesnt work

### ISSUE THREAD

**Issue by adechanterac** [mobile-dev-inc/maestro#163]
Hello, 

I tried maestro tool recently and i faced several issues with tapOn command.

If i try to tapOn button (with no text but image) given an id (element in a fragment), maestro don't find it.
If i replace image in this button with a text, it does.

Same issue with TapOn in a recyclerview, if i have several elements with the same content (using tapOn text and index), it doesn't work.

**Comment by dmitry-zaitsev** [comment]
Could you share your `yaml` test file? I would like to see how you are using the `tapOn` command

**Comment by adechanterac** [comment]
The view is a button with no text but and image. I simply use it this way :

```
appId: com.example.myapp
---
- launchApp
- tapOn:
    id: "country_selection_button"
```

If i set no image to it and set a text and use : 

```
- tapOn:
    text: "test"
```
  it works well but this is not what i want to test

**Comment by dmitry-zaitsev** [comment]
Note that `id` should be a full qualified name of the id resource OR a regex as seen in `maestro hierarcht`, so you are missing a part of it.

A quick fix would be to use this

```
- tapOn:
     id: ".*country_selection_button"
```
