### ISSUE TITLE
Getting an error when using the textInput 

### ISSUE THREAD

**Issue by Kristijan-Karanfiloski** [mobile-dev-inc/maestro#1631]
Hi I need some help i just downloaded Maestro, and I want to use It on a project for now I used a simple test to start the app and tapped on some buttons but the problem appears when using the textInput command i get this error 
 ║                                                                              
 ║  > Flow                                                                      
 ║                                                                              
 ║    ✅  Launch app "com.next11.app"                                            
 ║    ✅  Tap on "Already have an account?"                                      
 ║    ✅  Tap on "Email"                                                         
 ║    ✅  Tap on "Go to Activation Page"                                         
 ║    ✅  Tap on "Activation code here"
 ║    ⏳  Input text random NUMBER
 ║
ℹ️ Retrying connection to the XCUITest server for 1...
Error: ⚠️ Error: An unknown network error occurred while communicating with the XCUITest server. If the issue persists, consider raising a GitHub issue with the error message and any available logs for further assistance.
I noticed that for now, it happens only when I tap on input and try to input some text but the weirdest thing is that I tried the same taste on a different mac and it's working the test is passing

**Comment by bartekpacia** [comment]
Hey, thanks y'all for creating this issue - unfortunately, it's not easily reproducible. We have a huge backlog, so it's important we can triage issues in an efficient manner.

Therefore I'm going to close it for now. Please, feel free to open a new issue in the future with step-by-step repro attached.
