### ISSUE TITLE
unable to populate textfield with information [v1.34.1]

### ISSUE THREAD

**Issue by rebekah-oj** [mobile-dev-inc/maestro#1640]
**Describe the bug**.

while attempting to populate textfields using inputText command, the text field is not getting populated with the complete text that was specified in the test. i.e i tried to login using email address and password on my application , the email address was not completely typed out despite all attempts, i went as far as using the shortest email address i had access to but even that did not work.

**To Reproduce**

1. Start the simulator
2. Input text into a textfield i.e enter email address into email field
3. Run `maestro test  login.yaml`
4. The Flow fails at type email address

**Expected behavior**
the entire text in this case , the email address that was specified in the test should be completely populated in the text field. no numbers or letters should be omitted

**Screenshots**

<img width="1792" alt="Screenshot 2024-01-02 at 10 16 02 AM" src="https://github.com/mobile-dev-inc/maestro/assets/47415296/d90e008f-cfa0-4724-8ed6-fd55b646af07">

**Environment information (please complete the following information):**

- Maestro version [v1.34.1]
- Platform: [Android 11.0, Chrome]
- Framework: [Flutter]
- Device model and OS version: [e.g. Nexus 6P]
- emulator
- Host [Mac M1]

**Additional context**
this issue is applicable to all input attempts

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue! Unfortunately, it's not reproducible to us.

Please provide [a minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
