### ISSUE TITLE
[v1.34.1] - Maestro Cloud - Code 0x8badf00d error - Flow fails on Maestro Cloud even though tests steps are passing 

### ISSUE THREAD

**Issue by marounmelhem** [mobile-dev-inc/maestro#1642]
**Describe the bug**
We're facing a weird bug on Maestro Cloud where steps pass in a particular test but the actual flow fails withe this error:
```
Namespace FRONTBOARD, Code 0x8badf00d
```

Here's [an example upload](https://console.mobile.dev/uploads/2af78d1a-9c11-451f-85aa-16faa91efb13?teamId=f29e32be-305e-4e67-ace1-6bbcbe1577b8&appId=ed0833f6-2dce-4cf7-ba46-5df62af550ac&analysisId=a10b2b21-6707-43ca-880a-7a5385312b73&checkIdx=0).

**To Reproduce**
- Happens randomly on Maestro Cloud on specific tests (also when restarting the tests in question)

**Expected behavior**
The flow should pass on Maestro Cloud because all test steps are passing

**Screenshots**
<img width="1145" alt="Screenshot 2024-01-04 at 12 51 40 PM" src="https://github.com/mobile-dev-inc/maestro/assets/10087168/32d4ae16-2565-4787-acda-4a643ba5f11c">

**Environment information (please complete the following information):**

- Maestro version [v1.34.1]
- Platform: Maestro Cloud
- Framework: React Native
- Device model and OS version: [iPhone11]
- Simulator, emulator or physical device: Maestro Cloud Simulator
- Host [e.g. Mac M1, Windows, Linux, etc]

**Workspace (if applicable)**
Please share your workspace with Flow files and application binary if you are able to do so as that greatly helps in reproduction efforts.

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

**Additional context**

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue - unfortunately, it's not easily reproducible. We have a huge backlog, so it's important we can triage issues in an efficient manner.

I'll close this for the time being. If you encounter it again (and have the YAML test and APK to share), please create a new issue and we'd be happy to run it repeatedly to try to reproduce the issue.
