### ISSUE TITLE
Allow backend to be run alongside with simulator/emulator app

### ISSUE THREAD

**Issue by VilleMiekkoja** [mobile-dev-inc/maestro#1652]
**Is your feature request related to a problem? Please describe.**
In CI pipeline we would wish to run e2e simulator tests before we merge the PR. For this we need to able to run the backend locally in maestro, alongside with the simulator app. If I have understood correct, this is not currently possible? I would imagine this is a common need for applications. Other option would be to create a separate public environment for the PR code, but it's harder to do and more expensive. We would need the environment only for the duration of the tests, and we would then need to create a separate public environment for each PR and also maybe for each commit if we wish to test each commit.

**Describe the solution you'd like**
Solution would be that maestro cloud would allow running local backend along the side of the simulator/emulator app.

**Describe alternatives you've considered**
Described them in the first section already

**Additional context**
We are running pipeline in bitbucket. We can't run the backend there since we can't get a public IP address for it that an app in maestro cloud could access to.

**Comment by bartekpacia** [comment]
This would be a huge undertaking that we unfortunately do not have plans to do.

We recommend having a staging env that is exposed to the public web just like prod.
