### ISSUE TITLE
[Maestro version, v1.35.0]slower execution speed than appium

### ISSUE THREAD

**Issue by shishangx** [mobile-dev-inc/maestro#1653]
**Describe the bug**
same device, but slower execution speed than appium

**To Reproduce**
You can use any app to test it. In actual testing, for example, the response time of Appium is in the hundreds of milliseconds, while Maestro is in 1-2 seconds.

**Expected behavior**
Cannot be significantly slower than appium

**Screenshots**

**Environment information (please complete the following information):**

- Maestro version [v1.35.0]
- Platform: [iOS 16.2 simulator, Android 12]
- Framework: [React Native]
- Device model and OS version: [iphone simulator, Pixel3XL]

**Comment by felipevolpone** [comment]
Maestro implementation is very different from Appium so doesn't make sense to compare them
