### ISSUE TITLE
[Maestro 1.35.0] "Flow file does not exist" on the cloud

### ISSUE THREAD

**Issue by bchow68** [mobile-dev-inc/maestro#1658]
**Describe the bug**
When I run my tests (flows) locally no problem. All flows run to completion. However, when I run my flows on the cloud I get the error, "Flow file does not exist".

As I'm evaluating Maestro it'd be great if we can get this to work.

**To Reproduce**
1. Start the simulator for iPhone 11, iOS 16.2
2. Run ` maestro cloud -e MODEL_OS=iphone11_ios16.2 --app-file=/Users/admin/Library/Developer/Xcode/DerivedData/FotoNotes-gdvlinqkxrimnleeioihcsasecfp/Build/Products/Debug-iphonesimulator/SiteCapture.app --flows=tests/`

**Actual behavior**
Upload request failed (400): Syntax error: Failed to parse file: /./login/login-02.yml
Flow file does not exist: jar:file:///tmpFiles/workspaces/workflow3431492392982014347.zip!/./login/../../common/launch_app.yml

**Expected behavior**
The cloud should run the test flows I uploaded.

**Screenshots**
<img width="887" alt="image" src="https://github.com/mobile-dev-inc/maestro/assets/108538982/21cb687c-5f03-4c47-a742-fbdc544d9cf2">

Screen recording: https://www.loom.com/share/e2330ae65d9f42b0a5f672a50afe3020?sid=32811858-ccb1-479c-9e68-12f1689c6aa9

**Environment information (please complete the following information):**

- Maestro version 1.35.0
- Platform: iOS 16.2 
- Framework: Native iOS
- Device model and OS version: [e.g. iPhone6]
- Simulator: iPhone 11, iOS 16.2
- Host: Mac M1

**Workspace (if applicable)**
Please share your workspace with Flow files and application binary if you are able to do so as that greatly helps in reproduction efforts.
[sitecapture.zip](https://github.com/mobile-dev-inc/maestro/files/14044325/sitecapture.zip)

**Bugreport output (if applicable)**
The zip files created when `maestro bugreport` can be uploaded here as well if applicable.

**Additional context**

**Comment by bchow68** [comment]
This issue is resolved.

**Comment by Hosam-hsm** [comment]
@bchow68 Could you please explain how was this solved?

**Comment by bchow68** [comment]
@Hosam-hsm You can read about it in Slack. https://mobile-dev-inc.slack.com/archives/C05EVEUTKRP/p1705868719729869

**Comment by 4gus71n** [comment]
@bchow68 @Hosam-hsm having the exact same issue with Android, would you mind sharing how you guys fixed it?
