### ISSUE TITLE
[Feature Request] I would like to run a test using multiple binaries

### ISSUE THREAD

**Issue by tian000** [mobile-dev-inc/maestro#1661]
**Is your feature request related to a problem? Please describe.**
I want to test deep links with my app, from another app. So I would like to be able to upload both apps and run a flow on the interactions between the two apps.

openLink is helpful but it does not allow me to fully test the interaction between apps.

**Describe the solution you'd like**
Maestro cloud should accept multiple binaries in a zip file.

**Comment by radomir-sebek** [comment]
+1
