### ISSUE TITLE
Feature: Capture Screenshots and Send to Jira Xray

### ISSUE THREAD

**Issue by camilohenaonavarro** [mobile-dev-inc/maestro#1664]
## Description

Currently, our automated testing project lacks the ability to capture screenshots and automatically send them to Jira Xray. To enhance visibility and efficiency in our tests, I propose the implementation of this feature.

## Feature Details

The new functionality should allow:

- Capture screenshots during automated test execution.
- Integrate the capability to automatically send these screenshots to Jira Xray for easy reference.

## Objectives

1. Improve visual documentation of test executions.
2. Facilitate issue identification and resolution through screenshots.
3. Efficiently integrate with Jira Xray for centralized test result management.

## Suggested Tasks

- [ ] Research best practices for capturing screenshots during automated test execution.
- [ ] Implement screenshot capture functionality.
- [ ] Configure integration with the Jira Xray API for automatic screenshot submission.
- [ ] Update documentation to include instructions on using this new feature.

## Context

This enhancement is crucial for improving the quality and effectiveness of our automated tests, providing additional visual insights that can be invaluable for the development and testing teams.

**Comment by bartekpacia** [comment]
I don't see us providing an explicit integration with a 3rd party vendor like jira xray.

There's the [`takeScreenshot`](https://maestro.mobile.dev/api-reference/commands/takescreenshot) command, and then you can upload screenshots to jira xray yourself. Would that solve your request?
