### ISSUE TITLE
inputText with text does not write proper text

### ISSUE THREAD

**Issue by adechanterac** [mobile-dev-inc/maestro#167]
It happens frequently that inputText does not write the good text and leads to a failed flow

`inputText: "France"` often write `Farnce` on my case

**Comment by dmitry-zaitsev** [comment]
@adechanterac what Maestro version are you using?

**Comment by adechanterac** [comment]
I use the `v1.5.0`

**Comment by dmitry-zaitsev** [comment]
Assuming it is iOS?

**Comment by adechanterac** [comment]
no it is android

**Comment by dmitry-zaitsev** [comment]
We believe this should be fixed in 1.8.0

**Comment by attilapolgar** [comment]
I'm experience the same with `v1.13.2` on Android emulator (e.g. Pixel 4 API 31).

a config like like

```
- inputText: "lorem ipsum"
```

sometimes (often) results missing or even reversed characters

![image](https://user-images.githubusercontent.com/3582918/201686918-feb2a320-dc4c-4af8-84b6-d8befb64ee71.png)
