### ISSUE TITLE
[v1.35.0][Flutter] Unable to detect Button Widget "enabled" state

### ISSUE THREAD

**Issue by hakoniemi** [mobile-dev-inc/maestro#1675]
**Describe the bug**
Maestro is unable to detect whether MaterialButton (e.g. TextButton) is enabled or disabled. This may be related to that [enabled](https://api.flutter.dev/flutter/material/ButtonStyleButton/enabled.html) property seems to be deprecated as a property. Current state is based on whether `onPressed` value is *null* or not.

**To Reproduce**
1. Create a `TextButton` widget
2. append `onPressed` as null
3. apply Semantics label or Text to make it accessible
4. Write a Maestro flow with:
```
- assertNotVisible:
    text: .*Reference.*
    enabled: true
```
(or the opposite with `assertVisible` and `enabled: false`)

**Expected behavior**
Maestro should detect the actual state based on value of `onPressed` instead of deprecated `enabled` property

**Environment information:**

- Maestro version: v1.35.0
- Platform: iOS 17.0
- Framework: Flutter
- Device model and OS version: iPhone SE 3rd (Simulator)

**Comment by bartekpacia** [comment]
Hi @hakoniemi, thanks for the issue!

`ButtonStyleButton.enabled` is simply a getter with the following implementation:

```dart
bool get enabled => onPressed != null || onLongPress != null;
```

In general in Flutter, the button is considered to be disabled when there's no click handler associated with it (i.e. `onPressed`/`onLongPressed` is null).

> **Expected behavior**
>
> Maestro should detect the actual state based on value of `onPressed` instead of deprecated `enabled` property.

Maestro doesn't know anything about Flutter, it works by querying the app's accessibility hierarchy. So if you think that something is wrong, I think you should report an issue to Flutter first.

Does this help with your problem in any way?
