### ISSUE TITLE
[Feature Request] Report Portal Integration

### ISSUE THREAD

**Issue by CamBowes** [mobile-dev-inc/maestro#1676]
Hi,
I was wondering if Maestro could be integrated with [ReportPortal](https://reportportal.io/) as we use this as our test report aggregator.

This would hopefully report back test summary, errors and screenshot/videos.

**Comment by bartekpacia** [comment]
Hey Cam, would you be up to share what exactly you'd like to see us providing? And also explain your use case a bit.

Maestro can output results in Junit format, which I guess can they be uploaded to ReportPortal, assuming they expose some API of sorts for doing that.

**Comment by CamBowes** [comment]
I think ReportPortal has an API that allows JUnit format reports to be uploaded, https://reportportal.io/docs/log-data-in-reportportal/ImportDataToReportPortal/

Thanks for getting back to me!

**Comment by bartekpacia** [comment]
I see, thanks @CamBowes. So if they have an API can't you upload it yourself? I am not sure what Maestro could do here (feel free to clarify!)
