### ISSUE TITLE
[1.36.0] Unable to click on a button in a card, if the button is the only clickable element in that card (Flutter)

### ISSUE THREAD

**Issue by mregnauld** [mobile-dev-inc/maestro#1691]
**Describe the bug**
When I run my Flutter app on an Android device, Maestro does not recognize a button inside a card. It only sees the whole card.
That being said, if I add another clickable element inside that card, everything works as expected, Maestro is now able to see and interact with the button.

**To Reproduce**
Steps to reproduce the behavior, e.g.:

1. Create a Flutter app with the following content:
```Dart
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Card(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Text("Introduction text"),
            SizedBox(height: 24),
            Material(
              type: MaterialType.transparency,
              child: InkWell(
                onTap: () => print("PRESSED"),
                child: Text("PRESS"),
              ),
            )
          ],
        ),
      ),
    );
  }
```
2. Run `maestro studio`
3. Run the app
4. Maestro studio only sees the whole card, and not the `PRESS` button

**Expected behavior**
Maestro should be able to see and interact with the button inside the card, even though the button is the only clickable element in that card.

**Environment information**

- Maestro version: 1.36.0
- Platform: Android 12
- Framework: Flutter
- Device model and OS version: Samsung Galaxy M51 (One UI 4.1)
- Physical device
- Host: Macbook Air M1

**Workspace**
Android Studio Giraffe | 2022.3.1 Patch 1

**Comment by mregnauld** [comment]
For those of you who are interested, I found a workaround for this issue by using the `Semantics` widget as described below:

```Dart
Semantics(
  container: true,
  child: Material(
    type: MaterialType.transparency,
    child: InkWell(
      onTap: () => print("PRESSED"),
      child: Text("PRESS"),
    ),
  ),
),
```

I still let the issue open, in case there is still a bug to fix.

**Comment by bartekpacia** [comment]
Hi @mregnauld - this is Flutter's default behavior. Maestro only pulls semantics that Flutter creates. It would work the same way in Appium etc.

Your workaround with `Semantics(container: true)` is a good one.

**Comment by mregnauld** [comment]
OK thanks!
