### ISSUE TITLE
Question - I can't seems to find a way to use basic 'Auth' (Username/Password) whilst making Get call, do we have a smiliar method?

### ISSUE THREAD

**Issue by Abhishek21sharma** [mobile-dev-inc/maestro#1693]
I can see an example to add Auth : BearerToken in when making Http GET Request like below, However finding difficult to understand how to add 'Auth'(UserName/Password). 
Do you've an example for this please ?

Following one is from Maestro guide: 

const response = http.get('https://example.com', {
    headers: {
        Authorization: 'Bearer MyToken'
    }
})

**Comment by bchow68** [comment]
Example of basic auth:

'Authorization': Basic <base64_encoded_string> 

where base64 encoded string represents your credentials in the format, "username:password".

**Comment by bartekpacia** [comment]
Thank you @bchow68 :)
