### ISSUE TITLE
Cannot use pickers - hierarchy does not see it on iOS

### ISSUE THREAD

**Issue by KonradTkaczyk** [mobile-dev-inc/maestro#170]
Currently I was not able to control picker to select digits. Picker is visible on the screen of simulator but hierarchy view does not see it.

**Comment by dmitry-zaitsev** [comment]
Could you please share:

- Screenshot of your app
- Output of `maestro hierarchy` command
- Output of `idb ui describe-all` command

**Comment by Leland-Takamine** [comment]
@KonradTkaczyk This should be resolved with the new iOS driver (available on latest Maestro version). Please re-open if you are still seeing this issue after upgading!
