### ISSUE TITLE
Erro na pasta .Maestro e no AddMedia no Git Action

### ISSUE THREAD

**Issue by rjolima** [mobile-dev-inc/maestro#1702]
Pra subir para GIT Action a pasta .maestro é solicitada : https://console.mobile.dev/quickstart?teamId=f2d3614b-e7b5-4889-a55c-69edb6b2b7ac
![image](https://github.com/mobile-dev-inc/maestro/assets/41792297/162fe907-95c3-40db-b05b-fee702199246)
no mestro Commands > addMedia pede pra colocar "./asserts/<nome da imagem>" só que aí começa da erro no git action
https://maestro.mobile.dev/api-reference/commands/addmedia
Mesmo adicionando mais um ponto no caminho, que funciona no teste manual e não funcionando no action do git
![image](https://github.com/mobile-dev-inc/maestro/assets/41792297/0ec63b89-7d4a-4e51-8399-b1b3baf94192)

**Comment by bartekpacia** [comment]
Hello, thanks for taking time to report an issue in our repo. If you rewrote it in English and made the problem more descriptive, then it'd be easier for us to help you.
