### ISSUE TITLE
[Maestro Cloud] Error is incorrect, and leaks Cloud internals (security)

### ISSUE THREAD

**Issue by Fishbowler** [mobile-dev-inc/maestro#1705]
I submitted a workspace via the Github Action. The response was 

```
Run mobile-dev-inc/action-maestro-cloud@v1.8.1
Uploading to Maestro Cloud

Error: Error running Maestro Cloud Upload Action: Request to https://api.mobile.dev/v2/upload failed (500): org.postgresql.util.PSQLException: ERROR: unsupported Unicode escape sequence
  Detail: \u0000 cannot be converted to text.
  Where: JSON data, line 1: ..."ext":{}}}},{"runScriptCommand":{"script":"\u0000... [statement:"INSERT INTO <<redacted>>
```

It turns out that one of the files in the workspace was a git-crypt encrypted file containing credentials that I'd forgotten to decrypt.

* This should be a 400-series error, not a 500
* This error message shouldn't expose the Maestro Cloud internals (database engine, table name, column names)

**Expected behavior**
HTTP/400 The workspace contains unparseable files

**Environment information (please complete the following information):**

- Flow with a `runScript` referencing a JS file
- JS file encrypted using `git-crypt`

**Workspace (if applicable)**

n/a - it never reached the console :(

**Comment by amanjeetsingh150** [comment]
@Fishbowler this should be fixed. Let me know if you something weird
