### ISSUE TITLE
[v1.36.0] video recording with command startRecording limited to 3 minutes

### ISSUE THREAD

**Issue by camoles** [mobile-dev-inc/maestro#1709]
**Describe the bug**
When you use the startRecording command to record a video, the recording ends at 3 minutes, even if the test lasted longer. Tested on a few api levels with android emulator running on a linux system.

**To Reproduce**

Run any flows that takes longer than 3 minutes, for example, make a flow that just repeats some action many times, and you will see that the recording is limited to 3 minutes even though the actual execution took longer.

**Expected behavior**

The recording should only be limited by disk space in the target directory where the recording is being written.

**Environment information (please complete the following information):**

- Maestro version [e.g. v1.36.0]
- Platform: Tested on Android emulator api levels 30, 33 and 34
- Framework: React Native
- Device model and OS version: Only tested on android emulator
- Host Linux

**Comment by 7maucdn** [comment]
I faced same issue

**Comment by bartekpacia** [comment]
This is resolved for Android API levels 34 and higher. See PR #1683

Unfortunately this is a platform limitation and hard to fix for lower API levels, so we don't plan on addressing that.
