### ISSUE TITLE
[Maestro 1.36.0] console.log statements not output to terminal from runScript commands within flows

### ISSUE THREAD

**Issue by mattrlong** [mobile-dev-inc/maestro#1710]
**Describe the bug**
When executing JavaScript files before a flow is executed, the log statements appear as expected in the terminal, ie: 

```
appId: ${APP_ID}
---
- runScript:
    file: ./script.js

- runFlow: "myFlow.yaml" 
```

However, if the same file is executed within the flow, ie if myFlow.yaml above were to contain: 
```
appId: ${APP_ID}

---

- launchApp:
    clearState: true
- runScript: 
    file: ./script.js
```
Any log statements within the scripts do not appear in the terminal. 

**To Reproduce**
Create script.js with below, and replicate using the two options for executing the script above: 
```
// script.js

const myVar = 'foo';
console.log(myVar); // outputs 'foo'
console.log(`myVar is ${myVar}`) // outputs 'myVar is foo'
```
**Expected behavior**
console.log output to always appear in the terminal when running flow for debugging purposes. 

**Screenshots**
An example of the difference in output can be seen below, where the script.js is executed once before the flow (with output), and the second during a flow execution: 
![image](https://github.com/mobile-dev-inc/maestro/assets/8707115/dd9c9845-af82-401c-b13d-37392c12e34f)

**Environment information (please complete the following information):**

- Maestro version v1.36.0
- Platform: Android 14
- Framework: Native Android
- Device model and OS version: Pixel3a
- Emulator
- Host Mac M1
- RhinoJS runtime

**Comment by bartekpacia** [comment]
Hey, thanks for the issue. I wasn't able to reproduce it. Here's my workspace:

[workspace.zip](https://github.com/user-attachments/files/16736938/workspace.zip)

I run the flow with `maestro test maestro_issue_1710/flow.yaml`

Tested on Maestro v1.37.9, both Android and iOS.

**Comment by bartekpacia** [comment]
Please consider creating new issue and make sure it's reproducible.
