### ISSUE TITLE
[Feature Request]any plan for web driver

### ISSUE THREAD

**Issue by chenshuichao** [mobile-dev-inc/maestro#1711]
**Is your feature request related to a problem? Please describe.**
The web driver is great feature.So is there any plan for web driver
**Describe the solution you'd like**
full support of web driver in maestro studio

**Comment by ericmasiello** [comment]
I'd also love to use Maestro to run web apps in Safari on simulator. Today, testing complex touch move interactions on realistic environments is under served by the existing web app testing frameworks (cypress, playwright)

**Comment by bartekpacia** [comment]
Hey, thanks for your interest in Maestro Web Driver. It's an experimental feature and we do not actively develop it, but we are more than happy to accept outside contributions for it!
