### ISSUE TITLE
not able to click on continue button 

### ISSUE THREAD

**Issue by bhagyanotion** [mobile-dev-inc/maestro#1731]
Hi team .I am trying to run maestro on my application but still at login flow .I am able to enter the email and password but unable to click on continue button .Can someone help with this ?

**Comment by shrestha-rupesh** [comment]
Use`maestro studio` and find out the value of the `Continue` button.

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue! Unfortunately, it's not reproducible to us.

Please provide [a minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

This issue does not contain such an example, therefore I'm going to reluctantly close it.

If you don't have time right now, that's totally OK. Feel free to open a new issue in the future with all the required information provided.

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
