### ISSUE TITLE
[1.36][studio] Copy button not considering special space character `NBSP`

### ISSUE THREAD

**Issue by mugbug** [mobile-dev-inc/maestro#1737]
**Describe the bug**

I'm having an issue with `maestro studio`'s copy command feature.

We use some language currency formatters to format a double value, for instance, into a currency string like `R$ 10.000,00`. The thing with those formatters is that they don't use a normal space character between the `R$` and the `10.000,00`. They use this following character: ` ` which is usually rendered as a space, but when maestro compares it with a normal space it doesn't match the string.

In my IDE this characters renders as follows: 

<img width="149" alt="image" src="https://github.com/mobile-dev-inc/maestro/assets/19307199/14ec9b42-4043-4f1b-b618-546ab49095d8">

Also, if I just tap the <img width="44" alt="image" src="https://github.com/mobile-dev-inc/maestro/assets/19307199/79f7771c-027e-4364-a50e-c5a7d6aa8192"> icon and `CMD+A` and `CMD+C`, I can copy the `NBSP` character as expected, so it's probably a parsing issue or something on the "copy to clipboard" feature <img width="43" alt="image" src="https://github.com/mobile-dev-inc/maestro/assets/19307199/e501f6f2-82b7-498b-9b23-9d8ae1d81c35">.

**Environment information (please complete the following information):**

- Maestro version [1.36]
- Platform: [Both]
- Framework: [Flutter]
- Device model and OS version: [iPhone 14 Pro - iOS 17.2]
- Simulator
- Host [Mac M1]

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue! Unfortunately, it's not reproducible to us.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

This issue does not contain such an example, therefore I'm going to reluctantly close it.

If you don't have time right now, that's totally OK. Feel free to open a new issue in the future with all the required information provided.

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
