### ISSUE TITLE
[v1.36.0] [Flutter] Scroll options are not working

### ISSUE THREAD

**Issue by shrijanRegmi** [mobile-dev-inc/maestro#1738]
**Describe the bug**
I have a settings screen that has a button on the bottom part. I tried `scrollUntilVisible` but it's just not scrolling. Other scroll options are also not working (`scroll` and `swipe`).

**To Reproduce**
1. Start android emulator,
2. Run maestro test command,
3. Wait for the test to reach the settings screen.

**Expected behavior**

After reaching to the settings screen, the screen should scroll until my button is visible.

**Environment information:**
- Maestro version [v1.36.0]
- Platform: [Android 11.0 - API 30]
- Framework: [Flutter]
- Device model and OS version: [e.g. Pixel 6 Pro]
- Emulator
- Host [Mac M2]

**Comment by bartekpacia** [comment]
Hey, thanks a lot for creating this issue - unfortunately, it's not easily reproducible. We have a huge backlog, so it's important we can triage issues in an efficient manner.

could you please provide [a minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers)?

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
