### ISSUE TITLE
Scroll não funciona quando é em um lugar específico

### ISSUE THREAD

**Issue by rjolima** [mobile-dev-inc/maestro#1743]
Não é possível usar scroll LEFT ou RIGHT quando fica em um ponto específico do aplicativo
It is not possible to use LEFT or RIGHT scrolling when located at a specific point in the application

![image](https://github.com/mobile-dev-inc/maestro/assets/41792297/28cde64e-8f87-4a79-bfb5-aa14e6225e1a)
![image](https://github.com/mobile-dev-inc/maestro/assets/41792297/7b079093-0322-49d2-9d88-adcdb9d60b01)

**Comment by bartekpacia** [comment]
this seems to be a very similar request to #1775

**Comment by bartekpacia** [comment]
closing as duplicate of #1775
