### ISSUE TITLE
Add support for Compose Multiplatform on iOS

### ISSUE THREAD

**Issue by Alaksion** [mobile-dev-inc/maestro#1746]
**Is your feature request related to a problem? Please describe.**
I'm working on an app with 6M+ users and we are planning to refactor our E2E tests to achieve better consistency and efficiency. The team found out about Maestro and the tool looks really promising: easy to use, understand and maintain.
Our app is written with compose Multiplatform and workflows are working as expected on the Android side, on the other hand, IOS integration is not working as we expected.

**Describe the solution you'd like**
It would be great if there was a way of interacting with the IOS app using finders based on displayed text or accessibility identifiers.  Right now it looks like this approach is not working.

**Additional context**
I have created a sample app to simulate the problem I'm having: [CMP Sample](https://github.com/Alaksion/CMP-Sample)

# Test environment
Maestro version: 1.36.0
Compose Multiplatform version: 1.6.2

Steps to reproduce:

1. Clone the repository
2. Install the IOS app in the simulator
3. Run the `sample.yaml` workflow inside the `maestro` folder.
4. Assert the workflow steps are passing but nothing actually happens in the simulator
5. Run the workflow on the android app and assert workflows are passing and emulator responds to maestro's actions

As you can see in the sample app repository I tried to force accessibility sync using `accessibilitySyncOptions = AccessibilitySyncOptions.Always(null)` and it worked partially. With this configuration maestro studio can identify the nodes but cannot interact with them.

**Comment by bartekpacia** [comment]
Hey @Alaksion, thanks for the report! We'll very busy rn but we'll definitely get to it.

I consider this to be a bug instead of feature request, since from what I know, [Compose supports accessibility on iOS since 1.6.0](https://blog.jetbrains.com/kotlin/2024/02/compose-multiplatform-1-6-0-release/#i-os-accessibility-support), and Maestro works by querying th accessibility tree, so it should work out of the box.

**Comment by bartekpacia** [comment]
I tried to reproduce it, but didn't succeed ([commit 38a8a](https://github.com/Alaksion/CMP-Sample/commit/38a8a981cbb46fcdcaac78840082ffea39ae8e9b)). The `sample.yaml` flow you shared fails, as is expected.

macOS Sonoma 14.5, Xcode 15.4, iOS 17.5 simulator. Please see attached video.

https://github.com/mobile-dev-inc/maestro/assets/40357511/562d6b55-2f21-40a9-bd86-125f96dfb9d3

**Comment by bartekpacia** [comment]
possibly related: #1271 1549
