### ISSUE TITLE
Add `direction` parameter to `scroll` command

### ISSUE THREAD

**Issue by LinusMuema** [mobile-dev-inc/maestro#1753]
**Is your feature request related to a problem? Please describe.**
In our application some, we have a dynamic topbar that disappears on scrolling upwards but appears again on any downwards scroll. Just like CoordinatorLayout.

**Describe the solution you'd like**
 It would be really great if we had options in the `scroll` command to specify the direction of the secoll and maybe orientation to support both horizontal and vertical scroll.

**Describe alternatives you've considered**
N/A

**Additional context**
- [CoordinatorLayout (xml)](https://blog.mindorks.com/using-coordinator-layout-in-android/)
- [Jetpack compose docs](https://developer.android.com/develop/ui/compose/components/app-bars#scroll)

**Comment by bartekpacia** [comment]
Hi @LinusMuema 👋 thanks for creating the issue

The request here is to have the [`scroll`](https://maestro.mobile.dev/api-reference/commands/scroll) command accept more parameters, similarly to what [`scrollUntilVisible`](https://maestro.mobile.dev/api-reference/commands/scrolluntilvisible) has, right? direction: DOWN

**Comment by LinusMuema** [comment]
Hi @bartekpacia 

Yes exactly. To specify the direction of scrolling.

**Comment by bartekpacia** [comment]
Understood. We're a small team that's very busy, but we'll do our best to get this done in the future.

Since this feature is already implemented for `scrollUntilVisible`, I'm also gonna add `good first issue` label and hope some good soul shows up!

**Comment by bartekpacia** [comment]
There's already [`swipe`](https://maestro.mobile.dev/api-reference/commands/swipe) command which seems to have what you're asking for. Does that resolve your issue?
