### ISSUE TITLE
[Maestro version, v1.36.0]web driver

### ISSUE THREAD

**Issue by chenshuichao** [mobile-dev-inc/maestro#1767]
<img width="1280" alt="Screen Shot 2024-06-15 at 15 17 40" src="https://github.com/mobile-dev-inc/maestro/assets/77186544/95c1270a-8110-4104-a909-765b16966d22">

we should make the device more like chrome, more width, more heigh,and the same the 1028*768

**Comment by bartekpacia** [comment]
Hi, could you clarify what's the problem here?

**Comment by chensce** [comment]
the web view is too small.
we should make the device more like chrome, more width, more heigh,and the same the 1028*768

**Comment by bartekpacia** [comment]
Thanks for creating this issue - unfortunately, it's not reproducible to us.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

This issue does not contain such an example, therefore I'm going to reluctantly close it.

If you don't have time right now, that's totally OK. Feel free to open a new issue in the future with all the required information provided.

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
