### ISSUE TITLE
[Maestro v1.36.0] Tapping on a specific point within another element not working

### ISSUE THREAD

**Issue by danielferromeral** [mobile-dev-inc/maestro#1779]
Based on the [documentation](Tapping on a specific point within another element), if I write something like this:
```
- tapOn:
    text: "A text with a hyperlink"
    point: "90%,50%
```
It should click in the word "hyperlink", but is not. For me, it clicks in the middle of the screen, a bit to the right, but the click is not relative to the text. It just ignore the text reference.

**To Reproduce**
1. Create a flow for a view where you have a text with a hyperlink that is not in the middle
2. Write a commando to tap in the hyperlink
3. Run the flow
4. The tapOn is not in the hyperlink, is in that coordinates of the screen

**Expected behavior**
It taps in the relative position of the element found. Also would like to be able to specify an ID and not only a text.

**Environment information (please complete the following information):**

- Maestro v1.36.0
- Platform: Android API 30
- Framework: Native Android
- Device model and OS version: Pixel 8 Pro
- Simulator, emulator or physical device
- Host MacBook Pro Sonoma 14.5

**Comment by JRWilding** [comment]
see #1421
