### ISSUE TITLE
Request - Release 1.37.0

### ISSUE THREAD

**Issue by AttieG** [mobile-dev-inc/maestro#1787]
@axelniklasson @amanjeetsingh150 
There has been several updates over the course of the past several months since February and I would like to request a new release.
Is this repo still maintained?

**Comment by amanjeetsingh150** [comment]
Hey we are planning the release in coming weeks. We have some features we would like to include and complete testing. Thank you for your patience! Stay tuned on the updates in maestro channel on slack.
