### ISSUE TITLE
Failed to parse file when using subflows with maestro cloud CLI

### ISSUE THREAD

**Issue by paulsweeting** [mobile-dev-inc/maestro#1790]
**Describe the bug**

Upload requests fail to maestro cloud when using the CLI if the test contains sub-flows:

```
- runFlow: subflows/onboarding-android.yaml
```

**To Reproduce**
Follow https://cloud.mobile.dev/getting-started/quickstart in login into CLI and download samples

1. Start the simulator/emulator
2. Run `maestro cloud sample.zip ios-advanced-flow.yaml` OR `maestro cloud sample.apk android-advanced-flow.yaml`
3. The Flow fails with error: 
```
Upload request failed (400): Syntax error: Failed to parse file: /./ios-advanced-flow.yaml
Flow file does not exist: jar:file:///tmpFiles/workspaces/workflow197377531878186231.zip!/./subflows/onboarding-ios.yaml
```
**Expected behaviour**
It works as expected with simple flows that do **NOT** contain subflow e.g. `maestro cloud sample.zip ios-flow.yaml` 

**Environment information (please complete the following information):**

Maestro version: 1.36.0
Platform: Android && iOS
Framework: cloud
Device model and OS version: N/A (cloud)
Host: Mac M3

**Comment by paulsweeting** [comment]
Duplicate of https://github.com/mobile-dev-inc/maestro/issues/1791 .. Closing. This issue was missing the 'Bug' label so I had to raise it again.

**Comment by bartekpacia** [comment]
Hey @paulsweeting, don't worry about the label! :) 

thanks for creating the bug!
