### ISSUE TITLE
[Feature Request] Assert specific image is visible in a ImageView

### ISSUE THREAD

**Issue by Sayum24** [mobile-dev-inc/maestro#1796]
**Is your feature request related to a problem? Please describe.**
I want to check whether a specific image is displayed in an imageView, because I have multiple images I'm setting for an ImageView at runtime.

**Describe the solution you'd like**
Check whether a certain xml-drawable/ png with its ID is visible on the screen with the assertVisible-Command.

**Describe alternatives you've considered**
maybe link media to the script which can be compared.

**Additional context**
I'm not 100% whether this feature already exists.

**Comment by bartekpacia** [comment]
Hi @Sayum24, thanks for creating the issue and welcome to Maestro community!

Do you have any idea on how could this be implemented?

**Comment by Sayum24** [comment]
Thanks for the fast reply @bartekpacia.
Currently I've got no idea...

Checking with an accessibility identifier could be a solution to my problem. Can you please share a link to the resource?

**Comment by bartekpacia** [comment]
What framework is your app built with?

**Comment by Sayum24** [comment]
Android, Kotlin

**Comment by Sayum24** [comment]
> Android, Kotlin

I just found out that I can handle it like displayed text.

Thanks for your help @bartekpacia !

**Comment by bartekpacia** [comment]
Happy to help! I'll the issue then:)
