### ISSUE TITLE
Allow variables in LaunchApp command

### ISSUE THREAD

**Issue by whlk** [mobile-dev-inc/maestro#181]
Sometimes the `appId` needs to be adjusted based on environment. For example if there are different build variants of the same app. Currently [injecting variables](https://maestro.mobile.dev/getting-started/maestro-cli#pass-variables-to-tests) is only available for a subset of commands (`TapOnElementCommand`, `AssertCommand`, `InputTextCommand` and `OpenLinkCommand`). 

I propose to also allow injecting environment variables into the `LaunchAppCommand`.

**Comment by dmitry-zaitsev** [comment]
This is now a part of 1.7.1. Credit goes to @whlk 👍
