### ISSUE TITLE
Make "assertVisible" find part of a text

### ISSUE THREAD

**Issue by K0n2t1** [mobile-dev-inc/maestro#1820]
**Is your feature request related to a problem? Please describe.**
In my React Native application the test should open an article and check it's content being visible afterwards. I can't make it work yet, since it seems to only succeed when the string of assertVisible is the complete content of a screen element.

**Describe the solution you'd like**
My understanding of something being visible is fullfilled, if it is visible as part of a bigger text:

assertVisible: "World"
This should be true if an element containing "Hello World!" is visible. Would be great to make this the standard behaviour. If necessary you can possibly add an option to use the current behaviour.

**Describe alternatives you've considered**
 I am not able to provide the whole article text in the yaml file. Also pasting the whole article in the test yaml makes it unreadable and the content can contain text styling, line breaks and more.

**Additional context**
none

Best Regards!

**Comment by rasyid7** [comment]
What I'm understand is,

There's a text `Hello World` in the app,
and you want to `assertVisible: World`?

if so, you can use regex:
`assertVisible: .*World`.
or you can use `or`:
`assertVisible: World|Hello World`

**Comment by bartekpacia** [comment]
Thanks @rasyid7 for answering here! Yeah, regex seems like the way to go here.

**Comment by K0n2t1** [comment]
Thx @rasyid7! i wasn't aware i am able to use regex here.
That solves the problem for my use case. ❤️
