### ISSUE TITLE
Maestro does not move on with the next step as the hierarchy is still changing even though in some cases it's what we want.

### ISSUE THREAD

**Issue by StylianosGakis** [mobile-dev-inc/maestro#183]
My use case is described exactly in the slack channel in this discussion https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1663244249203259?thread_ts=1663243109.313569&cid=C041FU72T54
The gist is that in some step of the test, there's an audio recording and a timer is updating every second to show how many seconds long the recording is. This however made the test in one case take 20 seconds to commit to do the next action. There is an assumption that the constantly changing hierarchy is contributing to this delay as it's still waiting for the hierarchy to settle before going on the next step.
This may be true for various UIs where there might be some constantly changing view state that should not obstruct the test from continuing on.

**Comment by mollyhartwick3** [comment]
We put in a fix that we believe will fix your issue in version 1.11.4. Closing this issue, please feel free to reopen if this continues to be an issue 🙂
