### ISSUE TITLE
More assertions

### ISSUE THREAD

**Issue by cvoronin** [mobile-dev-inc/maestro#184]
Maestro looks very cool, really.
However we need more assertions for testing.
For example, I want to test a calculator. I enter 5 into field A, I enter 5 into field B, press "Add Button" - and now I have to validate that "Result" field contains 10.

**Comment by dmitry-zaitsev** [comment]
For that you can use `assertVisible`:

```
- assertVisible:
     id: id_of_your_result_field
     text: 10
```
