### ISSUE TITLE
CICD asks for analytics, no way to opt out

### ISSUE THREAD

**Issue by christian-hess-94** [mobile-dev-inc/maestro#1846]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

We are pushing a RN update in our app. We use maestro for running visual regression screenshot tests, and the branch that has the update is getting stuck when maestro asks us to opt into analytics: 
![image](https://github.com/user-attachments/assets/1707c46f-2c60-4cd1-8f39-5c59fd0dd950)

### Actual results

The CICD workflow gets stuck after bundling the app and running maestro, as maestro asks for us to opt into analytics:
![image](https://github.com/user-attachments/assets/f167666e-b360-4333-913f-98204bff62d7)

### Expected results

We would like to know if we can modify the command to run maestro to automatically opt out of analytics (we do not wish to opt in at this point)

### About app

The app is closed source. The issue with maestro is happening only when running out visual regression suites via github actions CICD runners.

### About environment

The workflow runs on ubuntu, I don't know which specific version

### Logs

<details>
<summary>Logs</summary>

```
BUILD SUCCESSFUL in 11m 46s
983 actionable tasks: 983 executed

Build successful!
Starting emulator...
Waiting for emulator to start...
Installing APK on emulator...
Performing Streamed Install
Success

App installed successfully!
Waiting for the simulator to start...
===== Run E2E Attempt: 1 ====
Maestro CLI would like to collect anonymous usage data to improve the product.
Enable analytics? [Y/n] 
Error: The operation was canceled.
```

</details>

### Maestro version

1.33.1

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

### Anything else?

This is the step where we are installing maestro in our CICD machine:
- name: Install Maestro
        run: |
          export MAESTRO_VERSION="1.33.1"
          curl -Ls "https://get.maestro.mobile.dev" | bash

**Comment by bartekpacia** [comment]
Hey @christian-hess-94, sorry about this! 

For now, this should work: `printf 'n\n' | maestro <...>`

**Comment by christian-hess-94** [comment]
hi @bartekpacia! Thanks for the response. This is the way we are running the maestro command:
```js
const MAESTRO_TEST_COMMAND = `${process.env.HOME}/.maestro/bin/maestro test .maestro/storybook.yml`;
...
const child = spawn(MAESTRO_TEST_COMMAND , [], { ...options, shell: true });
```

So i'd change it to:
```js
const MAESTRO_TEST_COMMAND = `printf 'n\n' | ${process.env.HOME}/.maestro/bin/maestro test .maestro/storybook.yml`;
...
const child = spawn(MAESTRO_TEST_COMMAND , [], { ...options, shell: true });`
```

**Comment by bartekpacia** [comment]
Hey @christian-hess-94, v1.37.4 is out and this problem should no longer occur on CIs.

To disable analytics collection (and asking for it), set `MAESTRO_CLI_NO_ANALYTICS` environment variable to any value, for example:

```
MAESTRO_CLI_NO_ANALYTICS=1
```

Please let me know if the issue persists.

**Comment by christian-hess-94** [comment]
awesome thanks for the quick response, I'll try to implement it here and circle back to you!

**Comment by christian-hess-94** [comment]
@bartekpacia would this work as a way to set the analytics env variable?
![image](https://github.com/user-attachments/assets/c3aa5439-0f7b-42e1-aa7a-6bafd2e57466)

**Comment by bartekpacia** [comment]
Nope. On GitHub Actions you set env vars in a bit different way - [see here](https://stackoverflow.com/questions/57968497/how-do-i-set-an-env-var-with-a-bash-expression-in-github-actions)

**Comment by christian-hess-94** [comment]
oh ok got it thanks! I have modified like so:
![image](https://github.com/user-attachments/assets/bb2e1a39-364b-49a4-8d8e-b8fe4c2c108c)

the `yarn test:visual:android` line is the script that executes maestro:
`"test:visual:android": "node .maestro/scripts/visual-testing.js compareScreenshots --platform=android",`

this leads to the code snippets I sent originally:
```js
const MAESTRO_TEST_COMMAND = `${process.env.HOME}/.maestro/bin/maestro test .maestro/storybook.yml`;
...
const child = spawn(MAESTRO_TEST_COMMAND , [], { ...options, shell: true });
```

**Comment by bartekpacia** [comment]
Yes, that should work.

If it solves your problem, please close the issue. Cheers!
