### ISSUE TITLE
NullPointerException in maestro cli 1.37.4

### ISSUE THREAD

**Issue by prasanta-biswas** [mobile-dev-inc/maestro#1870]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

Getting NullPointerException with simple `maestro` command
Command: 
`
 $maestro
 
Exception in thread "main" java.lang.NullPointerException: acc must not be null
	at maestro.cli.util.IOSEnvUtils.getSimulatorRuntimes(IOSEnvUtils.kt:19)
	at maestro.cli.analytics.Analytics.maybeUploadAnalyticsAsync(Analytics.kt:147)
	at maestro.cli.AppKt.main(App.kt:99)
`

### Actual results

Exception in thread "main" java.lang.NullPointerException: acc must not be null
	at maestro.cli.util.IOSEnvUtils.getSimulatorRuntimes(IOSEnvUtils.kt:19)
	at maestro.cli.analytics.Analytics.maybeUploadAnalyticsAsync(Analytics.kt:147)
	at maestro.cli.AppKt.main(App.kt:99)

### Expected results

Should show usage details

### About app

NA

### About environment

Apple MacBook Pro M1 Sonoma
Java 17

### Maestro version

1.37.4

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

**Comment by prasanta-biswas** [comment]
@amanjeetsingh150 
Xcode 15.2
Build version 15C500b

**Comment by bartekpacia** [comment]
Hey @prasanta-biswas, sorry about the problem. Could you tell me if (and if yes, what's inside) this path exists on your machine?

```
/Library/Developer/CoreSimulator/Volumes/*/Library/Developer/CoreSimulator/Profiles/Runtimes/
```

This issue seems to be the same as #1850

**Comment by prasanta-biswas** [comment]
@bartekpacia yes it exisits
```
$ls -l /Library/Developer/CoreSimulator/Volumes/*/Library/Developer/CoreSimulator/Profiles/Runtimes/
/Library/Developer/CoreSimulator/Volumes/iOS_20E247/Library/Developer/CoreSimulator/Profiles/Runtimes/:
total 0
drwxrwxr-x  3 root  wheel  96 Mar 23  2023 iOS 16.4.simruntime

/Library/Developer/CoreSimulator/Volumes/iOS_21C62/Library/Developer/CoreSimulator/Profiles/Runtimes/:
total 0
drwxrwxr-x  3 root  wheel  96 Dec  2  2023 iOS 17.2.simruntime
```

**Comment by bartekpacia** [comment]
That's very weird then. This is my output:

```
$ ls -l /Library/Developer/CoreSimulator/Volumes/*/Library/Developer/CoreSimulator/Profiles/Runtimes/
/Library/Developer/CoreSimulator/Volumes/iOS_20E247/Library/Developer/CoreSimulator/Profiles/Runtimes/:
total 0
drwxrwxr-x  3 root  wheel  96 Mar 23  2023 iOS 16.4.simruntime

/Library/Developer/CoreSimulator/Volumes/iOS_21F79/Library/Developer/CoreSimulator/Profiles/Runtimes/:
total 0
drwxrwxr-x  3 root  wheel  96 May  4 07:04 iOS 17.5.simruntime
```

but I don't see this error.

**Comment by bartekpacia** [comment]
Thanks. I managed to reproduce the issue. First thing is to remove the analytics statefile: 

`rm ~/.local/state/maestro/analytics.json`

and rebuild CLI with a path that doesn't exist, e.g. `Library/Developer/CoreSimulator/Profiles/Runtimes_DOES_NOT_EXIST_TEST`

That said I don't know why `listFiles()` returns null on your machine. In other words, if the paths exist (like in your case), I don't know why this code fails:

```kotlin
val topLevelDirs = Path("/Library/Developer/CoreSimulator/Volumes").toFile()
    .listFiles()
    ?.filter { it.exists() } ?: emptyList()

val installedRuntimes = topLevelDirs
    .map { it.resolve("Library/Developer/CoreSimulator/Profiles/Runtimes") }
    .map { it.listFiles() }
    .reduceOrNull { acc, list -> acc + list }
    ?.map { file -> file.nameWithoutExtension }
```
