### ISSUE TITLE
[Feature Request] support specifying device id when running maestro test

### ISSUE THREAD

**Issue by btrautmann** [mobile-dev-inc/maestro#1891]
**Is your feature request related to a problem? Please describe.**

We have written a wrapper around `maestro` that supports running/recording/playing back our end-to-end tests. Because a user may have multiple devices running on their machines, we'd like to support selecting a device to run on, but maestro AFAIK does not support this.

_Edit to add:_ Today, Maestro does this via a prompt that requires human input, we'd just like to make it so that a CLI tool can easily do this as well.

**Describe the solution you'd like**

We'd like to be able to do `maestro test <device-id> <test-file>`. If you need to disambiguate the device id being for a given platform, maybe another flag is needed, but AFAIK iOS uses UUIDs and Android uses simple strings (e.g `emulator-5554` or `ZY224LJPKC`) which should be easy to tell apart.

**Describe alternatives you've considered**

Right now we bail early if we see that more than one device is running on the host machine with an error: `Multiple Flutter devices found, but Maestro does not support starting tests with a device chosen in a non-interactive manner. Please close all devices but the target device and try again.`

This is a stinky UX for the developer.

**Comment by bartekpacia** [comment]
Hey @btrautmann, this is already possible with:

```
maestro \
  --udid emulator-5554 \
  test .maestro/my_test_flow.yaml
```

or for iOS:


```
maestro \
  --udid 047787D4-FD19-4D63-A485-994C0965D42C \
  test .maestro/my_test_flow.yaml
```

**Comment by btrautmann** [comment]
Ah, that worked perfectly! Thanks @bartekpacia. I may have missed this in the documentation, sorry about that.
