### ISSUE TITLE
Enhancement - Add clickable as an assertion option

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#190]
It would be good to check if an element is clickable true or false

**Comment by dmitry-zaitsev** [comment]
There are 2 reasons for why we decided not to add such an assertion:

- There is currently no way to infer this on iOS as this information is not exposed to us
- We like to think about Maestro as a user going through the flow. A user would only know whether an element is clickable by actually trying to click on somthing and seeing whether there is any result. So even if an element is clickable but offers no feedback - that is the same as if it would not work
