### ISSUE TITLE
maestro 1.37.8 cannot connect to XCUITest server

### ISSUE THREAD

**Issue by disrae** [mobile-dev-inc/maestro#1915]
Downgrading to previous version results in working execution again. 
Re-installing latest version once again fails to connect to XCUITest server. 
![image](https://github.com/user-attachments/assets/b68394e7-a626-4ed6-b491-7e5edf9db428)

[2024-08-14_174004.zip](https://github.com/user-attachments/files/16620056/2024-08-14_174004.zip)

Edit: Oops, I see this is already reported, but in case my log files are useful I'll leave it up for now. 🙏

**Comment by bartekpacia** [comment]
duplicate of #1914
