### ISSUE TITLE
[Feature Request] Add the ability to configure different email for different individual/bunch of tests

### ISSUE THREAD

**Issue by mrinalkhanvilkardd** [mobile-dev-inc/maestro#1925]
**Is your feature request related to a problem? Please describe.**
Currently whenever a test fails there is a way to email for the overall test suite failure to a single email. We are multiple team writing maestro tests cases for our individual features. With just email, it creates a lot of noise. It would be great if we would be able to configure email for individual/bunch (folder) of tests.

**Describe the solution you'd like**
Along with the `config.yaml` at the root, it would be preferable to have a `config.yml` for individual subfolders. Another solution is to add an overriding email address (or slack channel) in the test itself.

**Describe alternatives you've considered**
Currently we have to manually take a look at the dev console and we are trying to prevent that

**Additional context**

**Comment by bartekpacia** [comment]
Hey @mrinalkhanvilkardd – thanks for this suggestion.

Would a webhook work for you? I.e. you'd receive a webhook from Maestro Cloud whenever a test suite completes, and in the payload you'd have data about specific flows, etc. Then you could apply filtering yourself, and we'd avoid adding more complex code to Maestro. How does that sound to you?

**Comment by mrinalkhanvilkardd** [comment]
> Hey @mrinalkhanvilkardd – thanks for this suggestion.
> 
> Would a webhook work for you? I.e. you'd receive a webhook from Maestro Cloud whenever a test suite completes, and in the payload you'd have data about specific flows, etc. Then you could apply filtering yourself, and we'd avoid adding more complex code to Maestro. How does that sound to you?

Hi @bartekpacia our current CI is bitrise, let me check if that would work with that.

**Comment by bartekpacia** [comment]
I used Bitrise; it allows you to execute arbitrary code, so you should be able to collect results yourself, and do whatever you want with them.
