### ISSUE TITLE
iOS landscape mode support

### ISSUE THREAD

**Issue by tkhvaira** [mobile-dev-inc/maestro#1926]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

!NOTE! I reopen this issue as far as this is not fixed and changes was rolled back, but a lot of people need this so bad.

iOS testing currently does not support landscape mode.

As a quick test, download the samples:

```
maestro download-samples
cd ./samples
unzip sample.zip
xcrun simctl install Booted Wikipedia.app
```
And update the iOS flow to:

```
appId: org.wikimedia.wikipedia
---
- launchApp
- tapOn: "Search Wikipedia"
- inputText: "tacos"
```
Launch the simulator and rotate into landscape mode, and then run:

`maestro test ios-flow.yaml`

The test reports that it passes, but it does not navigate into the search screen to type into the text.

Running maestro studio shows a mismatch where the overlay content appears to be laid out in landscape, but the image of the app's screen is rotated 90 degrees:

<img width="1682" alt="image" src="https://github.com/user-attachments/assets/70f3dbb4-bee6-4165-b9fd-18f92039ea10">

### Actual results

Test steps marked as passed but nothing is happening on the simulator.

### Expected results

Correctly interacting with simulator when actions performed by tests.

### About app

Application from samples

### About environment

I'm on MacBook Pro M3 running on Sonoma 14.6.1

### Maestro version

1.37.9

### How did you install Maestro?

Homebrew

**Comment by bartekpacia** [comment]
thanks, I remembered about it but forgot to re-open #565. now that it's re-opened, i'll close this as a dupe

**Comment by chiefchief** [comment]
@bartekpacia You've reopened #565 but the conversation is locked

**Comment by bartekpacia** [comment]
Sorry, I forgot to unlock the conversation. Should be good now.

As for iOS landscape support - we plan to re-add it soon.

**Comment by chiefchief** [comment]
> Sorry, I forgot to unlock the conversation. Should be good now.
> 
> As for iOS landscape support - we plan to re-add it soon.

thank you

**Comment by tkhvaira** [comment]
> Sorry, I forgot to unlock the conversation. Should be good now.
> 
> As for iOS landscape support - we plan to re-add it soon.

thanks so much, waiting for this coz our app is working in landscape only and we really want to test it using Maestro
