### ISSUE TITLE
Run Maestro testcases on different ports of Wiremock server

### ISSUE THREAD

**Issue by jaideepl** [mobile-dev-inc/maestro#1934]
### Use case

We want to run Maestro testcases parallel using Wiremock server for mocking.
Currently Maestro runs on a apk which can connect to a single port of Wiremock. Due to this, when we execute the testcases in parallel, the mock data gets overridden on Wiremock server.
Please provide a solution for this.

**Comment by bartekpacia** [comment]
I'm not familiar with Wiremock. Could you be more specific and explain what solution you'd like us to implement?
