### ISSUE TITLE
"maestro test" does nothing

### ISSUE THREAD

**Issue by vsilvadev** [mobile-dev-inc/maestro#194]
When I try to run the command for the test to start nothing happens and the test never runs.

![Kapture 2022-09-16 at 12 20 38](https://user-images.githubusercontent.com/60434378/190674254-64b291a9-18d4-4ec6-be32-93b21d2a4cbb.gif)

**Comment by dmitry-zaitsev** [comment]
Are you using Android or iOS? If Android, is it an emulator or a real device?

**Comment by vsilvadev** [comment]
I'm using an Android Emulator, the app is already running when I try to execute the command to test.

**Comment by jojofrelis** [comment]
hi. how's the progress of this issue? i using android emulator and i get this issue too

**Comment by jkgwak** [comment]
I have the same problem.
Are there any updates?
