### ISSUE TITLE
Consolidated Assert using mapping

### ISSUE THREAD

**Issue by Rbnbcr** [mobile-dev-inc/maestro#1951]
### Use case

Sometimes, I have to assert many labels on a single overview. Which will look like: 

- assertVisible: "1"
- assertVisible: "2"
- assertVisible: "3"

### Proposal

Wouldn't it be much more efficient if we could have it consolidated like such:

- assertVisible: { "1", "2", "3" }

**Comment by bartekpacia** [comment]
In the use case you presented, you can extract the repeated steps to a subflow.

[docs](https://maestro.mobile.dev/api-reference/commands/runflow#runflow)

**Comment by bartekpacia** [comment]
I don't think the added complexity is worth it.

Maybe a more advanced use case could warrant it, but the one provided doesn't.
