### ISSUE TITLE
Android exception while opening a deeplink - java.lang.NullPointerException: appName must not be null

### ISSUE THREAD

**Issue by smehr123** [mobile-dev-inc/maestro#1956]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

1) Installed the android react native app on emulator
2) tried to open an app deeplink with following steps as suggested by Maestro official doc

Code Block:
```
appId: com.example.app
---
- launchApp:
    clearState: true
- openLink:
    link: 'https://link-stage.test.fan/test123'
- assertVisible: 'Welcome'
```

Please Note: It seems to run fine on iOS simulator

### Actual results

failed with the message:
java.lang.NullPointerException: appName must not be null
[maestro test maestro/deeplink.yaml] 	at maestro.drivers.AndroidDriver.autoVerifyWithAppName(AndroidDriver.kt:533)
[maestro test maestro/deeplink.yaml] 	at maestro.drivers.AndroidDriver.autoVerifyApp(AndroidDriver.kt:519)
[maestro test maestro/deeplink.yaml] 	at maestro.drivers.AndroidDriver.openLink(AndroidDriver.kt:513)
[maestro test maestro/deeplink.yaml] 	at maestro.Maestro.openLink(Maestro.kt:487)
[maestro test maestro/deeplink.yaml] 	at maestro.orchestra.Orchestra.openLinkCommand(Orchestra.kt:701)
[maestro test maestro/deeplink.yaml] 	at maestro.orchestra.Orchestra.executeCommand(Orchestra.kt:262)
[maestro test maestro/deeplink.yaml] 	at maestro.orchestra.Orchestra.executeCommands(Orchestra.kt:201)
[maestro test maestro/deeplink.yaml] 	at maestro.orchestra.Orchestra.runFlow(Orchestra.kt:111)
[maestro test maestro/deeplink.yaml] 	at maestro.orchestra.Orchestra.runFlow$default(Orchestra.kt:75)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.runner.MaestroCommandRunner.runCommands(MaestroCommandRunner.kt:185)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:54)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.runner.TestRunner$runSingle$result$1.invoke(TestRunner.kt:51)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.runner.TestRunner.runCatching(TestRunner.kt:145)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.runner.TestRunner.runSingle(TestRunner.kt:51)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1$1.invoke(TestCommand.kt:291)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1$1.invoke(TestCommand.kt:249)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.session.MaestroSessionManager.newSession(MaestroSessionManager.kt:107)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.session.MaestroSessionManager.newSession$default(MaestroSessionManager.kt:58)
[maestro test maestro/deeplink.yaml] 	at maestro.cli.command.TestCommand$handleSessions$1$1$results$1$1.invokeSuspend(TestCommand.kt:249)
[maestro test maestro/deeplink.yaml] 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[maestro test maestro/deeplink.yaml] 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
[maestro test maestro/deeplink.yaml] 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
[maestro test maestro/deeplink.yaml] 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
[maestro test maestro/deeplink.yaml] 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
[maestro test maestro/deeplink.yaml] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
[maestro test maestro/deeplink.yaml] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
[maestro test maestro/deeplink.yaml] 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)
[maestro test maestro/deeplink.yaml] ==== Debug output (logs & screenshots) ====

### Expected results

The app should have opened the deeplink successfully

### About app

cross-platform app, react native

### About environment

Device: Pixel 3a
OS: API 33
MacOS: Sonoma - 14.6.1

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.37.9

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

**Comment by bartekpacia** [comment]
This issue is not reproducible.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

This issue does not contain such an example, therefore it'll be closed unless you update it.

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example

**Comment by bartekpacia** [comment]
Thanks.

Does setting `autoVerify: false` help?

See https://maestro.mobile.dev/api-reference/commands/openlink

**Comment by smehr123** [comment]
Yes that helped, thank you :)

**Comment by bartekpacia** [comment]
I mean, this is still a bug, tho I'm glad the workaround worked:)
