### ISSUE TITLE
The `Command` interface should have a `String label` property

### ISSUE THREAD

**Issue by bartekpacia** [mobile-dev-inc/maestro#1969]
Since all Maestro commands now accept a `label`, it makes sense to add it to

https://github.com/mobile-dev-inc/maestro/blob/ba6927385c9d6305aef7eae5d21b49f190ee538a/maestro-orchestra-models/src/main/java/maestro/orchestra/Commands.kt#L31-L39

so we never forget about it.

### Additional context

Mentioned by @amanjeetsingh150 in https://github.com/mobile-dev-inc/maestro/pull/1906/files/ba045503e5eb0c46e26e6279d6130c1a25954311#r1735133326

**Comment by tokou** [comment]
Fixed here https://github.com/mobile-dev-inc/maestro/pull/1946/commits/0101e44aa3d76005ac0220398f6e0887eb9743df
