### ISSUE TITLE
tapAndHold command until release

### ISSUE THREAD

**Issue by manoadepu** [mobile-dev-inc/maestro#1975]
### Feature Suggestion: Advanced Gesture Interaction

**Description:**
The proposed feature allows for more complex user interactions by enabling the user to perform a long press on one element or point while simultaneously tapping on a different element or point. This can enhance the testing framework's ability to simulate and validate advanced user interactions.

**Examples:**

1. **_Long Press:_** Long press on a context menu button (e.g., a "Settings" icon).
**_Tap:_** While holding the long press, tap on a submenu item (e.g., "Privacy Settings").
Use Case: This simulates opening a context menu and selecting an option without lifting the finger.

2. **_Drag-and-Drop Operations:_** long press on an element and use swipe to drop on a specific location.
 
Benefits:
Enhances the capability to test complex user interactions that involve simultaneous gestures.
Provides a more realistic simulation of user behavior for better validation of application functionality.

### Proposal

Below is the piece of code I would have done if i am using Appium:

```python
driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)

element = driver.find_element_by_id('com.example.app:id/element_id')  # Change to your element's ID

touch_action = TouchAction(driver)
touch_action.long_press(element, duration=2000).release().perform()

x_coord = 500
y_coord = 800

for _ in range(5):
    touch_action.tap(x=x_coord, y=y_coord).perform()
```

**Comment by bartekpacia** [comment]
Hey @manoadepu!

The drag-and-drop seems to already tracked in https://github.com/mobile-dev-inc/maestro/issues/1203. Can you confirm it's what you want?

I'm also a bit confused about the sample you code posted. It seems that it would tap 5 points one after another, not tap&hold on them simultaneously, right?
