### ISSUE TITLE
Reverse the order of releases in changelog.md

### ISSUE THREAD

**Issue by egor-n** [mobile-dev-inc/maestro#201]
I'd like to suggest that the order of releases in https://github.com/mobile-dev-inc/maestro/blob/main/CHANGELOG.md be reversed. Currently, it is showing the oldest release first while it's more convenient to show the newest releases at the top so you don't have to scroll. Happy to submit a PR for this change.

**Comment by dmitry-zaitsev** [comment]
That definitely makes sense. The thought always crosses my mind whenever we do a new release :)
