### ISSUE TITLE
Provide a way to clear the state of the app outside of the `launchApp` command.

### ISSUE THREAD

**Issue by StylianosGakis** [mobile-dev-inc/maestro#204]
My use case is that I am testing the app using a deep link since I need to provide it some extras to avoid authentication which can not be part of the maestro flow. Or someone else might want to deep link into specific screens just to make the test faster and more deterministic.
Either way, a way to clear the app before-hands would be awesome and would allow for better tests.
Discussion started here: https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1663349097034459?thread_ts=1663332026.363259&cid=C041FU72T54

**Comment by dmitry-zaitsev** [comment]
The `clearState` command is already implemented and is going to be a part of the next Maestro release (this week)

**Comment by dmitry-zaitsev** [comment]
`clearState` command is now live in 1.7.1
