### ISSUE TITLE
Unable to pass the values returned from a javascript file to the run flow

### ISSUE THREAD

**Issue by smehr123** [mobile-dev-inc/maestro#2040]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

**Java script file:**
function generateEmailWithUniqueCode() {
    // Generate a random 6-digit code
    const sixDigitCode = Math.floor(100000 + Math.random() * 900000)
    const email = `te.${sixDigitCode}@test.com`
    return { code: `${sixDigitCode}`, email: email }
  }
// Retrieve both values from the function
const result = generateEmailWithUniqueCode();
// Store the values in the output object
const output = {
    code: result.code,
    email: result.email
};

**Maestro file:**
appId: com.example.dev
---
- runScript:
    file: java-script-helpers/generate-email-username.js
- runFlow:
    file: helpers/signUp.yaml
    env:
      EMAIL: ${output.email}
      VERIFICATION_CODE: ${output.code}
      USERNAME: 'dhadhwjdjwj'
      TEAM_NAME: 'Test Team'
- takeScreenshot: AfterSignUp

### Actual results

The EMAIL parameter value is being set as org.mozilla.javascript.Undefined@1eb6a241

### Expected results

The EMAIL parameter value should be set as something like - te.123456@test.com

### About app

React Native app
iOS
Simulator - iPhone 15, iOS 17.5

### About environment

Mac OS - Sonoma - 14.6.1

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.37.9

### How did you install Maestro?

install script (https://get.maestro.mobile.dev)

**Comment by smehr123** [comment]
Please Note: I tried logging the email and code values to console and they are being printed fine

**Comment by bartekpacia** [comment]
screenshot for posterity

![Screenshot 2024-09-10 at 20 41 29](https://github.com/user-attachments/assets/81d8d62b-c917-4771-98f4-a273cb496ae5)
