### ISSUE TITLE
Input text is not working properly on webview after clearstate and launchApp

### ISSUE THREAD

**Issue by aakash1313** [mobile-dev-inc/maestro#207]
We have a scenario where we need to make some changes in our config and relauch the app and initiate the test steps again . But it seems after re-launching the app, the input text is not setting the value properly. 

Maestro Version 1.71
Android emulator 11, Pixel2

Here's an emulated script to repro the scenario

`appId: com.microsoft.office.outlook
---
- launchApp
- tapOn: "ADD ACCOUNT"
- tapOn: "Enter your email"
- inputText: "olmuitesting2@outlook.com"
- tapOn: "CONTINUE"
- tapOn: "Password"
- inputText: "Outlookrox!"
- clearState: com.microsoft.office.outlook
- launchApp
- tapOn: "ADD ACCOUNT"
- tapOn: "Enter your email"
- inputText: "olmuitesting2@outlook.com"
- tapOn: "CONTINUE"
- tapOn: "Password"
- inputText: "Outlookrox!"
- tapOn: "Sign In"
`

Bug: The second time inputText is just setting Outlo and skipping the remaining text

Please let me know if you need more info on this

**Comment by dmitry-zaitsev** [comment]
@aakash1313 I was not yet able to reproduce the issue, however it seems that folks on the Internet sometimes face a similar issue with `adb input text`: [link](https://stackoverflow.com/q/59342871/926907)

I have some ideas on how to fix this optimistically, but first - could you please share a screen recording of this issue?

**Comment by ArthurSav** [comment]
@dmitry-zaitsev 

> I have some ideas on how to fix this optimistically, but first - could you please share a screen recording of this issue?

Perhaps we can introduce an artificial detail for char input

**Comment by aakash1313** [comment]
@ArthurSav : That's a good idea, but as per the doc it seems that is encouraged , waiting for @dmitry-zaitsev on this :)

**Comment by ArthurSav** [comment]
@aakash1313 I was referring to adding a small delay per single char input. So typing `Hello` would be `H`-> delay 10ms -> `e`-> delay 10ms etc...

**Comment by ArthurSav** [comment]
@aakash1313 This should be fixed with the next release

**Comment by dmitry-zaitsev** [comment]
A fix is now in 1.8.0. Please let us know if it works for you!
