### ISSUE TITLE
Audio ouput testing 

### ISSUE THREAD

**Issue by yelkamel** [mobile-dev-inc/maestro#211]
Hello,

We develop evolum, it's a french app for meditation and relaxing.

I really like maestro and I test everything that I can.

But I wanted to know if it's possible to add a feature to test the output audio of the device ?
We wanna test if the meditation audio play after we click on the play button.

Regards,

**Comment by matt-dalton** [comment]
+1 on this - would be great

**Comment by Leland-Takamine** [comment]
Hey closing this issue out for now since we don't have plans to address in the near future. If anything changes we'll update this thread.
