### ISSUE TITLE
Input Special Characters & Emojis

### ISSUE THREAD

**Issue by DavidREntwistle** [mobile-dev-inc/maestro#2114]
### Use case

Input validation testing, special characters and emojis

### Proposal

Expanding on the `- inputText` command, allowing the use of special characters & emojis e.g. £ & 💰

**Comment by Fishbowler** [comment]
Is this #146 ?

**Comment by DavidREntwistle** [comment]
Looks so! I'll close this.

**Comment by DavidREntwistle** [comment]
Closing as issue raised [here](https://github.com/mobile-dev-inc/maestro/issues/146)
