### ISSUE TITLE
Run JavaScript - passing a parameter does not work as described in docs

### ISSUE THREAD

**Issue by NikolaSimsic** [mobile-dev-inc/maestro#2139]
### Is there an existing issue for this?

- [X] I have searched the existing issues and didn't find mine.

### Steps to reproduce

I am trying to pass the parameters to the javascript file exactly as it is described [here](https://maestro.mobile.dev/advanced/javascript/run-javascript#:~:text=Passing%20a%20parameter,//%20Outputs%20%27Parameter%27).

This is the code:

```
- runScript:
    file: checkText.js
    env:
        elementId: logBox
        expectedText: random
```

And checkText.js:

```
const elId = elementId;
const expectedTxt = expectedText;
console.log("out log", elId, expectedTxt);
```

### Actual results

After the execution, result is without values being read:

 ║         Log messages:                                                                   
 ║           out log                                                                       
 ║                     
 
 
 

### Expected results

It should be possible to pass the env values as a parameters to the js file.

### About app

It is a native app, execution on Android device. But this does not matter for the case.

### About environment

M1 MacBook Air arm64 macOS Sequoia 15.1. 
openjdk 17.0.9 2023-10-17
OpenJDK Runtime Environment Homebrew (build 17.0.9+0)

### Logs

<details>
<summary>Logs</summary>

```
<!-- Replace this line with your logs. *DO NOT* remove the backticks! -->
```

</details>

### Maestro version

1.39.1

### How did you install Maestro?

Homebrew

**Comment by Fishbowler** [comment]
Logging only supports a single parameter right now

https://maestro.mobile.dev/advanced/javascript/logging

**Comment by Fishbowler** [comment]
Gonna close this for now. Please feel free to reopen if that doesn't solve your problem.

**Comment by Fishbowler** [comment]
Howdy @NikolaSimsic.

I gave it a day before closing AND included a suggestion to reopen the issue if it didn't solve your problem.

Your example doesn't follow the docs I linked.

Needs to be:
```
console.log("out log: " + elId);
```
