### ISSUE TITLE
Question: Background Assertions

### ISSUE THREAD

**Issue by mzelzoghbi** [mobile-dev-inc/maestro#221]
Hello team, 
Awesome work team, I really like how simple to wirte a test.

I'm currently working on SDK and automating our sanity tests using Espresso but it is very challenging since most of our work running in the background with almost NO UI, My question is can Maestro run assertions on Background calls, like Network request response, Sqlite record added/removed or files created/deleted? and if not is it something on your backlog.

Thanks. 🙏🏻

**Comment by axelniklasson** [comment]
Hi there @mzelzoghbi! As of maestro 1.27.0 we support [assertions of outgoing network requests](https://maestro.mobile.dev/advanced/experimental/maestro-mock-server/commands/assertoutgoingrequests), so please check that out and open another issue if you want to see other enhancements in maestro.
