### ISSUE TITLE
Fast forward input text and deleting

### ISSUE THREAD

**Issue by josealfonsomora** [mobile-dev-inc/maestro#222]
Adding text to a text field is very slow going character by character. 
Is there a way to fast forward it or to input the text altogether?

The same for deleting. Can we delete all text in a field with a single command?

**Comment by amanjeetsingh150** [comment]
Hey, @josealfonsomora this should be resolved in the latest release 1.10.0. Can you check if this works for you? Feel free to reopen issue if you face any difficulty.

**Comment by josealfonsomora** [comment]
thanks @amanjeetsingh150 `inputText` is working good now but `eraseText` is still taking a lot to complete, can we make it to clear text faster?

**Comment by amanjeetsingh150** [comment]
Hmmm, strange nothing has changed around that implementation. That mostly happens because internally we repeat pressing backspace. Is it only android or iOS?

**Comment by josealfonsomora** [comment]
Android




https://user-images.githubusercontent.com/793226/195889168-aeb1f4ea-668a-4ecc-87c8-2c6d39c799a3.mov

**Comment by amanjeetsingh150** [comment]
Hey @josealfonsomora this should be fixed in latest version of maestro. Let me know if the current speed works for you 🙌

**Comment by ShivamJoker** [comment]
It's still too slow for me.
Why don't we have API to change the speed?

**Comment by DarienYang** [comment]
Hi @amanjeetsingh150 
I'm using maestro version: 1.34.1
Text input is still quite slow in this version. 
Is there a way to solve it? Thanks

https://github.com/mobile-dev-inc/maestro/assets/120372747/7df39c48-c792-4ac8-bfce-2416b48b23a3

**Comment by sulky-penguin** [comment]
@DarienYang I am also experiencing this issue with the same version. Have you found any luck with a fix?
