### ISSUE TITLE
Unable to find Toast message

### ISSUE THREAD

**Issue by dmitry-zaitsev** [mobile-dev-inc/maestro#230]
It seems that Maestro does not "see" Toast messages in the view hierarchy

**Comment by sarimmehdi** [comment]
Any update on this?

**Comment by samatzhusup** [comment]
Any update?

**Comment by amanjeetsingh150** [comment]
Hey folks, @sarimmehdi @samatzhusup this should be addressed in next release. Have raised PR. Will keep you updated in this issue when its rolled out.

**Comment by amanjeetsingh150** [comment]
Hey @samatzhusup , @sarimmehdi this should now be available in 1.26.1. The latest version.
