### ISSUE TITLE
After initFlow is finished app closes 

### ISSUE THREAD

**Issue by lochness42** [mobile-dev-inc/maestro#241]
For some reason app closes once `initFlow` finishes thus rest of the test fails. 
If I use the same flow as `runFlow` as first step, everything works. Obviously it is a workaround, but I guess it's not intentional work.

**Comment by dmitry-zaitsev** [comment]
In fact, that is the intended behaviour of `initFlow` needed in some rare cases when working with mobile.dev platform. 

You can disregard it and use `runFlow` as you already do - that is a valid way to use the command
