### ISSUE TITLE
Add ability to run shell scripts.

### ISSUE THREAD

**Issue by lukaszciastko** [mobile-dev-inc/maestro#247]
Please, add the ability to run shell scripts inside the flow.

This can be useful for example to call API services to set up data or communicate directly with the app via localhost.

**Comment by sav007** [comment]
@dmitry-zaitsev @Leland-Takamine I just wanted to check with you if this smth you are working on right now? If not are you open to accept PR for this, I might be wrong but looks like this is doable just introducing new command to cli and orchestra modules?

**Comment by Leland-Takamine** [comment]
@sav007 One of the challenges here is that this needs to be able to run in different environments (locally, CI, Maestro Cloud). We may need to break this down into different use cases to be able to solve them in a portable fashion.

@lukaszciastko @sav007 Can you please provide some details around your main use cases?

**Comment by sav007** [comment]
Sure, one of the case was mentioned in description of this feature request.

I think having shell command support will make Maestro more flexible and extendable, for instance:
- write screen shot testing where shell used to launch external tool to compare images, or upload images 
- in our specific case we have our custom cli tool that allows to directly communicate with the app from host computer to trigger registered actions (like overriding user settings, feature flags, etc.)

I think having shell support can open tons of possibilities and integrations with 3rd party tools.

**Comment by Leland-Takamine** [comment]
One of the benefits of Maestro is that it is self contained and therefore can be run anywhere. Once external tooling is introduced, you lose that benefit. That said I do understand the motivation behind this feature. I think we'll need to think more about the trade offs. One idea that comes to mind is containerized plugins (ala custom custom docker-based github actions)

**Comment by sav007** [comment]
Totally makes sense.

**Comment by dmitry-zaitsev** [comment]
Maestro 1.16.0 introduces Javascript support: https://maestro.mobile.dev/advanced/javascript

Though it might not address all the usecases that you raised (i.e. it is not possible to call out to external tool), it solves some others (i.e. making HTTP requests).

It would be great if you could open new tickets per-usecase (i.e. screenshot testing). That would make it much easier for us to navigate and prioritise in bite-sized milestones
