### ISSUE TITLE
Allow creating "variables"

### ISSUE THREAD

**Issue by mganchas** [mobile-dev-inc/maestro#252]
Hey! Great work on Maestro 👌 
Would be really useful if there was a way to set a collection of "variables" to reuse them in our tests.

For example:
```
appId: com.company.app
---

- variables:
   loginText: "Login to your account"

- assertVisible: $loginText
- tapOn: $loginText
```

Thanks!

**Comment by dmitry-zaitsev** [comment]
Looks nice, we will consider it
