### ISSUE TITLE
Feature request: alternative syntax for setting geolocation

### ISSUE THREAD

**Issue by ragunathjawahar** [mobile-dev-inc/maestro#254]
The current syntax for setting geolocation is,

```
- setLocation:
    latitude: 13.5266
    longitude: 78.2150
```

Provide a convenience syntax in the following format,
```
- setLocation: 13.5266,78.2150
```

**Comment by Leland-Takamine** [comment]
@ragunathjawahar Going to close this out and let's continue conversation on #105
