### ISSUE TITLE
Doesn't find label TextField's text

### ISSUE THREAD

**Issue by Salamonk11** [mobile-dev-inc/maestro#259]
As you can see on screenshot attached, when I try to find the `label` of the `TextField` with `tapOn`, maestro doesn't recognizes the text.
I tried it with some different ways like:

```
tapOn: 
   text: 'label of TextField'
```
But it still doesn't work.
However, for example the text "**Dati personali**" that's above the TextField is recognized.

I'm using maestro v1.8.0 on Ubuntu 21.10 with Android emulator.

![image](https://user-images.githubusercontent.com/50325099/194320283-522ad483-410a-4ab5-9b90-7363fe3ddb1e.png)

**Comment by dmitry-zaitsev** [comment]
@Salamonk11 this depends on the view implementation as we expect that views are providing accessibility information. It seems that this TextView with a label does not report `Name` anywhere in the view hierarchy. A way around this would be to refer to the view by its id

**Comment by Salamonk11** [comment]
First of all, thank you for your feedback.
I'm trying to use the way around with the **id**, but it still doesn't work...

Am I doing something wrong?

![image](https://user-images.githubusercontent.com/50325099/196119076-14dc9777-b2c3-4634-b92e-eb9c0e7f0721.png)

**Comment by dmitry-zaitsev** [comment]
Could you share an output of `maestro hierarchy` command?

**Comment by Salamonk11** [comment]
Here it is!
This is the section concerned

![image](https://user-images.githubusercontent.com/50325099/196173344-0a5f5cdb-7529-4232-87c3-f4c122890e0a.png)
