### ISSUE TITLE
Flows : How to provide the dynamic params to the flows 

### ISSUE THREAD

**Issue by aakash1313** [mobile-dev-inc/maestro#260]
Thanks for adding the flows :)

I was trying to test these and wanted to try calling them from my YAML script using the dynamic params i provided to the script, is there a way i can achieve that currently ?

**Comment by simon-gilmurray** [comment]
https://maestro.mobile.dev/getting-started/maestro-cli#pass-variables-to-tests

**Comment by aakash1313** [comment]
Yes this is when we are calling the script from Command line, I was curious to know that how do we achieve when we are calling the script as a flow from the test script.

**Comment by dmitry-zaitsev** [comment]
@aakash1313 could you give an example of what you are trying to achieve?

**Comment by dmitry-zaitsev** [comment]
Top-level dynamic parameters are going to be propagated to sub flows as well. Is that not the case for you?

**Comment by aakash1313** [comment]
Yes that works , thanks :)

**Comment by simon-gilmurray** [comment]
@dmitry-zaitsev Is it possible to look at adding the dynamic params alongside the runFlow command in the future? 
Otherwise for long flows that have a few nested subFlows I could see it being a bit of a pain to remember to pass in everything at the top parent level when executing a test.
