### ISSUE TITLE
[Enhancement] Test Failures - Add flag to enable screenshot and hierarchy output on test/step failure

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#264]
Add an optional flag at the start of the test to enable taking a screenshot and/or outputting hierarchy to a txt file on test failure to assist with debugging/identifying problems.

E.g.

```
- enableScreenshotOnFailure
- enableHierarchyOnFailure
```

**Comment by dialex** [comment]
+1
Also, this is a duplicate of https://github.com/mobile-dev-inc/maestro/issues/237

**Comment by mollyhartwick3** [comment]
Closing as a duplicate of #237
