### ISSUE TITLE
App not loading beyond the first screen on the mobile.dev cloud

### ISSUE THREAD

**Issue by Nikhil-ventura** [mobile-dev-inc/maestro#278]
Hello Team, I uploaded my maestro script and the binary on [mobile.dev](http://mobile.dev/) cloud and while running , the test is not executing beyond the first screen as displayed in the video recording. The same is working fine on the local emulator. Could you please confirm the OS version that is being used on [mobile.dev](http://mobile.dev/) cloud for android. I checked with the developer in my team and he told that there are certain firebase packages that he has used in his code which are only supported by android OS versions >5.1. 
The emulator OS on [mobile.dev](http://mobile.dev/) shown in the video recording seems to be very old from the looks of it. Please find the console URL for the test:
[https://console.mobile.dev/uploads/a2bf9dea-cc66-4214-b33e-086490483a82?teamId=de36c02[…]d73-4528cbd96962&appId=6bd9eca6-dc7c-4505-b9ed-bb36ab00fcde](https://console.mobile.dev/uploads/a2bf9dea-cc66-4214-b33e-086490483a82?teamId=de36c025-ad29-4757-9d73-4528cbd96962&appId=6bd9eca6-dc7c-4505-b9ed-bb36ab00fcde)
[logs.
[Screen Recording 2022-10-14 at 11.22.38 AM.zip](https://github.com/mobile-dev-inc/maestro/files/9784158/Screen.Recording.2022-10-14.at.11.22.38.AM.zip)
txt](https://github.com/mobile-dev-inc/maestro/files/9784153/logs.txt)

**Comment by axelniklasson** [comment]
Hi @Nikhil-ventura, thanks for reaching out! 

mobile.dev emulators are using Android 11, so firebase packages requiring Android >5.1 should not be a problem. 

We're trying to keep this repository to be Maestro-related issues and questions only, so if you could join our [public mobile.dev Slack workspace](https://docsend.com/view/3r2sf8fvvcjxvbtk) and post a question in the `#support` channel that would be great and we're be happy to help you figure out why your flows are not being executed as expected!

Thanks,
Axel
