### ISSUE TITLE
recursively discover Flow files in subdirectories

### ISSUE THREAD

**Issue by danielstr** [mobile-dev-inc/maestro#285]
In order to have a better organization when creating flow files, it would be very useful if we can include subfolders into .mobiledev. When the suit of flows grows, it is useful to organize them into different folders. Right now this is not possible and we have to include all the files at the same level in the .mobiledev folder.

Proposed solution:
recursively discover Flow files in subdirectories contained in .mobiledev

**Comment by TseoH** [comment]
> In order to have a better organization when creating flow files, it would be very useful if we can include subfolders into .mobiledev. When the suit of flows grows, it is useful to organize them into different folders. Right now this is not possible and we have to include all the files at the same level in the .mobiledev folder.
> 
> Proposed solution: recursively discover Flow files in subdirectories contained in .mobiledev

Make it possible will be COOL 🥹

**Comment by ARK215** [comment]
That would be super-helpful, as I'm using folders too

**Comment by artem888** [comment]
hey @danielstr ! thanks a lot for your feedback! we added support for running multiple tests and more configuration for workspaces and recursive execution. more info here https://maestro.mobile.dev/cli/test-suites-and-reports

if you have more questions / suggestions don't hesitate to contact us here or on [Slack](https://mobile-dev-inc.slack.com/ssb/redirect).
