### ISSUE TITLE
Hide Keyboard fails intermittently.

### ISSUE THREAD

**Issue by imanishverma** [mobile-dev-inc/maestro#287]
Hide Keyboard is still not 100% reliable. I found following flow where it fails:

```
# flow_contacts_android.yaml
appId: com.android.contacts
---
- launchApp
- tapOn: "Create new contact"
- tapOn: "First name"
- inputText: "FName01"
- tapOn: "Last name"
- inputText: "LName01"
- tapOn: "Phone"
- inputText: "80011085400"
- hideKeyboard
- tapOn: "Email"
- inputText: "lname01.fname01@gmail.com"
- tapOn: "Save"
```

Device: Pixel 6 Emulator

**Comment by raulriera** [comment]
It also seems that this command is introducing a line break (Nexus S, SDK 32) https://github.com/mobile-dev-inc/maestro/blob/5f866556debc28a8157ab5949fb1f40ed24268a3/maestro-client/src/main/java/maestro/drivers/AndroidDriver.kt#L351

**Comment by nhaarman** [comment]
KeyEvent `4` seems to work ('back', which dismisses the keyboard) http://www.temblast.com/ref/akeyscode.htm
