### ISSUE TITLE
need help using maestro in windows. ERROR: The input line is too long. The syntax of the command is incorrect

### ISSUE THREAD

**Issue by LalithKumar702** [mobile-dev-inc/maestro#291]
I have been trying to setup maestro in windows but there are some issues which i am facing while executing ".\maestro test flow.yaml" command. 
The error is as follows:
The input line is too long. 
The syntax of the command is incorrect.

kindly anyone help me with the same.

**Comment by ykiran** [comment]
Same here. None of the command options work.
Always the same error:

> The input line is too long.
> The syntax of the command is incorrect.

**Comment by Cellule** [comment]
I moved maestro to `c:\maestro` and it worked
it tries to set an env variable `set CLASSPATH=` which is just way too long

**Comment by LalithKumar702** [comment]
i tried that still same error is occuring. 
![image](https://user-images.githubusercontent.com/57323345/196867382-d5ecaed5-abab-4a43-8315-0aab946658ec.png)

**Comment by Leland-Takamine** [comment]
Reopening as I believe we should investigate if we can fix this in Meastro itself

**Comment by dmitry-zaitsev** [comment]
We recommend using WSL to avoid having issues like that one (and generally have a better developer experience with a lot of other tooling on the market). The instructions can be found here: https://maestro.mobile.dev/getting-started/installing-maestro/windows
