### ISSUE TITLE
Version 1.10.1 throws an error whenever you run any maestro command on windows

### ISSUE THREAD

**Issue by kojofosu** [mobile-dev-inc/maestro#300]
After downloading the latest version of maestro (1.10.1) on windows, running any command just throws the error 

```
The input line is too long.
The syntax of the command is incorrect.
```

Any help?

**Comment by LalithKumar702** [comment]
change the maestro file location to C:/  . it will help

**Comment by kojofosu** [comment]
@LalithKumar702 thanks...that was really helpful. 👍🏾
