### ISSUE TITLE
Start / End markers for react native

### ISSUE THREAD

**Issue by matt-dalton** [mobile-dev-inc/maestro#301]
For app startup and flow [performance](https://docs.mobile.dev/getting-started/analysis-areas/performance), is there a way of applying start and end markers for react native? It looks like the typical way of doing this is native logging, but I don't think you can trigger native logs via React Native.

Are there any other undocumented ways of triggering the markers that might work?

**Comment by Leland-Takamine** [comment]
Hey @matt-dalton, closing this out because I believe ReactNative logging (console.log) will print out to the same same log output that native code prints to so this should just work. If this is still an issue, please feel free to reopen!
