### ISSUE TITLE
Execute all tests in particular folder

### ISSUE THREAD

**Issue by tajchert** [mobile-dev-inc/maestro#311]
Either the existing command `maestro test` or the new one should execute all tests (`.yaml` files, maybe only those with correct syntax for Maestro) in the current directory (folder) or pass the directory as an argument.

Currently when I have few test cases I need to create either one test to combine them (using test nesting) or to pass them all as arguments to `maestro test` - in both cases adding new test require to remember about this and is a tedious step.

**Comment by dialex** [comment]
Have you tried `maestro test <folder>/<name>/*.yml`? It worked for me
