### ISSUE TITLE
Be able to kill and relaunch the app during a test

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#320]
Use case:
I have feature flags within my app that are linked with Firebase remote config, and can be set/modified via a debug menu.
Sometimes these feature flags don't get picked up or reflected in the app until killing the app and relaunching.

It would be nice to be able to kill the app and then relaunch by calling the launchApp command again, or a differing one such as relaunchApp.

I think this scenario could also be useful for testing changes and state are reflected as expected after the app is removed from memory/the stack.

**Comment by dmitry-zaitsev** [comment]
I believe `stopApp` command is what you are looking for: https://maestro.mobile.dev/reference/app-lifecycle#stopapp

**Comment by simon-gilmurray** [comment]
Perfect, thanks Dima!
