### ISSUE TITLE
Unable to run the mastro command 

### ISSUE THREAD

**Issue by jaswanth119** [mobile-dev-inc/maestro#324]
Could not parse Flow file:

Cannot deserialize value of type `maestro.orchestra.yaml.YamlConfig` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]

**Comment by simon-gilmurray** [comment]
What command are you running? What does your yaml flow file look like?

**Comment by axelniklasson** [comment]
@jaswanth119 I'll go ahead and close this one, but please consult the docs to write up your first flow available [here](https://maestro.mobile.dev/getting-started/writing-your-first-flow) to get going -- if you run into any issues please reopen this issue if relevant or file a new issue!
