### ISSUE TITLE
Tabs are not allowed in yaml

### ISSUE THREAD

**Issue by jam0cam** [mobile-dev-inc/maestro#327]
The space right before `text: Allow` is a `tab`, and I get that error.  When I replaced the tab character with the space character, it's fine. 

This is the code
```
appId: com.sample.android
---
- launchApp
- tapOn: 
	text: Allow
```

This is the error message
```
java.lang.RuntimeException: while scanning for the next token
found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'reader', line 5, column 1:
    	text: Allow
    ^

```

**Comment by Leland-Takamine** [comment]
The YAML specification actually does not allow tabs for indentation unfortunately
