### ISSUE TITLE
 maestro download-samples command timeout

### ISSUE THREAD

**Issue by RandunuK** [mobile-dev-inc/maestro#352]
```
maestro download-samples

Request timeout has expired [url=https://storage.googleapis.com/mobile.dev/samples/samples.zip, request_timeout=unknown ms]
```

I'm trying to use maestro in wsl. But I'm keep getting above response for `download-samples` command. Is this a bug ?

maestro version  1.11.4

Thanks

**Comment by dmitry-zaitsev** [comment]
You can download samples from the link above: https://storage.googleapis.com/mobile.dev/samples/samples.zip
