### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedClassVersionError: maestro_android/MaestroDriverGrpc has been compiled by a more recent version of the Java Runtime.

### ISSUE THREAD

**Issue by ederhmaia** [mobile-dev-inc/maestro#356]
When I try to `./maestro test android_flow.yaml`:

`Exception in thread "main" java.lang.UnsupportedClassVersionError: maestro_android/MaestroDriverGrpc has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

# Host:
Windows 11
AMD Ryzen 3400g

# Android Studio
Pixel 4 - API 30
Android 11.0 - Google Play - x86

**Comment by Leland-Takamine** [comment]
Hey @ederhmaia - We now support Java 1.8 runtime so you should no longer see this error after upgrading to the latest Maestro version. Please reopen if you continue to see issues!
