### ISSUE TITLE
Inconsistency in release version name

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mobile-dev-inc/maestro#357]
For 1.11.3 and older, the release zip is named  `maestro-x.xx.x.zip`.  https://github.com/mobile-dev-inc/maestro/releases/tag/cli-1.11.3

For 1.11.4, the release zip is named  `maestro.zip`.  https://github.com/mobile-dev-inc/maestro/releases/tag/cli-1.11.4

For nixpkgs, we depend on the file name while downloading and extracting the archive https://github.com/NixOS/nixpkgs/blob/b542ba925c701cdaf6d1de2804c9243ce854d4e5/pkgs/development/mobile/maestro/default.nix#L8

Can the release zip names be kept consistent? Happy to submit a PR with a GitHub Action to automate this.

**Comment by dmitry-zaitsev** [comment]
Sorry that this changed impacted you. Going forward, release file name will remain `maestro.zip`.

The reason we made this change is to simplify installation procedure as this allow you to easily fetch the latest (or any other) release from Github by using this url: https://github.com/mobile-dev-inc/maestro/releases/latest/download/maestro.zip
