### ISSUE TITLE
[FeatureRequest] Allow array of ElementSelector

### ISSUE THREAD

**Issue by StanKocken** [mobile-dev-inc/maestro#362]
First: thanks for this great tool, you made an amazing work.

Suggestion: allow for Array of ElementSelector.

When describing an element, I would like to be more precise by having a list of similar requirements.
That would be useful for all the `YamlElementSelectorUnion`: below, above, leftOf, rightOf, containsChild

For example: click on the element that contains all those children.
```- tapOn:
    containsChild: 
        - text: "Text in a child view 1"
        - text: "Text in a child view 2"
```

Today I will have the error `Cannot deserialize value of type maestro.orchestra.yaml.YamlElementSelector from Array value (token JsonToken.START_ARRAY)`

**Comment by dsyrstad** [comment]
@StanKocken Would `containsDescendents` work? https://maestro.mobile.dev/api-reference/selectors

**Comment by StanKocken** [comment]
Thanks, I did not use Maestro for a while so I cannot be sure 100%, but yes it seems this new `containsDescendents` seems to address this problem, thanks!
