### ISSUE TITLE
not able to input underscore with inputText command on iOS

### ISSUE THREAD

**Issue by tom-daggett-wd** [mobile-dev-inc/maestro#365]
on iOS, I'm not able to input an underscore in a text field.

- inputText: "foo_bar"

seems to get inputed in to an actual text field as "foobar".

The problem appears to be this file:
https://github.com/mobile-dev-inc/maestro/blob/main/maestro-ios/src/main/java/ios/idb/TextInputUtil.kt
a double-quote character invokes 
`'"' to keyPressShiftedToEvents(45)`   -- see here: https://github.com/mobile-dev-inc/maestro/blob/db57d3f79c76b9a1c83556c6fba8eeda95f1a224/maestro-ios/src/main/java/ios/idb/TextInputUtil.kt#L198
and 
`'"' to keyPressShiftedToEvents(52)` -- see here: https://github.com/mobile-dev-inc/maestro/blob/db57d3f79c76b9a1c83556c6fba8eeda95f1a224/maestro-ios/src/main/java/ios/idb/TextInputUtil.kt#L203

I'm pretty sure that this line https://github.com/mobile-dev-inc/maestro/blob/db57d3f79c76b9a1c83556c6fba8eeda95f1a224/maestro-ios/src/main/java/ios/idb/TextInputUtil.kt#L198
should be 
`'_' to keyPressShiftedToEvents(45)`
since 45 is the raw DEC usage code for the hyphen key ( https://developer.apple.com/documentation/uikit/uikeyboardhidusage/keyboardhyphen ) which when the shifted key is pressed turns into an underscore.

**Comment by franciscomorais** [comment]
up
