### ISSUE TITLE
Unable to tapOn trailing IconButton element of listTile widget (flutter)

### ISSUE THREAD

**Issue by anandcpanchal** [mobile-dev-inc/maestro#366]
In pure flutter codebase, 
Maestro hierarchy not able to identify leading, trailing components of the listTile widget individually. 
example:
if,

ListTile{
    title: Text("XYZ"),
    leading: IconButton(... title: "PQR"),
    trailing: IconButton(... title:"ABC")
}

then, 
Maestro hierarchy reads it as single child with text: "XYZ ... PQR ... ABC" and hence unable to tap on individual components.

Please advise.

**Comment by spoeck** [comment]
Wrap your IconButtons in Sematic-Widget or Tooltip-Widget:

```dart
ListTile{
    title: Text("XYZ"),
    leading: Tooltip(message: "PQR", child: IconButton(... title: "PQR"),),
    trailing: Tooltip(message: "ABC", child: IconButton(... title: "ABC"),),
}

```
