### ISSUE TITLE
[Feature Request] Ability to extract values from UI elements 

### ISSUE THREAD

**Issue by manjususan11** [mobile-dev-inc/maestro#368]
**Suggestion** : It would be nice to have a feature which can read data value from UI elements and store into variable and re use the variable for further calculation & logics

**Use case examples**

- Extract current speed from speedo meter app and extract the value from it and calculate if it is over speed or not

- Extract battery usage value from settings app

**Comment by dmitry-zaitsev** [comment]
Maestro 1.16.0 comes with a [Javascript](https://maestro.mobile.dev/advanced/javascript/run-javascript) support. We did address this specific use case here: https://maestro.mobile.dev/advanced/javascript/access-element-text
