### ISSUE TITLE
Add support for android bundles on cloud

### ISSUE THREAD

**Issue by deniscoman** [mobile-dev-inc/maestro#369]
Right now when trying to upload a bundle file (.aab) it say that the type it's not supported. Can you add support for it?

**Comment by bartekpacia** [comment]
You can extract `.apk` from `.aab` using [`bundletool`](https://developer.android.com/tools/bundletool) from Android SDK.

See also [this SO question](https://stackoverflow.com/questions/53040047/generate-an-apk-file-from-an-aab-file-android-app-bundle).
