### ISSUE TITLE
Ability to launch specific Activity on Android

### ISSUE THREAD

**Issue by Leland-Takamine** [mobile-dev-inc/maestro#37]
I'm not sure what this would look like from a cross-platform perspective, but it would be useful to be able to launch directly into a specific screen (perhaps with a specific intent). One counter argument is that maestro should only be able to do what a user can. That said, launching a specific Activity feels like a pretty common need.

**Comment by dmitry-zaitsev** [comment]
Maestro is first and foremost a blackbox testing tool. While there is a possibility to add such functionality, I am afraid it will offer a subpar experience as one can't actually tinker with underlying components of the app (i.e. to mock anything out). 

In a way, I see it as an anti-pattern as by skipping in-between Activities one might miss various side-effects that might've been introduced during a typical user interaction.

**Comment by Leland-Takamine** [comment]
That sounds reasonable! 👍
