### ISSUE TITLE
[Feature request] Add a wait command

### ISSUE THREAD

**Issue by azizsoule** [mobile-dev-inc/maestro#382]
In some case you would like to add an arbitrary wait (not dependent on a UI element becoming visible/not visible). Just wait for a defined time. Something like :

```yaml

- wait:
     duration: 30000

```

**Comment by dmitry-zaitsev** [comment]
Though I understand that sometimes it might be tempting to just add a wait command, we are discouraging users from doing so as it is a sure way to introduce flakiness in tests. For that reason, we are going to intentionally avoid adding this command for as long as we can.

In those rare cases where this command is unavoidable, consider either using either solution from #176 or doing something like this:

```
- extendedWaitUntil:
       notVisible: .*     # Regular expression that matches any view
       timeout: 30000
```

**Comment by ubuntudroid** [comment]
@dmitry-zaitsev The `notVisible: .*` step always fails for me after the timeout. 🤔

**Comment by mptorz** [comment]
It still fails for me as well

**Comment by mptorz** [comment]
> Though I understand that sometimes it might be tempting to just add a wait command, we are discouraging users from doing so as it is a sure way to introduce flakiness in tests. For that reason, we are going to intentionally avoid adding this command for as long as we can.
> 
> In those rare cases where this command is unavoidable, consider either using either solution from #176 or doing something like this:
> 
> ```
> - extendedWaitUntil:
>        notVisible: .*     # Regular expression that matches any view
>        timeout: 30000
> ```


@dmitry-zaitsev  The code you posted does not work. The flow would fail. One way to make this workaround work would be to accept `optional` selector on `extendedWaitUntil`. Then we could do something like this:

```
- extendedWaitUntil:
       notVisible: .*     # Regular expression that matches any view
       timeout: 30000
       optional: true
```
