### ISSUE TITLE
Configure default delay between taps/steps

### ISSUE THREAD

**Issue by ubuntudroid** [mobile-dev-inc/maestro#385]
In our Android app we are throttling most UI interactions which lead to a navigation so that only one can happen at most with 500 ms in-between. Everything faster will just be ignored.

This is to ensure that no accidental double clicks (and thus duplicated screens) happen and it's something many Android applications do in lieu of the OS taking care of such things (and yes, there are of course exceptions where it might be fine, so it's probably okay, that the OS gives us full flexibility here).

So the question is: Is there a way to ensure that always a certain time passes between subsequent actions in a flow? I wouldn't want to add some kind of wait command between every step to ensure that all actions happen with at least 500 ms between them.

**Comment by dmitry-zaitsev** [comment]
Though it is possible to implement such parameter, I believe what it actually does is surfacing a UX issue in the application as throttling at such long interval (500ms is a lot) is quite unusual.

As there is high risk that such parameter is going to be abused as a replacement for `sleep()`, we are not going to add it in Maestro for the time being.

**Comment by ubuntudroid** [comment]
@dmitry-zaitsev I understand your reasoning, but I don't think it is an UX issue if you want to prevent screens opening multiple times if the user accidentally double taps navigation elements. This is actually a widespread issue with click handlers, both recognized by the [community](https://stackoverflow.com/questions/51060762/illegalargumentexception-navigation-destination-xxx-is-unknown-to-this-navcontr?noredirect=1&lq=1) and the [Android team](https://twitter.com/ianhlake/status/1241025657313742848?s=20&t=3Sy51h2GJm7KyurAW6CtFg).

Throttling is one common solution to the (generic click handler) problem, catching/preventing navigation exceptions another one (but only applicable specifically to navigation problems).

I recognize that solutions like this pose an issue for UI tests and I'd rather not use them at all, but right now at least Android (but also iOS from what I'm hearing) is forcing developers to add handling like that if they want bulletproof apps. So for now it's just dealing with the reality. 🤷
