### ISSUE TITLE
Remove terminal empty lines when running maestro test

### ISSUE THREAD

**Issue by edgarlealbd** [mobile-dev-inc/maestro#399]
Maestro (or any external lib command for that matter) shouldn't be responsible for jumping lines or cleaning the terminal.
As per the video below, maestro is trying to clean the terminal for a more human-readable output, which is understandable, but it shouldn't be maestro's responsibility as the user can simply run `clear && maestro test ...`.

I propose to remove these empty lines and let the user decide if he wants to jump lines, clear the terminal, etc.

https://user-images.githubusercontent.com/97473744/201720870-8123af0b-7948-4602-b8b9-cb227fd864ab.mov

**Comment by dmitry-zaitsev** [comment]
This is addressed as part of #397 and will be present in 1.15.0 release (likely this week or early next week)
