### ISSUE TITLE
Add a method to scroll using percentages of width and height instead of pixels

### ISSUE THREAD

**Issue by KrzysztofZiolek** [mobile-dev-inc/maestro#426]
Add a method to scroll using percentages of width and height instead of pixels

```
- scrollByPercentages:
    start: 0-100, 0-100
    end: 0-100, 0-100
```

**Comment by jrexd** [comment]
Here's another proposal around using percentages based off of screen size...  https://github.com/mobile-dev-inc/maestro/issues/363

**Comment by Leland-Takamine** [comment]
This is now supported via swipe! https://maestro.mobile.dev/api-reference/commands/swipe
