### ISSUE TITLE
React Native nativeID not exposed as ID

### ISSUE THREAD

**Issue by boxabirds** [mobile-dev-inc/maestro#430]
With React Native, when I label a component with a `nativeID`, I expected `maestro hierarchy` to show the `nativeID` as an ID but it doesn't. 

This means elements in React Native need to be found by text which is problematic for items that don't have text (such as visual buttons).

**Comment by jamonholmgren** [comment]
Can confirm. 👍

**Comment by peteratdivvy** [comment]
@boxabirds Why not use testID?

**Comment by boxabirds** [comment]
It’s not exposed either

**Comment by diegolmello** [comment]
I think it depends on the component.
`id` worked on some cases for me, but I couldn't get when.

**Comment by michalchudziak** [comment]
Experiencing the same issue. Android only.

**Comment by Leland-Takamine** [comment]
`testID` should work now but leaving this open for further investigation: https://maestro.mobile.dev/platform-support/react-native

**Comment by bartekpacia** [comment]
Closing since this should work now. If it's not working, please create a new bug report.
