### ISSUE TITLE
Broken pipe (Write failed) while installing sample, WSL

### ISSUE THREAD

**Issue by mcoromac** [mobile-dev-inc/maestro#432]
I'm running Maestro on WSL. I followed the steps on the Getting started page. My adb installation was not detecting my device so I decide to run the same adb version from cmd on Windows and then it finally appeared on my WSL. 

My maestro version: 1.31.1
adb version: 
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5ubuntu2
Installed as /usr/lib/android-sdk/platform-tools/adb

However I'm getting the following error:
![image](https://user-images.githubusercontent.com/37454798/203648478-cb15fb1f-5c58-40e3-b262-d1e61f38777c.png)

**Comment by Leland-Takamine** [comment]
Hey @mcoromac - Can you provide the details of your Android Emulator as well?

**Comment by mcoromac** [comment]
Hi @Leland-Takamine I'm not using an emulator. I figure I could use it with a device. I'm using a Huawei P30 Lite and have enabled USB Debugging (MTP) through developer options. Should I use an emulator?

**Comment by Leland-Takamine** [comment]
@mcoromac Yes that should work so we'll look into this. What Android version are you running on your Huawei device? And it's worth trying on an Emulator just to see if that works

**Comment by mcoromac** [comment]
@Leland-Takamine thanks for your quick response. I'm running Android 10 with EMUI version 10.0.0.
I'll try again with an emulator and comment again with my results.

**Comment by mcoromac** [comment]
I tried with an emulator but it didn't work. Same error. 

![emulator](https://user-images.githubusercontent.com/37454798/203853374-7b8c55fd-386f-4e7e-912a-afcc39c7876d.png)

I also installed the sample apk manually and ran "maestro test android-flow.yaml" but didn't work also.

**Comment by Leland-Takamine** [comment]
Ok we will take a look into this!

**Comment by Leland-Takamine** [comment]
There's been a lot of enhancements to the windows installation docs since this was opened. So I'll close this one out for now. But please do re-open if you continue to run into issues after following these instructions: https://maestro.mobile.dev/getting-started/installing-maestro/windows
