### ISSUE TITLE
Create test reports for a single test file

### ISSUE THREAD

**Issue by edgarlealbd** [mobile-dev-inc/maestro#439]
As of now, I can only [generate test reports](https://maestro.mobile.dev/cli/test-suites-and-reports#generating-reports) if my tests are inside a folder. I want to have a test report for single files as well, when I run this:

```
maestro test --format=junit test_file.yaml
```

**Comment by dmitry-zaitsev** [comment]
Being addressed in #441

**Comment by dmitry-zaitsev** [comment]
This is now possible in 1.16.0
