### ISSUE TITLE
Flutter TapOn Floating Action Button

### ISSUE THREAD

**Issue by nigamsiddhant** [mobile-dev-inc/maestro#449]
Hello Guys,

I'm using maestro in my flutter project for testing.
How can I tapon the FloatingActionButton?

```
FloatingActionButton(
                  heroTag: null,
                  onPressed: () {
                    Navigator.of(context).push(MaterialPageRoute(
                        builder: (BuildContext context) =>
                            const BottomSheet()));
                  },
                  child: const Icon(Icons.add),
                )

```

**Comment by spoeck** [comment]
You can use the Semantics-Widget or in your case just make a tooltip (also possible with the Tooltip-Widget):

```dart
FloatingActionButton(
    heroTag: null,
    onPressed: () {
      Navigator.of(context).push(MaterialPageRoute(
          builder: (BuildContext context) =>
              const BottomSheet()));
    },
    child: const Icon(Icons.add),
    tooltip: "open menu",
)
```

```yaml
# someFlow.yaml
- tapOn: "open menu"
```

**Comment by spoeck** [comment]
In addition:
To inspect my Flutter App with "Accessibility Inspector" was eye opening :D
<img width="462" alt="image" src="https://user-images.githubusercontent.com/8719777/208141321-b0e74fa9-47c8-478e-ac3d-6f39d0fe94fe.png">

**Comment by stevenosse** [comment]
> In addition: To inspect my Flutter App with "Accessibility Inspector" was eye opening :D <img alt="image" width="462" src="https://user-images.githubusercontent.com/8719777/208141321-b0e74fa9-47c8-478e-ac3d-6f39d0fe94fe.png">

Or you can use `maestro studio` ;)

**Comment by amanjeetsingh150** [comment]
Hey, @nigamsiddhant actually you can use the `semanticLabel` with the Icon that is child of `FloatingActionButton` and maestro should be able to find it. Example from the sample app:

```
FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add, semanticLabel: "fabAddIcon"),
)
```

and do something like:

```
tapOn: "fabAddIcon"
```

![Screenshot 2023-01-12 at 3 37 38 PM](https://user-images.githubusercontent.com/12881364/212038502-8e92eaba-b3f6-41c2-bc19-32d664c88a99.png)
