### ISSUE TITLE
Maestro can't type the letter "z" in the text fields

### ISSUE THREAD

**Issue by KrzysztofZiolek** [mobile-dev-inc/maestro#450]
Maestro can't type the letter "z" in the text fields after upgrading the version of maestro to 1.16.0

**Comment by dmitry-zaitsev** [comment]
We are preparing a Maestro 1.16.1 hotfix today

**Comment by erykrutkowski** [comment]
@dmitry-zaitsev one more suggestion to consider regarding this issue: shouldn't we add some fallback to `adb shell input text` you know just in cased currently parsed letter is diacritic character.

**Comment by dmitry-zaitsev** [comment]
The fix is live in Maestro 1.16.1, thanks for spotting it!
