### ISSUE TITLE
[Question] How to decrease delay between test steps?

### ISSUE THREAD

**Issue by orestesgaolin** [mobile-dev-inc/maestro#478]
We're implementing our first flows and noticed that the delay between steps is pretty long. It makes it relatively time consuming to validate and debug the flows. 

Is there any way to decrease this delay e.g. to 200-300 ms which is typically duration of our navigation transitions?

**Comment by Leland-Takamine** [comment]
Hey @orestesgaolin we are we constantly looking for ways to increase the efficiency if Maestro Flow execution, and we optimize for balancing reliability and speed under the hood. But there is no way currently to set the delay between steps manually.
