### ISSUE TITLE
Tap on button fails

### ISSUE THREAD

**Issue by vmalyi** [mobile-dev-inc/maestro#487]
I've got a very simple scenario which unfortunately fails and here is the excerpt from the flow:

```
- launchApp
- assertVisible: "Enjoy learning & get better grades!"
- tapOn: "Start now"
```

The "Start now" has not been found despite being clearly visible on the screen.

![Simulator Screen Shot - iPhone SE (3rd generation) - 2022-12-12 at 17 12 00](https://user-images.githubusercontent.com/1609148/207103267-f3458a10-efe8-4348-ac16-378e18c09efc.png)

Here are the relevant logs:
[maestro.log](https://github.com/mobile-dev-inc/maestro/files/10210164/maestro.log)

**Comment by Leland-Takamine** [comment]
@vmalyi We are working on a re-architecture of iOS support within Maestro that should resolve most issues with discovering onscreen elements. Would you be able to share a simulator build of your app with us to test and makes sure this is resolved on with the new implementation? If you are open to it, feel free to email be your zipped ".app/" simulator build to support@mobile.dev along with a link to this github issue

**Comment by vmalyi** [comment]
@Leland-Takamine, thanks for the quick response! 

Unfortunately, there is no way I can share the simulator build for you to verify behavior but will be happy to give it a try when you have the new implementation available.

Thanks!
