### ISSUE TITLE
Open app with deep link

### ISSUE THREAD

**Issue by BenedictP** [mobile-dev-inc/maestro#49]
Would be nice to be able to open the app with a deep link:

1. For some E2E tests, we are directly starting a flow with a deep link because the logic before is handled with a different E2E test.
2. We also want to E2E test if the apps open correctly when we send a deep link to the system.

**Comment by dmitry-zaitsev** [comment]
That is a good use case, let us think about how to add it 👍

**Comment by dmitry-zaitsev** [comment]
We have introduced an `openLink` command: https://maestro.mobile.dev/guides/using-maestro-cli/open-link
