### ISSUE TITLE
CLI 1.17 hangs on Windows

### ISSUE THREAD

**Issue by brutaldev** [mobile-dev-inc/maestro#490]
Executing CLI 1.16.4 using the provided batch file works well. When using 1.17.1 there is no output and the process just hangs.

Microsoft Windows [Version 10.0.22621.900] (Windows 11)
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

**Comment by dmitry-zaitsev** [comment]
Are you using a batch file or are you using WSL?

**Comment by brutaldev** [comment]
Using the batch file from a standard command-prompt (not Powershell).

**Comment by ArthurSav** [comment]
We have made a lot of improvements and fixes since, can you upgrade to the latest version of Maestro and try again? 
If you still experience issues, we can re-open this.  
Thanks again for using Maestro!
