### ISSUE TITLE
UINavigationBar not visible in monitor hierarchy

### ISSUE THREAD

**Issue by AmadorNavarro** [mobile-dev-inc/maestro#491]
I'm trying to tapOn a UIBarItem from a UINavigationBar, but it isn't visible. TapOn: point: is ok for left buttons, but not for right buttons because the screen's width is different for each simulator.

Do you know how tapOn navigation items?

Thank you.

P.D.: If you try to monitor hierarchy a system app like contacts, you obtain the same result. The NavigationBar is hidden.

**Comment by ArthurSav** [comment]
We have made a lot of improvements and fixes since, can you upgrade to the latest version of Maestro and try again? 
If you still experience issues, we can re-open this.  
Thanks again for using Maestro!
