### ISSUE TITLE
Elements not tappable on real Android device

### ISSUE THREAD

**Issue by fantpmas** [mobile-dev-inc/maestro#497]
We're having issues where some elements are not tappable on a real Pixel 4a device. Taps work on the same device when emulated and also work on iOS simulator. Using 1.17.2.

When inspecting the view using `studio` we get the warning `This element's width or height is 0 so you won't be able to tap on it.`

Here's an example:
![Screenshot 2022-12-13 at 16 08 29](https://user-images.githubusercontent.com/20792077/207377489-34e24dde-969e-4785-b183-10987d710df6.png)

You'll notice the buttons seem duplicated as well. I also cannot tap on them in the view on the left:
![Screenshot 2022-12-13 at 16 28 48](https://user-images.githubusercontent.com/20792077/207377614-ca427f8d-6f45-405a-9e11-183fdd97a966.png)

We don't have this issue on the same Pixel 4a device when emulated:
![Screenshot 2022-12-13 at 16 30 49](https://user-images.githubusercontent.com/20792077/207377761-1b14316c-d06b-4514-b4b3-8283ebe8c791.png)

Nor on iOS:
![Screenshot 2022-12-13 at 16 27 27](https://user-images.githubusercontent.com/20792077/207377822-2fcf0f7d-0870-4c1e-9159-44fe3faecd45.png)

**Comment by nazrdogan** [comment]
+1

**Comment by SelcukKayahan** [comment]
any updates on this issue? we might have the same problem..

**Comment by ArthurSav** [comment]
Hi everyone, can you update to the latest Maestro version `1.20.0` and try again? We released a fix

**Comment by reymalahay** [comment]
> Hi everyone, can you update to the latest Maestro version `1.20.0` and try again? We released a fix

@ArthurSav what was the solution to this issue?

please advise.

thanks in advance,
rey malahay

**Comment by ArthurSav** [comment]
Hi @reymalahay please open a new ticket describing your issues and the steps necessary to reproduce it.

**Comment by reymalahay** [comment]
> Hi @reymalahay please open a new ticket describing your issues and the steps necessary to reproduce it.

thank you, @ArthurSav 

i just cut issue ticket #1544 

kind regards,
rey malahay
