### ISSUE TITLE
Not able to upgrade CLI

### ISSUE THREAD

**Issue by UnitedWithCode** [mobile-dev-inc/maestro#503]
I have installed Maestro via script. As on December 14, 2022, it installed version 1.9.0. I tried to upgrade CLI by [these instructions](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli). It is still same version. Because of this version, I am not able to run record & studio functionality. I am testing this on WSL2.

![image](https://user-images.githubusercontent.com/32124107/207537946-6383cd7a-d1b1-4b99-b64b-0a9e6e41c2c8.png)

**Comment by axelniklasson** [comment]
@UnitedWithCode are you still experiencing issues with upgrading the CLI?

**Comment by axelniklasson** [comment]
Hi @UnitedWithCode, I'll go ahead and close this out for now. Please file a new bug report [here](https://github.com/mobile-dev-inc/maestro/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BMaestro+version%2C+e.g.+v1.2.3%5D) if you are still experiencing issues!
