### ISSUE TITLE
Not tapping tabs in a React Native app on Android

### ISSUE THREAD

**Issue by Almouro** [mobile-dev-inc/maestro#511]
Hi!
Most React Native apps will use React Navigation for tab based navigation (https://reactnavigation.org/docs/tab-based-navigation)

However, Maestro seems to fail to tap on tabs by text. 
I'm using Samung S10 Android 12
(No issue when tapping by text with Appium + UIAutomator2 + webdriverio in comparison 😕)

## To reproduce:

1. Init React Native project with `npx react-native@latest init TestNavigation`
2. Add tab based navigation following https://reactnavigation.org/docs/tab-based-navigation

Here's an example APK -> https://github.com/Almouro/maestro-react-navigation/blob/main/release.apk

## Actual results
- Test passes ✅
<img width="308" alt="image" src="https://user-images.githubusercontent.com/4534323/207926073-46e9e266-28d5-4caa-ab11-00c213110041.png">

- But tab stays unclicked ❌
<img width="453" alt="image" src="https://user-images.githubusercontent.com/4534323/207925736-4c244e4a-c0cd-4b07-b421-52c652abfbb6.png">

## Studio

Maestro Studio mentions the item seems to have zero height

![image](https://user-images.githubusercontent.com/4534323/207930945-3aa4feef-01c1-4aae-bfe1-ebeeaccdda72.png)

**Comment by Almouro** [comment]
Actually this works:

```
appId: "com.testnavigation"
---
- launchApp
- tapOn:
    containsChild: "Settings"
```

Is this expected? I would assumed `tapOn: "Settings"` to work or Maestro Studio to pick it up 🤔

**Comment by fantpmas** [comment]
Probably same issue as https://github.com/mobile-dev-inc/maestro/issues/497

**Comment by ArthurSav** [comment]
Hi everyone, can you update to the latest Maestro version 1.20.0 and try again? We released a fix

**Comment by Almouro** [comment]
This is indeed fixed, working as expected now, thanks! 🥳

**Comment by reymalahay** [comment]
> Actually this works:
> 
> ```
> appId: "com.testnavigation"
> ---
> - launchApp
> - tapOn:
>     containsChild: "Settings"
> ```
> 
> Is this expected? I would assumed `tapOn: "Settings"` to work or Maestro Studio to pick it up 🤔

HI all,

what if the tab contains an icon? i tried using `testID` but doesn't work.

how does on deal with this automation scenario?

please advise.

thanks in advance,
rey malahay
