### ISSUE TITLE
Getting started - Java

### ISSUE THREAD

**Issue by yonaskolb** [mobile-dev-inc/maestro#514]
Hello, this project looks cool. Just wanted to let you know that by purely following the installations instructions at https://maestro.mobile.dev/getting-started/installing-maestro I get an error about Java when running `maestro`. 
```
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.
```

**Comment by yonaskolb** [comment]
Just for info, after installing java my next hurdle is the error `Could not find emulator binary`
```
maestro test flow.yml
Could not find emulator binary
```
- idb_companion is running successfully
- xcode command line tools is installed:
```
xcode-select -p
/Applications/Xcode-14.2.0.app/Contents/Developer
```
Not sure if it's an Xcode 14.2 issue

**Comment by dmitry-zaitsev** [comment]
Could you try updating Maestro (by running the same install script) to 1.17.4? There was an issue in 1.17.3 that was just fixed

**Comment by yonaskolb** [comment]
Yep all good now, thanks

**Comment by donlingliang** [comment]
In case people have similar environmental issues before running maestro:
- Java installation: https://phoenixnap.com/kb/install-java-macos
- ADB is not found in **PATH** even Android Studio has been installed. https://stackoverflow.com/a/63987862
