### ISSUE TITLE
Network Mocking

### ISSUE THREAD

**Issue by pauloaapereira** [mobile-dev-inc/maestro#531]
Hello.

Is there any way to test an application using Maestro with network mocking?

Thanks.

**Comment by AKJAW** [comment]
You could prepare a mock flavor/version of your application and run maestro on that app variant

**Comment by pauloaapereira** [comment]
Thanks for the answer @AKJAW .

It seems there is also now an Experimental section on Network Mocking!
https://maestro.mobile.dev/advanced/experimental/network-mocking

I'll give those a try.
