### ISSUE TITLE
Maestro cannot recognize UITextField's placeholder text

### ISSUE THREAD

**Issue by likeSo** [mobile-dev-inc/maestro#549]
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/12247340/209897743-c7a65deb-cada-431b-982e-ffe6c39d55c6.png">

I was trying to tap on the search field by `- tapOn: Please input...`, but it failed

**Comment by amanjeetsingh150** [comment]
Hey @likeSo 

I have just merged the fix can you upgrade the local maestro to head and try these commands to check if this is fixed? To upgrade:
```
 brew uninstall maestro
 brew install maestro-head --HEAD
```
Let me know if this works will release this in the new version

To go back on stable after checking
```
 brew uninstall maestro-head
 brew install maestro
```

**Comment by likeSo** [comment]
How can i use this command?
```shell
➜  ~ maestro
zsh: command not found: maestro
➜  ~ maestro-head
zsh: command not found: maestro-head
```

**Comment by amanjeetsingh150** [comment]
Hmmm, this fails for me as well. I'll investigate fails separately. But since the fix works for me I'll release the recent one soon and update you on the thread

**Comment by amanjeetsingh150** [comment]
Hey @likeSo can you try this this should be available in new CLI version `1.18.5`. Feel free to reopen this issue if this still doesn't work!

**Comment by likeSo** [comment]
I don't know why, the behavior of maestro is still not correct, maybe because my text field is customized? 

In my app:
![QQ20230111-210047@2x](https://user-images.githubusercontent.com/12247340/211814872-ec4a7e50-6a2b-4c5a-a600-bb97905c7088.jpg)

In Safari:
![QQ20230111-205850@2x](https://user-images.githubusercontent.com/12247340/211814937-9d4771a3-4b40-4a5a-9d2e-894e79762b0e.jpg)
![QQ20230111-205810@2x](https://user-images.githubusercontent.com/12247340/211814990-fac75c84-d8d2-49a4-85c4-7a622c21c4c1.jpg)

**Comment by hkawii** [comment]
This issue still happening on the latest version, any idea how to fix it please ?

**Comment by ste7en** [comment]
still experiencing this issue
