### ISSUE TITLE
Ability to swipe starting at a view

### ISSUE THREAD

**Issue by Leland-Takamine** [mobile-dev-inc/maestro#55]
We have the ability to swipe via coordinates today, but that's brittle and difficult to figure out what the right coordinates are. It would be nice to be able to say "Swipe left 1 inch starting from this view".

https://user-images.githubusercontent.com/847683/184698348-76b5f575-37ba-4f6b-b9f3-4b39d2a0c907.mov

**Comment by amanjeetsingh150** [comment]
Hey @Leland-Takamine given we have the capability to swipe in directions now. Does a command like the following makes sense for this use case?

```
- swipe:
    direction: LEFT
    id: id_of_view_here
```

**Comment by MrRio** [comment]
Hey, the above would make sense for our use case also

**Comment by MrRio** [comment]
Would be good with 'direction' and 'distance' in pixels.

**Comment by amanjeetsingh150** [comment]
@MrRio Awesome I have added this to my backlog. Would be soon working on it.

**Comment by artur-borowiec** [comment]
How about a swipe with text parameter, just like tapOn? The center of a view could be an anchor point for the swipe.

**Comment by MrRio** [comment]
Yeah that'd also be good

**Comment by danielstr** [comment]
Hi! what is the status of this enhancement? This will be very useful for our app too :=

**Comment by amanjeetsingh150** [comment]
https://user-images.githubusercontent.com/12881364/211739413-0e6a6ca4-0c1e-4bbb-a4e6-74acad5d9399.mp4

This will soon be addressed with the following PR:

https://github.com/mobile-dev-inc/maestro/pull/585

It will allow to directionally swipe on elements like:

```
- swipe:
     direction: LEFT
     element:
          id: "identifier-of-some-element-here"
```
