### ISSUE TITLE
Issue with native alerts on iOS

### ISSUE THREAD

**Issue by supoved** [mobile-dev-inc/maestro#558]
Maestro Studio unable to detect any layout elements when native alert is displayed (see screenshot).
Also `tapOn` doesnt see text elements or buttons on alert.

<img width="836" alt="Screenshot 2022-12-30 at 16 45 53" src="https://user-images.githubusercontent.com/6122489/210095891-b9ad1dc6-790f-4ba6-b984-e319a5301873.png">

Selenium can deal with those with `driver.switchTo().alert()` is there any way to interact with Alert in Maestro?

Running on iOS emulator Iphone 14 (version 16.1)
Maestro: 1.18.3

**Comment by amanjeetsingh150** [comment]
Hmmm, strange actually maestro does support interacting with native alerts like permission dialogs etc. Can you send the binary and flow if possible on the [slack channel](https://docsend.com/view/3r2sf8fvvcjxvbtk)? Feel free to send on DM.

**Comment by ArthurSav** [comment]
We have made some improvements that should fix this issue. If you still experience issues, please open a new issue with reproduction steps.  Thanks again for using Maestro!
