### ISSUE TITLE
TapOn toolbar item clicks on notification instead

### ISSUE THREAD

**Issue by sunilson** [mobile-dev-inc/maestro#56]
Directly after starting our app a notification is shown because a foreground service is started. But also directly after starting the app I want to click on an item in the toolbar. Unfortunately most of the time maestro clicks on the notification instead of waiting until the notification is gone and the toolbar item is not obscured. Can I manually add some waiting time here or how can I handle this? Thanks!

**Comment by dmitry-zaitsev** [comment]
Thanks for sharing the context! We have some ideas on how to implement it and will address it in the next few days.

**Comment by dmitry-zaitsev** [comment]
@sunilson we have published a new Maestro version (1.3.0) that introduces an `assertNotVisible` command (https://maestro.mobile.dev/reference/assertions)

It will wait for a view to disappear within a certain timeout before moving on to the next command
