### ISSUE TITLE
"U+200b" chars in text copied from maestro studio

### ISSUE THREAD

**Issue by vmalyi** [mobile-dev-inc/maestro#563]
Hey there,

I've just gave maestro studio a try and noticed that for the buttons in our app, it copies the "U+200b" chars when I identify the element on the screen and use the copy function for e.g. `tapOn` command. Interestingly, that without those chars, the `tapOn` doesn't work/find the element on the screen. See details in video below: 

https://user-images.githubusercontent.com/1609148/210360738-f524d1a1-c920-439e-b88a-28ffaece701e.mov

The main inconvenience with this is that we need to _always_ use maestro studio to derive the e.g. `tapOn` commands for our buttons (even if the labels are obvious – e.g. "Next") which work with 100% probability.

**Comment by axelniklasson** [comment]
Hi there @vmalyi, are you still experiencing these issues?

**Comment by vmalyi** [comment]
> Hi there @vmalyi, are you still experiencing these issues?

Sorry, can't help here because we are not using the tool anymore.

**Comment by axelniklasson** [comment]
Ok, thanks for letting me know @vmalyi!
