### ISSUE TITLE
Landscape support for iOS

### ISSUE THREAD

**Issue by johntmcintosh** [mobile-dev-inc/maestro#565]
iOS testing currently does not support landscape mode. (I am not sure about the current status of landscape support with Android)

As a quick test, download the samples:

```
maestro download-samples
cd ./samples
unzip sample.zip
xcrun simctl install Booted Wikipedia.app
```

And update the iOS flow to:

```
appId: org.wikimedia.wikipedia
---
- launchApp
- tapOn: "Search Wikipedia"
- inputText: "tacos"
```

Launch the simulator and rotate into landscape mode, and then run:

```
maestro test ios-flow.yaml
```

The test reports that it passes, but it does not navigate into the search screen to type into the text.

Running `maestro studio` shows a mismatch where the overlay content appears to be laid out in landscape, but the image of the app's screen is rotated 90 degrees:

<img width="1624" alt="Screen Shot 2023-01-03 at 10 27 16 AM" src="https://user-images.githubusercontent.com/931283/210398728-31cc2696-57f3-4a69-87c5-7707f62d7394.png">

NOTE: This was discussed in a couple of slack threads, but I'm adding a ticket here so myself and anyone else interested can follow along for status updates or to be notified when support is available.
- https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1671032621327279
- https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1671642307201909

**Comment by mateioprea** [comment]
I have the same issue. I have an app that only runs in landscape mode on iPad and maestro mismatches all the elements. If I test with portrait orientation, everything works.

**Comment by kdsanchezv** [comment]
Hey guys, somebody knows if there is any progress regarding this issue?
That's the only blocker we have to use maestro in our tests.

**Comment by Guyentie** [comment]
I'm having the same issue for an Ipad app that is mainly used in landscape mode.

**Comment by Plimsky** [comment]
Hi there! 👋
I'm having the same issue with my project in which it's specifically designed in landscape mode. Is there any update or ongoing investigations about this? 
Thanks for the update! 👍

**Comment by meboev-fourth** [comment]
What is the status with this? It should be set with a high priority.
That's not an enhancement, it's a really nasty defect. It's been 6 months already, and no one has done anything about it.

**Comment by mdethlefs** [comment]
same issue. we have a video player we can toggle to fullscreen and all the elements are mismatched in maestro studio

**Comment by ccfiel** [comment]
oh I see still no update :(

**Comment by ccfiel** [comment]
Still no updates? Is there any roadmap of the project?

**Comment by ccfiel** [comment]
This is fine in android in iOS was not fine, it will just complete the steps but not executed in the emulator. See video.

[Untitled_ Jul 18 2023 3_36 PM.webm](https://github.com/mobile-dev-inc/maestro/assets/1788360/f1656000-673d-4cd7-8290-943cf74d3306)

**Comment by mdethlefs** [comment]
any updates?
we have a video player in our app and we basically can't test anything in fullscreen mode because of this. both iOS and Android.

**Comment by ericledonge** [comment]
I have issue with Android tablet in Maestro Cloud (everything is fine in local).

**Comment by raymond-tetteh** [comment]
I have the same issue. When is this going to be worked on?

**Comment by dinisnunes1** [comment]
Is there any news on this feature? It's really preventing us for use Maestro for our UI tests.

**Comment by davemess** [comment]
+1

**Comment by chiefchief** [comment]
have the same issue on iPad in landscape orientation, any updates?

**Comment by barbaramartina** [comment]
Hello, when do you think that landscape support will be in your pipeline? With the new European Legal Regulations on Accessibility, applications will need to support landscape by June 2025. It would be great to be able to test in landscape at least a couple of month before. Thanks

**Comment by bartekpacia** [comment]
related #1679

**Comment by chiefchief** [comment]
doesn't work on iPad

**Comment by bartekpacia** [comment]
re-opening as this had to be reverted in v1.37.9

**Comment by tkhvaira** [comment]
good day, any movement with this issue, really looking forward to this fix

**Comment by bartekpacia** [comment]
This is already fixed on our `main` branch. See PRs #1974 and #2050.

**Comment by bartekpacia** [comment]
We'll release this soon as part of Maestro version 1.39.

**Comment by barbaramartina** [comment]
Thanks. When is the version going to be released?

**Comment by klyovan** [comment]
> Either tomorrow or next week.

Hi Bartek, just checked your unreleased version (CLI 1.39.0-dev.1) and now the landscape works fine, but the native popups are not displaying correctly and it is also not possible to click on them with Maestro, could you please check this case ?  
<img width="533" alt="Screenshot 2024-09-12 at 21 34 53" src="https://github.com/user-attachments/assets/718e9bac-9dfb-4e5a-88d5-ca437912e99e">
Tested on simulator: Ipad Pro 11-inch (M4) 
This popup is called by native code but invoked from `Flutter` using platform channel
If I try to debug it using `maestro studio`, I can see that the nodes for `cancel` and `continue` an item exist on the screen, but they are flattened and positioned to the left and below, but still not clickable using either the studio or the yaml file.

**Comment by bartekpacia** [comment]
The currently available draft version doens't reflect the latest master. Let me relase a new one in a few minutes.

**Comment by bartekpacia** [comment]
Please check out `v1.39.0-dev.2`:

```console
brew update
brew install maestro@1.39-dev.2
```

**Comment by klyovan** [comment]
The issue with native popup still there 
<img width="233" alt="Screenshot 2024-09-13 at 08 21 20" src="https://github.com/user-attachments/assets/9b7fe9be-07b9-4764-8a16-392adf971dac">

**Comment by bartekpacia** [comment]
@klyovan Please create a new issue (and reference this one)
