### ISSUE TITLE
No ability to `launchApp` with  Intent/Process arguments

### ISSUE THREAD

**Issue by retyui** [mobile-dev-inc/maestro#569]
one thing that block us to move away from Appium is "launch" arguments 

[react-native-launch-arguments](https://github.com/iamolegga/react-native-launch-arguments)

```tsx
capabilities: {
  optionalIntentArguments: `--ez myBool true --es myStr 'string text'`, // Android
  processArguments: {args : ['-myBool', 'true','-myStr', 'string text']}, // iOS
}
```

android: Additional intent arguments that will be used to start activity. 
- http://developer.android.com/reference/android/content/Intent.html

ios: Arguments to pass to the AUT using instruments

links
- https://maestro.mobile.dev/reference/app-lifecycle#launchapp
- http://appium.io/docs/en/writing-running-appium/caps/

**Comment by jbentonGx** [comment]
Not being able to pass launch arguments when launching the app is also an issue for me.

**Comment by kunalverma25** [comment]
Same here for iOS..
Having support for launchArguments is really important..
