### ISSUE TITLE
Not able to test dynamic links on Android

### ISSUE THREAD

**Issue by lhimo** [mobile-dev-inc/maestro#588]
I'm trying to use the `openLink` functionality but the app I am testing does not open up. If I try manually from adb instead, when I add the parameter `-a android.intent.action.VIEW` the app opens fine.

Would this something that can be added as default or through an additional method?

**Comment by Natanaelvich** [comment]
that would be great, same thought #586

**Comment by Natanaelvich** [comment]
available in Release [CLI 1.19.0](https://github.com/mobile-dev-inc/maestro/releases/tag/cli-1.19.0)
