### ISSUE TITLE
It does not work on Android Tv

### ISSUE THREAD

**Issue by dev-sharma-deltatre** [mobile-dev-inc/maestro#594]
I tries on tv application and it does not work perfectly.

**Comment by stevenosse** [comment]
Hello
I think you should provide more details. maestro version ? the tests you performed ? what went wrong ?

**Comment by dev-sharma-deltatre** [comment]
@stevenosse sure. I cannot find any document where I can find commands to navigate the TV remote. It is all just tap and scroll movements no support for android tv remote.

**Comment by amanjeetsingh150** [comment]
Hey @dev-sharma-deltatre not sure what commands you are looking for exactly. But there are set of commands we support for android tv: https://maestro.mobile.dev/reference/keyboard#android-tv.

**Comment by amanjeetsingh150** [comment]
Closing this for now. Feel free to open issue for any feature you find missing.
