### ISSUE TITLE
[iOS] Populate the XCUIApplication `launchArguments`

### ISSUE THREAD

**Issue by ashraf-ct** [mobile-dev-inc/maestro#608]
Is it possible to be able to populate the XCUIApplication `launchArguments` using maestro? - [Apple Doc](https://developer.apple.com/documentation/xctest/xcuiapplication/1500477-launcharguments)

    /**
     * The arguments that will be passed to the application on launch. If not modified, these are the
     * arguments that Xcode will pass on launch. Those arguments can be changed, added to, or removed.
     * Unlike NSTask, it is legal to modify these arguments after the application has been launched. These
     * changes will not affect the current launch session, but will take effect the next time the application
     * is launched.
     */
    open var launchArguments: [String]

I don't believe the [launch parameter](https://maestro.mobile.dev/reference/app-lifecycle#launchapp) in maestro allows us to do this.

**Comment by kunalverma25** [comment]
@axelniklasson launchArguments are really important in iOS testing..
Many things like rating popups, some custom user flows etc are suppressed/modified in many major iOS codebases for UI testing using launchArguments..
Almost all UI Testing frameworks support launchArguments like Appium etc..

This issue actually breaks a lot of flows where things like asking the user for ratings are randomly done..

**Comment by ainame** [comment]
I just saw a comment on the community Slack that this is now being implemented.
https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1679672795356359?thread_ts=1679628715.242669&cid=C041FU72T54

**Comment by axelniklasson** [comment]
Great news everyone, maestro now supports [Launch arguments](https://maestro.mobile.dev/api-reference/commands/launchapp#launch-arguments) in `1.27.0`. Please [upgrade to the latest maestro version](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) to try it out!
