### ISSUE TITLE
Migrating React Native app from Detox to Maestro

### ISSUE THREAD

**Issue by jpudysz** [mobile-dev-inc/maestro#616]
Hello maestro team!

I started migrating one of the app's E2E tests from Detox to Maestro.
So far, I'm happy with the result, although I have one blocker and two issues.

I love how I can specify test cases in the yaml file rather than awaiting everything in detox.

**Blocker:**
I have advanced SMS OTP flow, and I need somehow to mock the network or detect maestro.
I can't use network mocking as my React Native's metro bundler can't reach the app.
I also couldn't find a way to pass env from maestro to React Native app in a way [detox](https://www.npmjs.com/package/react-native-is-detox) can do it.

How can I detect that maestro is running the app?

**Issues**
1) Drawer from react-navigation is always visible for maestro even though it's pushed out of the visible screen
2) Nested `testID` (accessibilityID) in React Native cannot be reached from the maestro. The maestro can only see top-level ID.

Thank you for the hard work, and I hope there is a way to overcome my Blocker. I will happily test new versions of the maestro.

**Comment by Leland-Takamine** [comment]
Thanks for surfacing these issues @jpudysz! We'll be taking a look a look into these issues this week. In the meantime, feel free to join our Slack channel where we can help answer any other questions you have: https://docsend.com/view/3r2sf8fvvcjxvbtk
