### ISSUE TITLE
Clean up files on run by folders

### ISSUE THREAD

**Issue by julioexacta** [mobile-dev-inc/maestro#637]
I work with a login scheme that uses wso2, when I need to perform a test sequence where I need to change my logged in user, I used the clear command pointing to my device's browser, to be able to log out of my app's user. Running my test file by file this method works perfectly, however when I try to run this test through the folder clear does not clean my user section and it is not logged out, which makes only my first file work and all others fail .

**Comment by axelniklasson** [comment]
Hi there! You can use the `clearState` command to clear out app files between runs ([docs](https://maestro.mobile.dev/api-reference/commands/launchapp)):

```yaml
- launchApp:
    clearState: true
```
