### ISSUE TITLE
docs: is idb still required?

### ISSUE THREAD

**Issue by walkerdb** [mobile-dev-inc/maestro#640]
A [recent blog post on blog.mobile.dev](https://blog.mobile.dev/maestro-re-building-the-ios-driver-603998b012e8) discusses how the ios driver was rebuilt to stop relying on facebook's idb tool (amazing work btw), but the documentation [still says to install the `idb-companion` library via brew](https://maestro.mobile.dev/getting-started/installing-maestro#connecting-to-your-device).

Is idb actually still required for maestro to drive ios sims?

**Comment by amanjeetsingh150** [comment]
Hey, @walkerdb yes idb is still required. We ar in process of migration so it would might take time to totally get rid of it.

**Comment by walkerdb** [comment]
got it - thanks for the quick response!
