### ISSUE TITLE
Support for different bundle identifiers on different platforms

### ISSUE THREAD

**Issue by markrickert** [mobile-dev-inc/maestro#645]
I have a react-native app that builds from the same source but has different bundle identifiers for ios and android. 

Is there any way to specify this so that I don't have to mass update the script files with the new bundle id each time i want to switch platforms?

When running the `maestro` command, it'll ask me if i want to run the script on ios or android (if they're both running) but the tests always fail on the platform that differs from the maestro bundle id configuration.

Is what i'm trying to achieve currently possible?

Ideally, instead of:

```yaml
appId: my.ios.bundleId
```

At the top of the script files, we should be able to set them independently for the different platforms:

```yaml
- appId: 
  - ios: my.ios.bundleId
  - android: my.android.bundleId
```

**Comment by dmitry-zaitsev** [comment]
This is possible via env arguments. For example, if your flow is as following:

```
appId: ${APP}
---
- launchApp
```

You can choose which app to launch by providing a `-e APP={your app id}` option. For example:

```
maestro test -e APP=my.ios.bundleId flow.yaml
```
