### ISSUE TITLE
investigation: number/integer support for ENV values for dynamic index

### ISSUE THREAD

**Issue by JigneshWorld** [mobile-dev-inc/maestro#649]
To reuse this for multiple common steps, I am thinking of passing integer value as an env variable in nested flow.
But I am getting this error. Hence, I guess all env variables are considered strings and I can’t pass numbers for the index

e.g. index 
![Screenshot 2023-01-20 at 5 18 33 PM](https://user-images.githubusercontent.com/7347854/213706188-fb8922f7-1cd9-4cea-876e-337486a62f93.png)

![Screenshot 2023-01-20 at 5 20 05 PM](https://user-images.githubusercontent.com/7347854/213706183-d4ab4db4-9df5-4bfd-9fdb-28a9389f8795.png)

**Comment by dmitry-zaitsev** [comment]
This is available in the latest Maestro version

**Comment by JigneshWorld** [comment]
Thank you @dmitry-zaitsev 🎉
