### ISSUE TITLE
Swipe commands break the framework (iOS)

### ISSUE THREAD

**Issue by michalchudziak** [mobile-dev-inc/maestro#650]
After upgrading to maestro `1.19.5` (from 1.18.5), swiping on iOS seems to break the framework. A simple command:

```
- swipe:                 
    start: 100, 700
    end: 100, 400
```

results in a framework freeze and the following error:

![image](https://user-images.githubusercontent.com/7837457/213721720-ac628d03-fee3-406b-917c-de94390bcba9.png)

The cloud builds could also be affected, as they're marked as `Canceled`.

**Comment by dmitry-zaitsev** [comment]
Could you try to use swipe from element ([docs](https://maestro.mobile.dev/reference/scroll-and-swipe#swiping)) to see if that fixes your problem? I suspect that what happens here is coordinates are outside of screen bounds and are therefore failing the test.

Also, could you tell us more about your app? Is it it native app? React Native? SwiftUI?

**Comment by michalchudziak** [comment]
Hey, restarting my mac helped fix the issue. Swipes seem to work well now. Thanks
