### ISSUE TITLE
Swipe in direction from point

### ISSUE THREAD

**Issue by tenhobi** [mobile-dev-inc/maestro#654]
Hello, I could not figure out how to swipe in a direction from some starting point. For example, when I want to swipe a drawer from left of the app. A cannot set up start/end, because I do not know how big the screen might be and using too high value for x axis can throw an error on iOS or using too low value for x axis would not open the drawer.

Aka I would want something like 

```
- swipe:
    direction: RIGHT
    from: 
       point: 0, 300
```

or 

```
- swipe:
    direction: RIGHT
    start: 0, 300
```

but that does not seem to work for me. 🤔 So, is there some way to do it. Or, is it even a way to do in integration testing?

**Comment by artur-borowiec** [comment]
I think that for now you can run:
`- swipe:
    direction: RIGHT`
It just swipes through almost whole width of the screen. Works for me in Android, closes the drawer correctly (but the direction is left).

Or you can find a specific (anchor) view at which you will start the swipe:
`- swipe:
    direction: RIGHT
    from: 
       id: "item_identifier"`

Using coordinates seems to be limited to using both start AND end params.

**Comment by tenhobi** [comment]
Hey @artur-borowiec, thanks for tips.

According to https://maestro.mobile.dev/reference/scroll-and-swipe, swipe in direction by default does
> RIGHT: This command swipes in the right direction in the middle of the device.

Since I have horizontal scrollable (with like 16px margin around) on the page, it does not work and the scrollable is scrolled. I want to start the swipe in the first 16px, so a drawer is opened. Of course I can also specify start and end coords, but that's a bit problematic because the end coordinate can exceed the screen limit that produces an exception. :)

I also cannot use id, cause I use Flutter that does not expose them, neither would any other app I would want blackbox test have for this use case anyway.

**Comment by dmitry-zaitsev** [comment]
cc @amanjeetsingh150

**Comment by amanjeetsingh150** [comment]
Hey, @tenhobi can you check if you can use relative swipe with percentage?

Docs: https://maestro.mobile.dev/reference/scroll-and-swipe#relative-swipe-using-percentages

This can be configured agnostic to screen. If the normal swipe right doesn't work this percentage one can be used to try with different combination of x and can be configured for multiple screens since it works on percentage.

**Comment by tenhobi** [comment]
Hey, yes, that works!

I am not sure that it is needed, so an idea above my current needs: could it be possible to let set one be absolute while the other be relative? For example, if I would know where some element is in absolute measures and want to / need to swipe to the center bottom, then I would like to use something like 

```yaml
- swipe:
    start: 20, 35
    end: 50%, 100%
```

Which is currently not possible while throwing `java.lang.IllegalArgumentException: You need to provide start and end coordinates with %`.

**Comment by dmitry-zaitsev** [comment]
I would say using absolute coordinates is not a good idea in general as it will make your tests dependent on an exact device type

**Comment by amanjeetsingh150** [comment]
Closing this as solved, feel free to open if something comes up 🙌
