### ISSUE TITLE
Maestro stays loading indifinetely

### ISSUE THREAD

**Issue by LockedDB** [mobile-dev-inc/maestro#655]
**Version:** 1.19.5

**Enviroment:** Mac OS Ventura - M1

**Steps to reproduce:**

https://user-images.githubusercontent.com/56168736/213909217-6574ba70-29ed-4ef9-90bf-43d0c6c34ef3.mov

**Additional Information:** 
- No commands work with maestro it always stays loading.
- `JAVA_HOME` set to `/usr` or `/usr/` behaviour is the same.
- Also waited for 13 minutes and no response.

**Comment by dmitry-zaitsev** [comment]
This is really odd. Could you please:

- Share your `java -version`
- Share output of `ls ~/.maestro`
- Just to be sure, try to reboot your Mac and try again in case if there is some weird locked file somewhere

**Comment by LockedDB** [comment]
Yep, when checking the `java -version` the behaviour was the same. So I checked with other `JAVA_HOME` paths and now it works.

Thanks for the help.
