### ISSUE TITLE
Documentation: timeout information in conditional runFlow

### ISSUE THREAD

**Issue by javalnanda** [mobile-dev-inc/maestro#662]
It would be nice to include information about the default timeout in case of [conditional runFlow](https://maestro.mobile.dev/advanced/conditions#runflow-conditionally).

Currently, android flow marks the step as `skipped` after some default timeout ~7 seconds and on iOS side it waits forever. It would be good to include the information about the default timeout in the documentation 🙂

**Comment by javalnanda** [comment]
This issue seems to be related to iOS. iOS might not be waiting forever but asserting true even though element is not visible on the screen.
https://github.com/mobile-dev-inc/maestro/issues/663

**Comment by axelniklasson** [comment]
Hi there @javalnanda. This is something that might be subject to change as we make changes to the maestro internals so documenting this as it stands today would not be too much help for users. Thanks anyway!
