### ISSUE TITLE
`assertVisible` returns true even if element is not visible on screen - iOS (SwiftUI)

### ISSUE THREAD

**Issue by javalnanda** [mobile-dev-inc/maestro#663]
In case of iOS(SwiftUI), `assertVisible` returns true if the element is in the view hierarchy but not yet visible on the screen.
Use cases:
- Element animating into the visible area after X condition
- Elements on the scrollview outside of visible area

Validated in maestro studio, the elements not yet on screen are shown in the `UI Elements` list. Pls refer to the screenshot below where the `Get started` button is not yet visible on the screen but it is shown in the maestro studio.

<img width="1715" alt="Screenshot 2023-01-24 at 4 54 35 PM" src="https://user-images.githubusercontent.com/1729042/214279797-08a939e5-f457-4df5-945e-8a5ad049cb72.png">

**Comment by danielleitelima** [comment]
This issue is most like related to #668 .

**Comment by javalnanda** [comment]
@danielleitelima yes, scrollUntilVisible and assertVisible would be using same api to check if element is visible under the hood.

**Comment by dmitry-zaitsev** [comment]
cc @ArthurSav

**Comment by ArthurSav** [comment]
- `scrollUntilVisible`  Fix will be deployed today
- `assertVisible` Fix will be deployed within the week.

**Comment by axelniklasson** [comment]
Thanks for taking the time to raise this issue! This bug is fixed but if you still experience issues after [upgrading to the latest version of Maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli), please open a new issue with reproduction steps. Thanks again for using maestro!
