### ISSUE TITLE
Maestro failed to find the text on badge in bottom nav bar

### ISSUE THREAD

**Issue by hjkwak-kitty** [mobile-dev-inc/maestro#667]
## Description

It failed to find the text on the bottom nav item badge
`- extendedWaitUntil:
    visible:
      text: "1"
      below:
        id: "nav_host_container"
    timeout: 10000`

<img width="73" alt="image" src="https://user-images.githubusercontent.com/20948981/214326848-7900a130-6804-4567-b83d-4a421a57ea8f.png">

## Expected
I'd like to get the badge count visibility with the text

**Comment by dmitry-zaitsev** [comment]
Please make sure the badge is reported as a view with enabled accessibility properties. I.e. if you are drawing text manually on canvas it will not be visible to Maestro
