### ISSUE TITLE
"scrollUntilVisible" not working as expected on iOS.

### ISSUE THREAD

**Issue by danielleitelima** [mobile-dev-inc/maestro#668]
Tested both, Android and iOS. The command `scrollUntilVisible` works perfectly on Android, as far as I know, but on iOS it doesn't perform any change in the UI state. After investigating the hierarchy using `maestro studio` I could verify that all of the views in the scrollable screen appear on it for iOS. This is not the case for Android. I suspect that this is the reason why this feature is not working.

**Comment by dmitry-zaitsev** [comment]
This should be fixed in 1.21.3
