### ISSUE TITLE
After updating to the new version 1.20.0, the performance became very slow

### ISSUE THREAD

**Issue by Yuldoshev** [mobile-dev-inc/maestro#672]
test steps are running very slowly, for example inputText: "Hello" takes a long time to load

**Comment by BrentMifsud** [comment]
same here. I have a step that types in a large amount of text and it actually times out!

**Comment by Leland-Takamine** [comment]
@Yuldoshev Can you please try again on 1.21.1 - we've just published a fix for this. Please reopen if this doesn't resolve your issue!

**Comment by Yuldoshev** [comment]
Yes of course but new version tapOn: "16%,31%" given, this is not clear, it would be better if it is given with text or some other key, there is a problem with inputText again
