### ISSUE TITLE
Question: Flutter + WebViews

### ISSUE THREAD

**Issue by jakeBrightHR** [mobile-dev-inc/maestro#692]
Couple of questions,

- Can Maestro handle WebViews within Flutter apps?
- Can Maestro handle native Android and iOS permission dialogs?

**Comment by Alpaca00** [comment]
The first question @jakeBrightHR: it doesn't work for me,
the second question also has an interesting answer.

**Comment by bartekpacia** [comment]
Hi @jakeBrightHR :)

Both use cases work in my simple, example app.

**Comment by jakeBrightHR** [comment]
> The first question @jakeBrightHR: it doesn't work for me, the second question also has an interesting answer.

Haha, so what is the answer to the second question?

**Comment by amanjeetsingh150** [comment]
Hey @jakeBrightHR answer to both of the questions should be yes, that is expected. If something doesn't work, can you open a separate issue for reproducing it. Closing this for now since the question is answered.
