### ISSUE TITLE
Cant find a way to unlock - draw patterns

### ISSUE THREAD

**Issue by GiwrgosMpartsas** [mobile-dev-inc/maestro#693]
Hey there guys and excellent work so far! So, in our mobile app we have to draw a pattern with at least 4 dots filled, but there is no way to hold tap and draw a pattern. any possible solutions (that you have now) or in the future? 

Thanks

**Comment by artur-borowiec** [comment]
I was thinking about:
- press, release and move commands to let the user manually handle the swipe (press on a point, move to another point and release)
- "to" parameter for swipe command - to specify where to end the swipe

**Comment by astroboy0803** [comment]
I have same question, how can fix it?
do you have any sample code?

**Comment by GiwrgosMpartsas** [comment]
I have no idea, never found the solution.
I'm not using maestro anymore, I'm on appium now
________________________________

**Comment by astroboy0803** [comment]
> I have no idea, never found the solution. I'm not using maestro anymore, I'm on appium now
> […](#)

Oh no, it’s so sad 😭
But thanks for your answer👍

**Comment by angelos3lex** [comment]
@amanjeetsingh150 is there any roadmap to support such gestures? tap on one point, swipe to another, and then directly to another etc, without lifting the tap?
