### ISSUE TITLE
The `waitForAnimationToEnd` check passes despite the animation still being played

### ISSUE THREAD

**Issue by Concert0** [mobile-dev-inc/maestro#697]
As per title. Video below to demonstrate the point.
Maestro version: `1.21.1`

https://user-images.githubusercontent.com/12480883/215080985-bca8e20b-9c20-4c9d-b4ee-8a03e22977de.mov

**Comment by dmitry-zaitsev** [comment]
The command has a default timeout of 15s that can be customized:

```
- waitForAnimationToEnd:
      timeout: 30000 # 30s
```

**Comment by Concert0** [comment]
I'd expect the default behaviour to be a failure rather than a pass. What's the reason for the opposite implementation?

**Comment by Concert0** [comment]
@dmitry-zaitsev 🙏

**Comment by dmitry-zaitsev** [comment]
@artem888 how about adding an assertion for checking whether screen is static?

Something like:
```
- assertScreenIdle
```
