### ISSUE TITLE
Unable to click on half link text

### ISSUE THREAD

**Issue by Vinay08sharma** [mobile-dev-inc/maestro#714]
![Screenshot 2023-01-31 at 4 34 40 PM](https://user-images.githubusercontent.com/65557772/215743354-f4f5014a-d980-4a8c-9413-e3ae1148c324.png)
Unable to click on sign in button since it is a part of the label.

**Comment by Vinay08sharma** [comment]
We will need a support to use link text for clicking.

**Comment by axelniklasson** [comment]
My recommendation here would be to either
- split the elements into two elements and add an id to the `Sign in` text and then tap on that
- tap on the point ([docs](https://maestro.mobile.dev/api-reference/commands/tapon))
