### ISSUE TITLE
[Enhancement] - Be able to define execution order within folder or execute alphanumerically

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#715]
When running flows from a folder/suite, execution of flows appears to be random and doesn't run them alphanumerically or even by creation date.

It would be great to execute them alphanumerically or be able to define the order somehow.

**Comment by simon-gilmurray** [comment]
Slack thread:
https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1675175829501559

**Comment by KrisLau** [comment]
@whlk What about if I don't want it to be alphabetical? I want to be able to custom control the order?

**Comment by axelniklasson** [comment]
@KrisLau This is something that we're actively looking into internally, so stay tuned for future updates on custom execution ordering of Flows!

**Comment by KrisLau** [comment]
@axelniklasson Okie cool, thanks!
