### ISSUE TITLE
Using argument on appId

### ISSUE THREAD

**Issue by josinaldobarbosa** [mobile-dev-inc/maestro#717]
is possible to pass arg to appId?
```
appId: ${PACKAGE}
---
- launchApp
- tapOn: "Send"
```
`maestro test -e PACKAGE="com.mypackage" test.yaml`

**Comment by amanjeetsingh150** [comment]
Yes @josinaldobarbosa it should be possible to pass that in env variable. Did you faced any difficulty?

**Comment by josinaldobarbosa** [comment]
@amanjeetsingh150 update to latest version and now it works thanks
