### ISSUE TITLE
don't work manual swipe window

### ISSUE THREAD

**Issue by Yuldoshev** [mobile-dev-inc/maestro#718]
the manual scrolling function is not working, i.e. it is not possible to manually scroll through the screen in maestro studio, the app in the emulator

**Comment by Leland-Takamine** [comment]
Hey @Yuldoshev would you be able to share more information about the issue you're running into? A reproducible test case would be very helpful for us to debug this! Thanks!

**Comment by axelniklasson** [comment]
Hi @Yuldoshev, I'll go ahead and close this out for now. Please file a new bug report [here](https://github.com/mobile-dev-inc/maestro/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BMaestro+version%2C+e.g.+v1.2.3%5D) if you are still experiencing issues!
