### ISSUE TITLE
[Enhancement] - Improve assertTrue/JavaScript debuggability by providing further info or allowing a console.log()

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#725]
Currently trying to debug `- assertTrue` statements is very difficult as upon failure you just get an `Assert that false is true`

Using JavaScript variables also only displays the variable name before the statement gets evaluated, so being able to work out what values are there is quite tricky.

Suggestions:
- Improve assertTrue output by including the actual comparison:
`Assert that false is true (Assert that 3 is 4)`

- Allow some form of console.log() to be able to output these variables to the command line for quick debugging

**Comment by Iannnr** [comment]
+1 for `console.log()` especially when making API requests, being able to log the response would be very helpful

**Comment by simon-gilmurray** [comment]
Slack thread for reference:
https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1675252434471829

**Comment by Leland-Takamine** [comment]
It's now possible to see `console.log` messages in the flow output! Please upgrade to the [latest maestro version](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) to try it out!
