### ISSUE TITLE
[BUG] - Launching app with clearState: true is still crashing the app on every subsequent startup

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#732]
Using 

```
 - launchApp:
    clearState: true
```

makes the app crash on every subsequent open

**Comment by simon-gilmurray** [comment]
Slack threads and others experiencing same issue:

https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1672762188380479

https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1674121973358979

https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1674480226578929

https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1673881720161289

**Comment by dmitry-zaitsev** [comment]
Could you please give Maestro 1.22.1 a try and see if that is still the case?

**Comment by simon-gilmurray** [comment]
This looks to be fixed on 1.22.1, thanks @berikv and @dmitry-zaitsev
