### ISSUE TITLE
Maestro don't clickible image item or text title

### ISSUE THREAD

**Issue by Yuldoshev** [mobile-dev-inc/maestro#737]
Don't click selected item in ios simulator image, title or icon

**Comment by amanjeetsingh150** [comment]
Hey, @Yuldoshev thanks for reaching out. Can you share the steps to reproduce?

**Comment by Yuldoshev** [comment]
I of course
When you click on the item marked in red, there is no change, in the rest it only shows percentage, it is not android only, only ios is the problem
https://user-images.githubusercontent.com/15108480/216937779-3f0d0f86-dbc7-4cdb-946f-13d1052b5983.png

**Comment by amanjeetsingh150** [comment]
Hmmm, few questions:
- Is this react native or native iOS? Is it swift UI?
- Is this text the accessibility label for the item? 
- Can you try with some identifier?

```
-tapOn: "0 'zbekcha"
```

**Comment by Yuldoshev** [comment]
this is Flutter

**Comment by Yuldoshev** [comment]
- tapOn: "0 'zbekcha"
this working

**Comment by amanjeetsingh150** [comment]
@Yuldoshev thanks for the context. Do you mean executing this from cli works but not from studio?

**Comment by Yuldoshev** [comment]
from maestro studio and cli

**Comment by Yuldoshev** [comment]
Yes, it is partially solved, but in IOS Simulator it is only calculated with percentages, why can't I get paths in ios like in Android?

**Comment by amanjeetsingh150** [comment]
Sorry didn't get the question. With which path you want to access the widget?

**Comment by Yuldoshev** [comment]
when i select a custom item in maestro studio it should get the path for that item right? but on my screen it shows the location of that item in percent, for example
- tapOn:
    point: "93%,15%"
Is it possible to get it through the title in the item?

**Comment by Yuldoshev** [comment]
https://user-images.githubusercontent.com/15108480/216967673-87a2c6dd-bede-4ffe-b5d5-b782ee4869be.png
this 
as you can see in this image it is not clicking when clicked


thanks this link
https://maestro.mobile.dev/platform-support/flutter

**Comment by amanjeetsingh150** [comment]
I believe it should be possible with text or an accessibility label. Can you try the steps in the docs and let me know if this works?

**Comment by Yuldoshev** [comment]
Yes, I am appealing to you because it does not work with these texts.
In similar cases, it is not clicked with texts
Then how can I manage the waiting time effectively so it should wait until the app loads before moving to the next step

**Comment by amanjeetsingh150** [comment]
> Yes, I am appealing to you because it does not work with these texts.
> In similar cases, it is not clicked with texts

Did you try semantic labels as well?

> Then how can I manage the waiting time effectively so it should wait until the app loads before moving to the next step

Maestro has a tolerance for this type of flakiness so it implicitly waits for a certain time, till the elements are visible. See the link here: https://maestro.mobile.dev/#why-maestro

**Comment by Yuldoshev** [comment]
ok thanks all nice working

**Comment by amanjeetsingh150** [comment]
Awesome 👍 Feel free to reach out if something doesn't work
