### ISSUE TITLE
brew couldn't find maestro

### ISSUE THREAD

**Issue by pushpender-singh-ap** [mobile-dev-inc/maestro#758]
![Screenshot 2023-02-09 at 2 18 16 PM](https://user-images.githubusercontent.com/73298854/217762202-51f0f36c-3952-47f3-84e5-bc40463e48f3.png)

**Comment by pushpender-singh-ap** [comment]
Hey @amanjeetsingh150 after this command it's working brew install maestro but homebrew install section is missing in documentation.

Website:- https://maestro.mobile.dev/getting-started/installing-maestro

<img width="301" alt="Screenshot 2023-02-09 at 4 17 38 PM" src="https://user-images.githubusercontent.com/73298854/217791634-8aa8ad53-b1bc-48bc-8069-3702ab779ed4.png">

**Comment by amanjeetsingh150** [comment]
Hey @pushpender-singh-ap, the recommended way is to do it via the curl since it also tells you about any missing dependencies and upgrades:

https://maestro.mobile.dev/getting-started/installing-maestro#installing-the-cli
