### ISSUE TITLE
Golden testing - compare screenshots

### ISSUE THREAD

**Issue by ben-milanko** [mobile-dev-inc/maestro#762]
I'm finding this library super helpful!

Along with the `-takeScreenshot` command, it would be helpful if we could compare one screenshot to another during a test.

Currently I'm doing this with the following bash script.

```bash
FILE="integration_test/maestro/actual.png"

if [ ! -f "$FILE" ]; then
    echo "FAILED: actual.png screenshot does not exist."
    exit 1
fi

diff=`compare -metric AE integration_test/maestro/expected.png $FILE null: 2>&1`

echo "Difference between images is $diff."

if [ $diff \> 3000 ];
then
    echo "FAILED: Difference between images is larger than the allowed 3000.";
    exit 1
else
    echo "PASSED: Images are a match.";
    exit 0
fi;
```

**Comment by chriswiesner** [comment]
would be really helpful to have that baked into maestro 👍

**Comment by amanzan** [comment]
@ben-milanko could you please share how you're actually using the bash script to compare screenshots in a flow?
