### ISSUE TITLE
Jetpack Compose test tags not visible

### ISSUE THREAD

**Issue by Jerry3737** [mobile-dev-inc/maestro#763]
Hello,

I encountered a problem, which I am not sure how to tackle. I'm trying to automate some UI tests on an jetpack compose android app, I asked the dev to put testTags accordingly to your spec on your web.  Here is a snippet: 

```
TextButton(
			modifier = Modifier
				.testTag(TagConstant.Common.SIGN_UP)
				.align(Alignment.CenterHorizontally)
				.padding(
					top = Dimens_normal200,
					bottom = Dimens_normal100,
					start = Dimens_normal100,
					end = Dimens_normal100
				),
			onClick = { onNavigate(LoginDestinations.SignUp) }
		)
```

Actual result: I am not able to see the test tags as IDs in maestro studio interface, nor when I try to execute `maestro hierarchy`. I can only select by text or screen coordinations. 

Expected result: After the dev added the testTags in the project, I am able to target an element by using the testTag as an ID

I ran `maestro bugreport`, here is the zip: [2023-02-09_121843.zip](https://github.com/mobile-dev-inc/maestro/files/10696502/2023-02-09_121843.zip)

**Comment by dmitry-zaitsev** [comment]
Could you try adding this to your Modifier:

```
        .semantics { testTagsAsResourceId = true }
```

**Comment by amanjeetsingh150** [comment]
Hey @Jerry3737 thanks for reaching out! Can you share the jetpack compose version as well?

**Comment by Jerry3737** [comment]
Hi @amanjeetsingh150 , the compose version is 1.4.0-alpha05
Hello @dmitry-zaitsev , I will try and get back to you, thanks!

**Comment by Jerry3737** [comment]
We added the semantics modifier, I am now able to see the resource id in the log after running `maestro hierarchy`, but I am not able to use the id selector in the studio interface. Still showing only coordinates and texts. 

Here is the hierarchy for the app before the semantics were added: https://codeshare.io/oQNE7Z
Here is the hierarchy for after semantics were added: https://codeshare.io/zywJNk 
Line 163 is the one with visible resource id
In the interface I am inspecting the element that the resource-id is visible for in the log.

**Comment by Jerry3737** [comment]
We added the semantics modifier, I am now able to see the resource id in the log after running maestro hierarchy, but I am not able to use the id selector in the studio interface. Still showing only coordinates and texts.

**Comment by Jerry3737** [comment]
@dmitry-zaitsev @amanjeetsingh150 

Hello, please any further update/advice on this problem? 

Thank you very much!

**Comment by strajky5** [comment]
As my colleague @Jerry3737 wrote we added `testTagsAsResourceId` parameter but Maestro UI interface still dont show us the ids. Only running maestro hierarchy contains ids. @chriswiesner Is it working for you to see ids in the Maestro UI interface?

**Comment by chriswiesner** [comment]
no, it is still not working for me in maestro studio, but using the id in the flow.yml is working (once `testTagsAsResourceId` is used - that's what i thought would be good to add in the docs)

**Comment by Jerry3737** [comment]
I can confirm that using the id in the flow.yaml file works. The problem then only is that IDs are not visible in maestro studio. Thanks @chriswiesner

**Comment by nilsjr** [comment]
I reported a similar issue in the slack channel. [Slack thread](https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1676555165670469)
@Leland-Takamine and @axelniklasson are on it.

**Comment by amanjeetsingh150** [comment]
> @dmitry-zaitsev We added the semantics modifier, I am now able to see the resource id in the log after running maestro hierarchy, but I am not able to use the id selector in the studio interface. 

Hey @Jerry3737 apologies for the late reply, do you mean you are able to select through tapOn commands but its not visible in maestro studio? Didn't understand what do you mean by visible in logs?

**Comment by amanjeetsingh150** [comment]
Hey, @Jerry3737 @chriswiesner thanks for reaching out, apologies on late reply. Can you send me the following details:

1. Resource id you are expecting
2. Output of maestro hierarchy command
3. Screenshot of maestro studio not inspecting the composable.

**Comment by amanjeetsingh150** [comment]
Ok, I see similar information in slack by @nilsjr. I'll try to reproduce this and look for a fix.

**Comment by nilsjr** [comment]
I tried to solve it. Not that familiar with react but it worked yesterday on my local machine. Maestro Studio will show every resource id when multiple elements share the same bounds.

Could you verified it? I could also create a PR if this is ok? 
My fork: [same-bounds-fix](https://github.com/nilsjr/maestro/tree/feat/element-check-same-bounds)

**Comment by axelniklasson** [comment]
Hi there @nilsjr, thank you so much for taking the time to work on a fix! If you wouldn't mind creating a PR I'll be happy to review 🙌

**Comment by amanjeetsingh150** [comment]
Hey folks, we have updated docs on how to enable testTagsAsResourceId in the modifier of composable: https://maestro.mobile.dev/platform-support/android-jetpack-compose

cc: @chriswiesner
