### ISSUE TITLE
Maestro UI automation test is working very hard

### ISSUE THREAD

**Issue by Yuldoshev** [mobile-dev-inc/maestro#789]
It freezes the computer when running YAML 3-4 times in a row, this is a very bad result (computer config: Macbook Pro, i7, 8th gen, 16GB RAM) it shouldn't work so hard with this configuration

**Comment by dmitry-zaitsev** [comment]
Please check for other running processes on your device. Maestro itself is not too intensive on resources, but your Emulator/Simulator or IDEs might be.

**Comment by Yuldoshev** [comment]
ok i will check thanks
