### ISSUE TITLE
Flutter container transform breaks element discovery

### ISSUE THREAD

**Issue by KirioXX** [mobile-dev-inc/maestro#796]
We have elements in our UI that use a [container transform](https://pub.dev/packages/animations#container-transform) from the flutter animated package.
But when I open the container the targets become  not tapable any more:
![Screenshot 2023-02-14 at 13 07 03](https://user-images.githubusercontent.com/11646702/218747657-0e39437d-b8e2-4d7f-9c4d-9ccb787f4861.png)
In mastro studio it almost looks like if the targets transformt to the background with the rest of the UI.

Here are the logs for my last run:
[2023-02-14_130819.zip](https://github.com/mobile-dev-inc/maestro/files/10732621/2023-02-14_130819.zip)
and the simulator I use is a:
iPad (10th generation)
iOS 16.2

Is there anything that I can try to get arround this issue for now?
Thank you!

**Comment by axelniklasson** [comment]
Hi there @KirioXX! Could you try [upgrading to the latest version of maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) and let us know if this issue still persists? Thanks!

**Comment by bartekpacia** [comment]
Hey, thanks for creating this issue - unfortunately, it's not easily reproducible. We have a huge backlog, so it's important we can triage issues in an efficient manner.

Please provide a [minimal, reproducible example] that clearly explains how to reproduce the problem with the detailed, step-by-step instructions (that can be easily run by me or other maintainers).

[minimal, reproducible example]: https://stackoverflow.com/help/minimal-reproducible-example
