### ISSUE TITLE
Wrong resolution on Safari Browser 

### ISSUE THREAD

**Issue by matt400m** [mobile-dev-inc/maestro#809]
Hi,

I have problem with resolution on Safari Browser (Image). Maestro studio works looks good on Chrome, Firefox.

Version 16.2 (18614.3.7.1.5)

reproduce:
1. Set safari as default browser
2. run maestro studio
3. wait until browser appear

<img width="1767" alt="image" src="https://user-images.githubusercontent.com/9861688/219699006-8aa86e1a-0fe0-42aa-b628-93b66e5701f9.png">

**Comment by axelniklasson** [comment]
Thanks for raising this issue @matt400m, I'm taking a look at this now!
