### ISSUE TITLE
[BUG] Android 13 Issues: System share sheet and initial test startup

### ISSUE THREAD

**Issue by simon-gilmurray** [mobile-dev-inc/maestro#814]
Two issues I've noticed when testing against an Android 13 emulator that don't affect previous versions of Android:

1. Tapping on a system share sheet brings it up and immediately dismisses it on Android 13. On previous versions, tapping it leaves it up as expected until dismissed.

2. Tests seem to fail when starting quite a bit due to Maestro acting and tapping on elements before they are visible to the user as the app is still opening up. This is probably due to the speed of Android 13 but it should be waiting for animation to settle a bit better I think. I don't have any of these issues on Android 12 or previous, so I have had to add in a `- waitForAnimationToEnd: timeout: 1500` command just to handle this, but even that is often failing so I'm not sure if the issue is deeper here

**Comment by axelniklasson** [comment]
Thanks for reporting this Simon, we'll make sure to take a look at this.

**Comment by simon-gilmurray** [comment]
Also experienced by Thomas here:

"Thomas Vackier
  [4 hours ago](https://mobile-dev-inc.slack.com/archives/C041FU72T54/p1677848116411759?thread_ts=1677847974.074419&cid=C041FU72T54)
Seeing the same, restarting adb solves this for me somehow. ¯\_(ツ)_/¯"

**Comment by axelniklasson** [comment]
Hi there Simon! Could you try [upgrading to the latest version of maestro](https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli) and let us know if this issue still persists? Thanks!
