### ISSUE TITLE
Ability to specify start/end values in swipe when using from

### ISSUE THREAD

**Issue by kyleder** [mobile-dev-inc/maestro#820]
I have a use case where I need to change the value of a horizontal slider component. I can target the view using a testID which opens up the option of using the `swipe` functionality with `from` and `direction` specified, however, since the component needs to start from a specific point within the view, those two values alone are insufficient.

The starting state of the component looks like this:
<img width="304" alt="Screenshot 2023-02-20 at 9 56 38 PM" src="https://user-images.githubusercontent.com/103979/220259903-1f802c81-64dc-4ca7-8449-c47c6213341d.png">

...and once it is interacted with (control dragged from left to right) then it looks like:
<img width="304" alt="Screenshot 2023-02-20 at 9 56 50 PM" src="https://user-images.githubusercontent.com/103979/220260007-6b0b869a-8fdb-4c6d-aebe-10ffa405ebe8.png">

If the `start` and `end` options were available when `from` is specified and their values were relative to the containing view then it feels like this would be easy to achieve. For example:

```
- swipe:
    from:
      id: "score-slider"
    start: "5%, 50%"
    end: "90%, 50%"
```

Is there an alternative solution to using `swipe` for this use case? If not, is there any chance that `swipe` will be extended at some point to support this?

**Comment by Leland-Takamine** [comment]
I think it'll unfortunately be hard for us to prioritize this as it's a bit of an edge case. Going to close this out in an effort to clean up our issues. That said, we are always open to contributions to the project if you are interesting in taking a stab!
