### ISSUE TITLE
Supply mobile.dev API key via environment variable

### ISSUE THREAD

**Issue by whlk** [mobile-dev-inc/maestro#822]
Currently the [cli requires the mobile.dev api key as a param](https://cloud.mobile.dev/ci-integration/integration-with-any-ci-platform#2.-run-the-maestro-cloud-command) (i.e. `maestro cloud --apiKey=xyz`). This is not optimal when the tests are run on a CI platform, where the cleartext key can be seen in the logs. 

I therefore propose the option to supply the API key also via environment variable (i.e. `MOBILE_DEV_API_KEY`).

**Comment by axelniklasson** [comment]
Hi @whlk, that makes sense to me. We are planning to add support for loading env variables in a more seamless way so this will be addressed. Will let you know once this gets supported.

**Comment by axelniklasson** [comment]
@whlk in version `1.24.0` of maestro you can define an environment variable called `MAESTRO_CLOUD_API_KEY` in your shell and maestro will use that one instead of requiring you to log in or pass it via `--apiKey`.
