### ISSUE TITLE
Maestro occassionally double or triple taps elements.

### ISSUE THREAD

**Issue by arancauchi** [mobile-dev-inc/maestro#826]
I'm setting up maestro within our app, and most things are working well besides one issue.

When interacting with some of our UI elements, maestro will double or triple tap an element on screen.

This consistently happens in a certain part of our app. It doesn't matter if we reference the `tapOn` event with an id to an element or by its text, maestro will occasionally press the element twice or three times before continuing.

Has anyone else seen this issue before?

**Comment by dmitry-zaitsev** [comment]
Could you attach a screen recording of the issue? That would help us a lot.

When tapping on an element, Maestro assumes that something should change on the screen before moving forward (i.e. a view hierarchy should be different or screen state should change). If nothing changed, Maestro will attempt to tap again.

You can disable this behaviour: https://maestro.mobile.dev/troubleshooting/known-issues#android-accidental-double-tap

**Comment by arancauchi** [comment]
Sorry, but I unfortunately can't share a video due to company policy.
It seems to be intermittent, and seems to only happen in CI (perhaps due to the emulator loading more slowly?).

The `retryTapIfNoChange` seems to address the issue. I assume it's something to do with the fact we're making async requests on each button tap and the UI isn't updating in realtime, but only when a roundtrip to the server updates our data as a result of the press.

**Comment by Leland-Takamine** [comment]
@arancauchi [Disabling this behavior](https://maestro.mobile.dev/troubleshooting/known-issues#android-accidental-double-tap) should fix the issue. That said, we do want to debug this so if you can provide a sample project to reproduce this issue, please reopen and we'll dive in further!
