### ISSUE TITLE
Support for long press

### ISSUE THREAD

**Issue by aitorvs** [mobile-dev-inc/maestro#83]
We've been trying maestro intertnally and it's great btw!

Some of our tests require long press actions but I don't think that's currently supported. Is it something we missed in the documentation? 
Or if indeed not supported, any plans for it?

**Comment by dmitry-zaitsev** [comment]
It is indeed not supported yet, but it is an easy feature to add. You can expect it around this week

**Comment by aitorvs** [comment]
You're awesome! thanks a lot

**Comment by dmitry-zaitsev** [comment]
Since version 1.3.6 you can use a `longPressOn` command. [Documentation](https://maestro.mobile.dev/reference/tap-on-view#long-press)

```
- longPressOn: Hello World
```

**Comment by aitorvs** [comment]
This is awesome!!
