### ISSUE TITLE
Detect Maestro in React Native fails

### ISSUE THREAD

**Issue by 7assenTlili** [mobile-dev-inc/maestro#834]
Hey! I am trying to detect Maestro from within a React Native app running on iOS simulator.
To achieve this I am using `react-native-tcp-socket` to connect to the socket using the right port number.
```js
import TcpSocket from 'react-native-tcp-socket';

const options = {
  port: 9080,
  host: '127.0.0.1',
  localAddress: '127.0.0.1',
};

const socket = TcpSocket.createConnection(options, () => {
  // Write on the socket
  socket.write('Hello server!');
});

socket.on('data', function (data) {
  console.log('[SOCKET DATA] message was received', data);
});

socket.on('error', function (error) {
  console.log('[SOCKET ERROR]', error);
});

socket.on('close', function () {
  console.log('[SOCKET CLOSE] Connection closed!');
});
```
but I always get connection refused:
```
[SOCKET ERROR] Connection refused
[SOCKET CLOSE] Connection closed!
```

Am I missing something here?

**Comment by amanjeetsingh150** [comment]
Hey @7assenTlili can you try with port 22087, Also there is a library if you are interested to check if maestro is running the app: https://github.com/jpudysz/react-native-is-maestro

I will change the documentation to correctly mention this port.

**Comment by 7assenTlili** [comment]
Thank you @amanjeetsingh150 ! port 22087 worked for me.
Unfortunately `react-native-is-maestro` requires RN >= 0.71.0
