### ISSUE TITLE
Feature Request: Windows driver

### ISSUE THREAD

**Issue by wollac11** [mobile-dev-inc/maestro#836]
Maestro is already great for simplifying UI testing of cross-platform applications on Android and iOS and the experimental web driver also shows some promise.

It would be incredibly helpful to also have support for this extended to include MAUI Win UI and UWP applications on Windows. Perhaps Maestro could have a Windows driver which wraps around WinAppDriver from Microsoft (https://github.com/Microsoft/WinAppDriver)?

**Comment by axelniklasson** [comment]
Hi @wollac11, this would be a cool use case for Maestro but unfortunately not something that we are prioritizing at this point. We are welcoming PRs though so if you want to take a stab at it and contribute, please feel free to do so 🙂
