### ISSUE TITLE
fastlane plugin

### ISSUE THREAD

**Issue by inf2381** [mobile-dev-inc/maestro#841]
Hi 👋 , I was wondering whether you are planning to add support for [fastlane](https://fastlane.tools/) to maestro. As I did not find any issue or code for it, I created a fastlane plugin to run maestro in a fastlane lane ([link](https://github.com/inf2381/fastlane-plugin-maestro)). I would be happy transfer the ownership of the repository to mobile-dev-inc and contribute from there on.

**Comment by marckrenn** [comment]
Ahh, that's great! I've also worked on two pretty feature-rich `maestro_build` and `maestro_test` lanes and I'd love to collaborate 😊

These are probably a bit too opinionated for general use, but maybe there's a feature or two that could find its way in an "official" lane:
* Designed for local and CI use
* (Meta) parameters handling (via config.json file, CI variables and fastlane parameters)
* Parameter injection, eg. from CI-variable to Maestro test, to hide sensitive login-data
* Builds .app once, installs .app and spools up appropriate simulator based on the file-structure pictured below
* <img width="956" alt="Screenshot 2023-03-06 at 12 12 46" src="https://user-images.githubusercontent.com/2648540/223094867-310536d1-1da1-4de4-8d93-d05012544b7f.png">
* Supports xml-reports and auto-downloading of recordings (which can then be exposed as CI artifacts)
* Multithreading support, in theory, which allows tests to be run on multiple simulators in parallel ([once Maestro supports it](https://github.com/mobile-dev-inc/maestro/issues/859))

**Comment by p-nicolaou** [comment]
@inf2381 Thank you for the fastlane plugin! I would like to ask,
is there any way to pass environmental variables to maestro? I used to do it externally on the command line but, I couldn't find any way using fastlane.

**Comment by Leland-Takamine** [comment]
Hey @inf2381 - thank you very much for building this out! What we've done for now is document this in our community contributions page: https://maestro.mobile.dev/community/contributions . We're thinking about building out a section in our docs specifically on Fastlane integration (which would link out to your plugin), but that hasn't been finalized yet.

Going to close this issue out, but make sure to join our [Slack channel](https://docsend.com/view/3r2sf8fvvcjxvbtk) so we can continue the conversation!
