### ISSUE TITLE
[Feature_Request] Support optional flag with extendedWaitUntil & visible/notVisible with timeouts

### ISSUE THREAD

**Issue by susanabraham-tomtom** [mobile-dev-inc/maestro#846]
**### Requirement** : Right now there is not action to force wait the app on a fixed time of duration , if we can support "optional" flag with 

- extendedWaitUntil:
    notVisible/visible:
    optional:
    timeout: 

we can achieve the force wait in larger performance related test cases (e.g keeping app for longer duration of time and cross check for memory leaks )

**Comment by axelniklasson** [comment]
@susanabraham-tomtom Thanks for raising an issue! If I'm understanding this correctly this is just another way to essentially support a sleep command to make the flow wait for a given period of time, right?
