### ISSUE TITLE
Bug Maestro Studio in Safari

### ISSUE THREAD

**Issue by aymane-missouri-nw** [mobile-dev-inc/maestro#852]
when i run maestro studio in safari , this is what i see
<img width="1512" alt="Screenshot 2023-03-02 at 13 07 53" src="https://user-images.githubusercontent.com/104450977/222426521-4a98069c-24d0-4216-a7fc-42dc2883319c.png">

**Comment by axelniklasson** [comment]
@aymane-missouri-nw this is fixed and will go out in the next release (ETA next week). Thanks for reporting!
