### ISSUE TITLE
Question: how to assert on snackbars?

### ISSUE THREAD

**Issue by aitorvs** [mobile-dev-inc/maestro#86]
I was trying to make a test to verify a snackbar appears. But the snackbar seems to dissappear (long delay) before Maestro can detect it. I am basically asserting visibility on the snackbar text.
Am I doing something wrong?

**Comment by dmitry-zaitsev** [comment]
If it is for a publicly available app, could you please share:

- The flow that you are running
- The app you are running it on

**Comment by aitorvs** [comment]
I'm travelling right now but will prep a repro for you

**Comment by dmitry-zaitsev** [comment]
Closing until more context is available
