### ISSUE TITLE
Query or hierarchy command doesn't return all elements in a scrollview

### ISSUE THREAD

**Issue by franklbt** [mobile-dev-inc/maestro#866]
Hi,

I'm trying to assert a scroll view contains some elements.

But the query or hierarchy commands doesn't return all elements in a scroll view, but only the ones that are visible.

Is there a way to return all loaded elements ?

Maestro version: 1.23.0
OS: Windows 11 + WSL 2

**Comment by Leland-Takamine** [comment]
You should be able to use the `scrollUntilVisible` command to achieve this: https://maestro.mobile.dev/api-reference/commands/scrolluntilvisible Feel free to reopen if this doesn't solve your use case!
