### ISSUE TITLE
[1.24.0] Hierachy returns no elements on iOS

### ISSUE THREAD

**Issue by AlexanderEggers** [mobile-dev-inc/maestro#872]
On certain screens in my app I get no hierachy elements returned. Maestro studio is also not recognizing any elements on these screens. This issue only happens from time to time and is not consistent.

```
{
  "attributes" : { },
  "children" : [ {
    "attributes" : {
      "bounds" : "[0,0][0,0]"
    },
    "children" : [ ],
    "enabled" : true
  } ]
}
```

**Comment by matt-dalton** [comment]
I'm also now getting this

**Comment by matt-dalton** [comment]
Also...Maestro studio seems to not let you select any elements any more?

**Comment by matt-dalton** [comment]
Is there any other info we can give to help recreate this @berikv ? I'm getting it fairly reliably on a particular flow (and is blocking our suite). I'm on version 1.25.0.

Basically running through our entire onboarding is fine, then as soon as we land on the home screen (where there's lots more going on - multiple tabs, scrollable sections etc) the tests can't assert against any elements. Running `hierarchy` returns the above and studio is unable to inspect.

I can restart the simulator and go to the same screen and everything is fine. So something must happen when running the tests.

**Comment by Leland-Takamine** [comment]
@AlexanderEggers @matt-dalton Can you try again on the latest Maestro version please and let us know if this is still an issue? Thanks! https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli

**Comment by axelniklasson** [comment]
@AlexanderEggers @matt-dalton Does this happen on native iOS or are you using a framework such as React Native/Flutter or something else? Is there a way for us to reproduce this issue?  If you could run `maestro bugreport` when this happens and share the logs with us here that would be much appreciated.

**Comment by axelniklasson** [comment]
Hi @AlexanderEggers, I'll go ahead and close this out for now. Please file a new bug report [here](https://github.com/mobile-dev-inc/maestro/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BMaestro+version%2C+e.g.+v1.2.3%5D) if you are still experiencing issues!
