### ISSUE TITLE
[1.24.0] List elements on iOS are not including resource ids anymore

### ISSUE THREAD

**Issue by AlexanderEggers** [mobile-dev-inc/maestro#873]
When running maestro studio or maestro hierarchy on a screen with a list structure, every list element only returns its bounds and text but no resource-id is found. That used to work on 1.23.0.

**Comment by artem888** [comment]
hey @AlexanderEggers ! We're able to reproduce the issue locally, working on the resolution. Thanks for your feedback, we'll keep you posted.

**Comment by Leland-Takamine** [comment]
@AlexanderEggers Can you please try again on the latest Maestro version? If this is still an issue we will dive in of course! https://maestro.mobile.dev/getting-started/installing-maestro#upgrading-the-cli

**Comment by axelniklasson** [comment]
Hi @AlexanderEggers, I'll go ahead and close this out for now. Please file a new bug report [here](https://github.com/mobile-dev-inc/maestro/issues/new?assignees=&labels=bug&projects=&template=bug_report.md&title=%5BMaestro+version%2C+e.g.+v1.2.3%5D) if you are still experiencing issues!
