### ISSUE TITLE
tapOn contentDescription is not working when android:hint or android:text is present

### ISSUE THREAD

**Issue by jaychang0917test** [mobile-dev-inc/maestro#876]
Hi, for the`tapOn` command, can we force to find the view by `contentDescription` (in android)? The problem is if the `android:hint` and `android:contentDescription` are both present, maestro will use the hint one to locate the view, but what i expected is find the view by `contentDescription` instead.

For example: the command - tapOn: "content" is not working to locate this EditText
```
<EditText
     android:layout_height="wrap_content"
     android:layout_width="match_parent"
     android:hint="hint"
     android:contentDescription="content"
 />
```
The same issue happens for TextView when both android:text and `android:contentDescription` are present, maestro always use the `android:text`

So, is this behaviour expected? or can we force to find the view by `contentDescription` (in android)? Thanks

**Comment by amanjeetsingh150** [comment]
Hey @jaychang0917test we have added support to select elements through contentDescription as well. You just need to mention the accessibility text in the text attribute:

```
- tapOn: "accessibility-text-here"
```

Let me know if this works. Feel free to reopen issue if something works unexpected.
