### ISSUE TITLE
add SMS permission group

### ISSUE THREAD

**Issue by depapp** [mobile-dev-inc/maestro#889]
I have a use case to allow SMS permissions on the app that I'm test using Maestro, since Maestro support #864 

I would like to add new `group` for the `sms permissions`
```kotlin
            "sms" -> listOf(
                "android.permission.READ_SMS",
                "android.permission.RECEIVE_SMS"
                "android.permission.SEND_SMS"
            )
```

what do you think @amanjeetsingh150 @dmitry-zaitsev , can I create a PR for this?

**Comment by amanjeetsingh150** [comment]
Sure go ahead 💯
