### ISSUE TITLE
Icons cannot be accessed other way than using coordinates

### ISSUE THREAD

**Issue by nicoletasima** [mobile-dev-inc/maestro#890]
In our app we have some elements we want to access, but they are icons. In maestro studio these elements are identified only by coordinates.
We want to access them using xpath, ids or other properties.

**Comment by nicoletasima** [comment]
This is what maestro studio returns: `This element has no resource id associated with it. Type ‘⌘ D’ to view platform-specific documentation on how to assign resource ids to ui elements.`

**Comment by bartekpacia** [comment]
To interact with icons/image, set semantics information on them, e.g. accessibility identifiers. Does that answer your question?
