### ISSUE TITLE
Docs should be updated to uninstall maestro if installed with brew

### ISSUE THREAD

**Issue by ColtonIdle** [mobile-dev-inc/maestro#919]
I posted a question in slack about whether or not to use brew to install (since the docs only mention uninstalling with brew. nothing about installing with brew). Someone (I think from maestro team) said not to use brew anymore. to uninstall maestro with brew, then use the command to install.

sooo. someone should update the docs to state that.

**Comment by ArthurSav** [comment]
Thanks for reporting this issue. Docs have been updated to reflect this.
