### ISSUE TITLE
Subflows and integrate them into other flows

### ISSUE THREAD

**Issue by BenedictP** [mobile-dev-inc/maestro#92]
Would be nice to have "subflows" wich can be written without an `appId` or `launchApp` command and they can be called from other flows.
Our use case: When we want to test our checkout flow the user needs to enter the billing details (name, phone number etc.) after this the user can select a payment method. Of course, we want to test the checkout flow with different payment methods but currently, we need to do a lot of copy and paste because of the billing details screen which is error-prone and annoying ;)

**Comment by dmitry-zaitsev** [comment]
This is currently supported via a concept of `initFlow` ([docs](https://docs.mobile.dev/reference/app-state-restoration)).

**Comment by BenedictP** [comment]
Can an initFlow call an flow which also has an initFlow inside?

**Comment by dmitry-zaitsev** [comment]
After looking into it a bit more, perhaps `initFlow` is not exactly what you have in mind here. We will think on how to add some sort of an `import` command

**Comment by dmitry-zaitsev** [comment]
This is now solved by `runFlow` command released as part of 1.8.0
