### ISSUE TITLE
Scroll to a specific view

### ISSUE THREAD

**Issue by BenedictP** [mobile-dev-inc/maestro#93]
Would be nice to have a command to scroll to a specific view in the list.
E.g.
- scrollTo
    text: "Text"

**Comment by Barryrowe** [comment]
Based on other tickets, this is in the works. Does the team know if this will support both already views beyond the frame, and views that have not yet been created during the scroll?  (ie. recyclerView items)?

**Comment by Isos9** [comment]
Hello, I would like to suggest a scrollFrom, because some part of screen are not vertically scrollable if there is a carousel for example, and if this carousel is at the top of the screen, where the default scroll start, then it doesn't scroll.

**Comment by dmitry-zaitsev** [comment]
`scrollUntilVisible` command solve this issue
