### ISSUE TITLE
Unrecognized field "runScript"

### ISSUE THREAD

**Issue by BharathSaraswathi** [mobile-dev-inc/maestro#934]
Could not parse Flow file:

Unrecognized field "runScript" (class maestro.orchestra.yaml.YamlFluentCommand), not marked as ignorable (22 known properties: "tapOn", "openLink", "assertNotVisible", "longPressOn", "assertVisible", "inputRandomPersonName", "launchApp", "inputRandomEmail", "extendedWaitUntil", "eraseText", "action", "inputText", "runFlow", "inputRandomText", "repeat", "pressKey", "stopApp", "clearState", "takeScreenshot", "inputRandomNumber", "swipe", "setLocation"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: java.util.ArrayList[2]->maestro.orchestra.yaml.YamlFluentCommand["runScript"])

**Comment by BharathSaraswathi** [comment]
I am trying to read a username and password from testData.js file into my SigninTest.yaml script and seeing the error posted above. Please help.
Code Snippet as below.

- launchApp
- runScript: consumerTestData.js
- assertVisible:
    text: "Select location"
- tapOn:
    text: "Select location"
- tapOn:
    text: "United States (US)"
- tapOn:
    text: "Login"
- tapOn:
    id: "email_text"
- inputText: ${output.consumer.username}

**Comment by igorsmotto** [comment]
Hey @BharathSaraswathi
Could you share which Maestro version are you running?
`maestro -v`

**Comment by ArthurSav** [comment]
This seems like an issue with formatting in your yaml file.
If the issue persists we can re-open this.

**Comment by manish270820** [comment]
getting same issue...below yml is working o emulator but not in real device.
`appId: com.*****.***
---
#- runFlow: ../Login/enterPin.yaml
- runFlow: ../login/loginFlow.yaml

- waitForAnimationToEnd:
    timeout: 3000

- tapOn:
    text: "Crypto"
    index: 1

- scrollUntilVisible:
    element: "Popular Crypto"
    direction: "DOWN"
#    speed: 100
#    visibilityPercentage: 100

- tapOn: "AssetCard Bitcoin"

- tapOn: "Buy"

- tapOn: "SIP"

- tapOn: "   0"
- inputText: "113"
- hideKeyboard

- tapOn: "Edit Date"
- assertVisible: "SIP Instalment Date"

#- tapOn: "3"
- back
- tapOn: "Next"

- assertVisible: ".*SIP"
- assertVisible: ".*1st Instalment.*"

- tapOn: "Trade Preview Button"

- waitForAnimationToEnd:
    timeout: 3000

- runFlow:
    when:
      visible:
        text: "Submit"
    commands:
      - tapOn: "8"
      - tapOn: "Submit"

- assertVisible: "Woohoo!"
- assertVisible: "Manage SIP"

- tapOn:
    delay : 300
    text : "Manage SIP"

- assertVisible: "Orders & History"
- assertVisible:
    text: "Open"
    index: 1

- assertVisible:
    text: "History"
    index: 1

- assertVisible: "SIP"
- assertVisible: "Active"

- tapOn:
    text: "SIP BTC"
    index: 0

#- assertVisible: "Amount"
#- assertVisible: "Frequency"
#- assertVisible: "Next Instalment"

- tapOn: "Pause SIP"

- assertVisible: "Are you sure you want to Pause SIP?"

- tapOn: "Yes, Pause"

- assertVisible: "SIP has been paused successfully"

- assertVisible: "Paused"

- tapOn: "Paused"

- assertVisible: "Activate SIP"
- tapOn: "Activate SIP"
- tapOn: "Yes, Activate"

- assertVisible: "SIP has been resumed successfully"

- assertVisible:
    text: "Active"
    index: 0
`


getting below issue , please help me on this

`Unrecognized field "runScript" (class maestro.orchestra.yaml.YamlFluentCommand), not marked as ignorable (22 known properties: "tapOn", "openLink", "assertNotVisible", "longPressOn", "assertVisible", "inputRandomPersonName", "launchApp", "inputRandomEmail", "extendedWaitUntil", "eraseText", "action", "inputText", "runFlow", "inputRandomText", "repeat", "pressKey", "stopApp", "clearState", "takeScreenshot", "inputRandomNumber", "swipe", "setLocation"])
`
