### ISSUE TITLE
public maestro slack channel is not accessible

### ISSUE THREAD

**Issue by jbentonGx** [mobile-dev-inc/maestro#937]
I wanted to ask some questions and could not get access to slack.

Going to the link for the public maestro slack channel, I needed to create an account. The account creation is limited to `@fetchrewards.com` email addresses.

Our company only allows access to other slack channels via shares that we initiate. Is there a way that could be arranged?

**Comment by igorsmotto** [comment]
Hey @jbentonGx, where did you get the slack access link? 
I've just tried to access using the invite link here: https://mobile-dev-inc.slack.com/join/shared_invite/zt-1g5nn4yx1-59gW6Wt0gP5JgXoxtiRq0w (present in the README) and it worked fine

**Comment by jbentonGx** [comment]
The link in the README worked. So I guess you should update the link on that bug-report page.

**Comment by igorsmotto** [comment]
Thanks for reporting! I'll update it.
