### ISSUE TITLE
Using Maestro programmatically accept a yaml file as argument

### ISSUE THREAD

**Issue by BenedictP** [mobile-dev-inc/maestro#94]
How I would like to use Maestro:
Developers can write tests with the Maestro CLI locally and add them to a folder in our app repository.
For running them on the CI, I would use the programmatic approach and create a small script to get all files from this folder and run them one by one with the programmatic approach.
Why? Our CI system runs on Linux, so I can not install the Maestro CLI with brew.

**Comment by dmitry-zaitsev** [comment]
Maestro does in fact work on Linux (as it is written in Kotlin) and can be installed via Homebrew (that also works on Linux, with [few tweaks](https://docs.brew.sh/Homebrew-on-Linux)). I have update our documentation with steps on how to install it: https://maestro.mobile.dev/getting-started/installing-maestro#cli

Programmatic usage of Maestro is also possible, albeit I would not recommend it for your use case. If you would still like to try, add Maestro as a [Gradle/Maven dependency ](https://maestro.mobile.dev/getting-started/installing-maestro#gradle), read commands by using `YamlCommandReader`, create a `Maestro` instance (i.e. `Maestro.android()`), and pass it all to `Orchestra` class.
