### ISSUE TITLE
Using Maestro break iOS Pagination logic causing app to freeze and tests failing

### ISSUE THREAD

**Issue by kunalverma25** [mobile-dev-inc/maestro#954]
This issue is easily reproducible on any iOS app which has a pagination functionality.

The scenario -

Open an iOS app's page where it has a list, which is paginated and can contain thousands of list items when fully scrolled.

If I run the app without maestro test/studio the app works fine without any issues.

But if I run the maestro studio or any test on that page the app basically gets stuck..

And the test cases fail.

This is happening due to the way Maestro gets the view hierarchy.

On the inspect page in Maestro studio the list also contains elements which should not even be created at point of time as the test has not done any scrolling.

This could mean that somehow in order to get the view hierarchy of the page, Maestro is interfering with the app's pagination logic which is causing memory issues and causing the app to freeze and tests to fail.

**Comment by ArthurSav** [comment]
Hi @kunalverma25 
There's a fix for this, checkout here our docs [here](https://maestro.mobile.dev/troubleshooting/known-issues#ios-issues-with-lists-uicollectionview-uitableview-that-fetch-data-on-scroll)
