### ISSUE TITLE
Maestro Cloud: Cannot reference sub flows outside of the test folder

### ISSUE THREAD

**Issue by pocmo** [mobile-dev-inc/maestro#956]
We have a complex structure to share flows between apps with similar features, roughly:

```
apps/app1/test-cases
apps/app2/test-cases
features/feature1
features/feature2
...
```

Test cases of apps reference flows from feature folders. Locally everything is fine, but when I try to upload to maestro cloud, using something like:

```
maestro cloud /path/to/apk/myapp.apk ./apps/app1/test-cases/android
```

Then this results in a 400 error:

```
Upload request failed (400): Flow file does not exist: jar:file:///tmpFiles/workspaces/workflowXXXX.zip!/./../../feature/feature1/someflow.yaml
```

It seems like I cannot reference sub flows that are outside of the test folder that I specify with `maestro cloud`. It seems to work only for sub flows that are in the test folder or in a sub folder of it.

**Comment by igorsmotto** [comment]
Hey @pocmo 
Yes, that's right. When you run `maestro cloud` to a folder, this folder is zipped and sent through. Since your flow has references outside of what is being zipped that's why you get the error.

My suggestion is to either send the topmost folder of your workspace that contains all the flow files and use [inclusion patterns](https://maestro.mobile.dev/cli/test-suites-and-reports#inclusion-patterns) to select the flows to run
Or to create some kind of shell script that would move all the required files to a temporary directory before uploading.

**Comment by pocmo** [comment]
Thank you @ArthurSav!

In the meantime we applied the workaround @igorsmotto mentioned:
> My suggestion is to either send the topmost folder of your workspace that contains all the flow files and use [inclusion patterns](https://maestro.mobile.dev/cli/test-suites-and-reports#inclusion-patterns) to select the flows that you wish to run

The only downside of this seems to be that this will send all flows that are reachable from the topmost folder, regardless of the filter. But of course only the filtered flows will be executed.

**Comment by axelniklasson** [comment]
Hi there @pocmo. Glad you found a workaround! We have some improvements in terms of UX when it comes to uploading Flows in our backlog, so stay tuned for future updates.

**Comment by pocmo** [comment]
Thank you, @axelniklasson. I will wait for those. :)

Here are some suggestions from my experience:
- I would like to see the filter applied locally and then only upload those flows (It seems like with a filter still every flow gets uploaded)
- I would like maestro to follow the include statements and upload subflows regardless of their location in relation to the selected/included flows
- I would like to see a warning when placeholders in (to be uploaded) flows are not set
