### ISSUE TITLE
Feature Request: Combine filtered tags with AND instead of OR

### ISSUE THREAD

**Issue by pocmo** [mobile-dev-inc/maestro#962]
A follow-up from #956, trying to use tags to filter flows.

Our repository contains test for multiple apps (app1, app2, app3, ...) and platforms (android, iOS, web).

I would like to use `--include-tags` to run only the flows for a specific app and platform in automation. For example `app1` AND `android`.

I tried using `--include-tags=app1,android`, but that actually includes all flow for `app1` on all platforms and all flows for `android` for all apps (`OR` instead of `AND`).

The only workaround is to exclude everything else in the matrix, e.g. with `--exclude-tags=ios,web,app2,app3`. But this is getting really cumbersome and adding an additional app requires updating all exclude tags everywhere.

**Comment by igorsmotto** [comment]
This looks like a good suggestion. My only concern is that I'm not sure what the API should look like.

As a workaround, what do you think about adding a new tag for these flows: `app1android`? (in addition to the tags that you already have)
This way you would only include: `--include-tags=app1android`

**Comment by pocmo** [comment]
> As a workaround, what do you think about adding a new tag for these flows: app1android? (in addition to the tags that you already have)
This way you would only include: --include-tags=app1android

Thank you for this suggestion. I think that would work for us!
