### ISSUE TITLE
No green check marks when test is done

### ISSUE THREAD

**Issue by aleksandar-cypress** [mobile-dev-inc/maestro#978]
When I run test in WSL2, i dont see what test has failed and what is OK, 

![Screenshot 2023-04-06 130829](https://user-images.githubusercontent.com/84180386/230360349-91922b4e-7f23-4f0c-bb37-ffb63e2d9886.png)

does anyone knows how to fix this ?

**Comment by felipevolpone** [comment]
This is probably related to either the font you're using in your terminal or the terminal app itself. Please try another one or raise this question in our Slack [1] and check what people with Windows are using.

[1] https://mobiledev.typeform.com/to/FelIEe8A
