### ISSUE TITLE
`maestro test` fails with "ReferenceError: ReferenceError: "term" is not defined. (inline-script#1)}"

### ISSUE THREAD

**Issue by lng-stripe** [mobile-dev-inc/maestro#983]
As the title says. Trying maestro on the first time for Android. It fails for both connected device and emulator.

Reproducible on maestro versions 1.24.0 and 1.25.0. Not an issue on 1.23.0.

```
$ maestro test flow.yaml
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true -Dcom.sun.jndi.ldap.object.trustURLCodebase=false
Running on emulator-5554

ReferenceError: ReferenceError: "term" is not defined. (inline-script#1)}
```

flow.yaml:
```
appId: [redacted]
---
- launchApp
```

**Comment by axelniklasson** [comment]
Closing this out. If this is still an issue, please file a new bug report with the requested information in the bug report template. Thanks!
