### ISSUE TITLE
can not use a subFlow in mainFlow via --include-tags

### ISSUE THREAD

**Issue by haci56** [mobile-dev-inc/maestro#985]
Hey , I'm trying to run a mainFlow that contains a subFlow using the **--include-tags** but i get error
that is my project structure

```
project/
    android/ 
        LoginApp.yaml (relative path = android/LoginApp.yaml)
        subflows/  (relative path = android/subflows)
            LaunchApp.yaml  (relative path = android/subflows/LaunchApp.yaml)
```

that is my main flow >>  #LoginApp.yaml
 ```
#LoginApp.yaml

appId: ${APP_ID}
tags: 
  - debug   
---
- runFlow : subflows/LaunchApp.yaml   
``` 
that is my subflow >> LaunchApp.yaml
```
appId: ${APP_ID}
---
- launchApp :
    clearState: false
```
once I use following command :
` maestro test --format=JUNIT -e APP_ID='com.xx.xx.xx' --include-tags=debug  android `

I get following error :
`maestro.orchestra.error.InvalidFlowFile: Flow file does not exist: file:///Users/.../android/LaunchApp.yaml`

but once i use following command :
`maestro test --format=JUNIT -e APP_ID='com.xx.xx.xx' --include-tags=debug  android/LoginApp.yaml `

it works properly. But in that case it is not a solution for me because i want to control my test runs via tags.
Is it an expected behavior, is there a workaround solution ?

**Comment by retyui** [comment]
try `android/config.yaml` with

```yaml
flows:
  - "*" # Run only "flows/*.yaml" (ignoring flows/_subflows/*.yaml)
```
